Repository charmverse/app.charmverse.io, pull requests merged in 2022-09, with the labels that each got.

#861 Create and configure proposal reviewers and authors
  __integration-tests__/server/pages/api/proposals/[id].spec.ts
  charmClient/apis/proposalsApi.ts
  charmClient/charmClient.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalStatusBadge.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/index.ts
  components/[pageId]/EditorPage/EditorPage.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/NewBountyButton.tsx
  components/common/Page/PageDialog.tsx
  components/common/form/InputSearchContributor.tsx
  components/common/form/InputSearchReviewers.tsx
  components/votes/components/NewProposalButton.tsx
  components/votes/components/VotesTable.tsx
  jest.config.ts
  lib/pages/addPage.ts
  lib/pages/interfaces.ts
  lib/permissions/pages/triggers/page-created.ts
  lib/proposal/__tests__/createProposal.spec.ts
  lib/proposal/__tests__/updateProposal.spec.ts
  lib/proposal/createProposal.ts
  lib/proposal/interface.ts
  lib/proposal/updateProposal.ts
  pages/api/pages/index.ts
  pages/api/proposals/[id].ts
  prisma/migrations/20220830161918_proposal_init/migration.sql
  prisma/migrations/20220831103842_proposal_page_rel/migration.sql
  prisma/migrations/20220831172926_proposal_role/migration.sql
  prisma/migrations/20220901154320_remove_proposal_group/migration.sql
  prisma/schema.prisma
  scripts/migrateProposal.ts
  testing/setupDatabase.ts
  theme/colors.ts
Labels: work-in-progress, :rocket: deploy

#866 Fixing prd tags
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  docker-compose.yml
Labels: :rocket: deploy

#873 create global page dialog
  .eslintrc.json
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
  components/bounties/BountiesPage.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/NewBountyButton.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/Link.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/PageDialogGlobal.tsx
  components/common/PageDialog/hooks/usePageDialog.tsx
  components/common/PageDialog/index.tsx
  components/common/PageLayout/PageLayout.tsx
  components/profile/PublicProfile.tsx
  components/votes/components/NewProposalButton.tsx
  components/votes/components/VotesTable.tsx
  pages/[domain]/bounties/index.tsx
  pages/api/pages/[id]/archive.ts
Labels: work-in-progress, :rocket: deploy

#879 Show status for proposals in table
  __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
  charmClient/apis/proposalsApi.ts
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/VotesSidebar.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/proposals/ProposalsPage.tsx
  components/proposals/components/NoProposalsMessage.tsx
  components/proposals/components/ProposalActionsMenu.tsx
  components/proposals/components/ProposalStatusBadge.tsx
  components/proposals/components/ProposalsTable.tsx
  components/proposals/components/ProposalsViewOptions.tsx
  components/votes/VotesPage.tsx
  components/votes/components/NewProposalButton.tsx
  lib/proposal/__tests__/getProposalsBySpace.spec.ts
  lib/proposal/getProposalsBySpace.ts
  pages/[domain]/proposals/index.tsx
  pages/api/spaces/[id]/proposals.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#877 Automagic proposal page permissions
  __e2e__/publicPage.spec.ts
  __e2e__/utilities.ts
  __integration-tests__/server/pages/api/permissions/index.spec.ts
  charmClient/apis/proposalsApi.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/common/BoardEditor/focalboard/src/archiver.ts
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/gallery.test.tsx
  components/common/BoardEditor/focalboard/src/csvExporter.ts
  components/common/BoardEditor/focalboard/src/nativeApp.ts
  components/common/BoardEditor/focalboard/src/store/boards.ts
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/BoardEditor/focalboard/src/store/clientConfig.ts
  components/common/BoardEditor/focalboard/src/store/comments.ts
  components/common/BoardEditor/focalboard/src/store/globalError.ts
  components/common/BoardEditor/focalboard/src/store/globalTemplates.ts
  components/common/BoardEditor/focalboard/src/store/initialLoad.ts
  components/common/BoardEditor/focalboard/src/store/language.ts
  components/common/BoardEditor/focalboard/src/store/searchText.ts
  components/common/BoardEditor/focalboard/src/store/users.ts
  components/common/BoardEditor/focalboard/src/store/views.ts
  components/common/BoardEditor/focalboard/src/utils.test.ts
  components/common/BoardEditor/focalboard/src/utils.ts
  components/common/PageDialog/PageDialog.tsx
  components/common/PageLayout/components/Header/components/ShareButton/ShareButton.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx
  components/settings/roles/components/SpacePermissions/components/DefaultPagePermissions.tsx
  components/share/PublicPage.tsx
  hooks/usePages.tsx
  lib/pages/__tests__/findParentOfType.spec.ts
  lib/pages/findParentOfType.ts
  lib/pages/generateMarkdown.ts
  lib/pages/interfaces.ts
  lib/pages/utils.ts
  lib/permissions/pages/actions/__tests__/has-same-or-more-permissions.spec.ts
  lib/permissions/pages/actions/has-same-or-more-permissions.ts
  lib/permissions/pages/page-permission-interfaces.ts
  lib/permissions/pages/page-permission-mapping.ts
  lib/permissions/pages/triggers/lockToBountyCreator.ts
  lib/proposal/__tests__/getProposalsBySpace.spec.ts
  lib/proposal/__tests__/syncProposalPermissions.spec.ts
  lib/proposal/interface.ts
  lib/proposal/syncProposalPermissions.ts
  lib/proposal/updateProposal.ts
  lib/proposal/updateProposalStatus.ts
  pages/api/pages/index.ts
  pages/api/permissions/index.ts
  prisma/migrations/20220906190844_add_proposal_editor/migration.sql
  prisma/schema.prisma
  testing/setupDatabase.ts
Labels: :rocket: deploy

#905 Fix comment and vote options not visible on floating menu
  __integration-tests__/server/pages/api/threads/[id]/resolve.spec.ts
  __integration-tests__/server/pages/api/threads/index.spec.ts
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/PageDialog/PageDialog.tsx
  pages/api/threads/[id]/index.ts
  pages/api/threads/[id]/resolve.ts
  pages/api/threads/index.ts
Labels: :rocket: deploy

#913 turning off datadog agent using compose profile
  .ebextensions/00_env_vars.config
  docker-compose.yml
Labels: :rocket: deploy

#805 Feat/avatar popup
  .eslintignore
  components/_app/GlobalComponents.tsx
  components/common/Avatar.tsx
  components/common/Snackbar.tsx
  components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
  components/profile/components/NftAvatarGallery/NftAvatarGalleryPopup.tsx
  components/profile/components/NftAvatarGallery/NftGalleryItem.tsx
  components/profile/components/NftAvatarGallery/RenderEmptyAvatarGallery.tsx
  components/profile/components/NftAvatarGallery/index.ts
  components/profile/components/SetAvatarPopup/NftAvatarSection.tsx
  components/profile/components/SetAvatarPopup/SetAvatarPopup.tsx
  components/profile/components/SetAvatarPopup/index.ts
  components/profile/components/UserDetails/UserDetails.tsx
  components/profile/components/UserDetails/hooks/useUpdateProfileAvatar.ts
  components/profile/components/UserDetails/hooks/useUserDetails.ts
  components/settings/workspace/LargeAvatar.tsx
  hooks/useFilePicker.ts
  hooks/useS3UploadInput.ts
  hooks/useUser.tsx
  lib/users/createUser.ts
  lib/users/getDefaultAvatar.ts
  models/User.ts
  package-lock.json
  pages/_app.tsx
  pages/api/profile/avatar.ts
  pages/api/profile/index.ts
  yarn.lock
Labels: :rocket: deploy

#915 Build the image then deploy EBStalk using the image
  .cdk/bin/app.ts
  .dockerignore
  .ebextensions/00_env_vars.config
  .github/actions/build_docker_image/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  Dockerfile
  docker-compose.yml
  files_to_zip.txt
  package.json
Labels: :rocket: deploy

#914 Fix public bounty visibility
  __e2e__/publicBounties.spec.ts
  __e2e__/utilities.ts
  __integration-tests__/server/pages/api/pages/[id]/index.spec.ts
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/BountyApplicantForm.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySignupButton.tsx
  components/bounties/BountiesPage.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/BountyCard.tsx
  components/common/CharmEditor/components/nestedPage/nestedPage.utils.ts
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  hooks/usePages.tsx
  lib/bounties/__tests__/createBounty.spec.ts
  lib/bounties/__tests__/listAvailableBounties.spec.ts
  lib/bounties/createBounty.ts
  lib/bounties/getBounty.ts
  lib/bounties/listAvailableBounties.ts
  lib/pages/__tests__/findParentOfType.spec.ts
  lib/pages/interfaces.ts
  lib/pages/server/__tests__/resolvePageTree.spec.ts
  lib/pages/server/getAccessiblePages.ts
  lib/pages/server/resolvePageTree.ts
  lib/pages/utils.ts
  lib/permissions/pages/page-permission-interfaces.ts
  lib/proposal/syncProposalPermissions.ts
  lib/spaces/__tests__/togglePublicBounties.spec.ts
  lib/spaces/interfaces.ts
  lib/spaces/togglePublicBounties.ts
  models/Bounty.ts
  pages/api/pages/[id]/index.ts
  pages/api/spaces/index.ts
  testing/generate-stubs.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#930 Use username as default profile path
  lib/profile/isProfilePathAvailable.ts
  lib/users/createUser.ts
  pages/api/profile/checkPathAvailability.ts
Labels: :rocket: deploy

#951 Proposals template
  __integration-tests__/server/pages/api/pages/[id]/index.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
  __integration-tests__/server/pages/api/proposals/from-template.spec.ts
  __integration-tests__/server/pages/api/proposals/templates/[id].spec.ts
  __integration-tests__/server/pages/api/proposals/templates/index.spec.ts
  __integration-tests__/server/pages/api/votes/index.spec.ts
  charmClient/apis/proposalsApi.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/TemplatesMenu/TemplatePageMenuActions.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/TemplatesMenu/TemplatesMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/TemplatesMenu/index.ts
  components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx
  components/common/TemplatesMenu/TemplatePageMenuActions.tsx
  components/common/TemplatesMenu/TemplatesMenu.tsx
  components/common/TemplatesMenu/index.ts
  components/common/form/InputSearchReviewers.tsx
  components/votes/components/NewProposalButton.tsx
  lib/pages/server/__tests__/getAccessiblePages.spec.ts
  lib/pages/server/getAccessiblePages.ts
  lib/proposal/__tests__/createProposal.spec.ts
  lib/proposal/__tests__/getProposal.spec.ts
  lib/proposal/__tests__/getProposalsBySpace.spec.ts
  lib/proposal/createProposal.ts
  lib/proposal/getProposal.ts
  lib/proposal/getProposalsBySpace.ts
  lib/templates/__tests__/exportWorkspacePages.spec.ts
  lib/templates/proposals/__tests__/createProposalTemplate.spec.ts
  lib/templates/proposals/createProposalTemplate.ts
  pages/api/pages/[id]/index.ts
  pages/api/pages/index.ts
  pages/api/proposals/[id]/index.ts
  pages/api/proposals/from-template.ts
  pages/api/proposals/templates/[id].ts
  pages/api/proposals/templates/index.ts
  pages/api/votes/index.ts
Labels: :rocket: deploy

#946 Lasting proposals & marking proposals in nexus
  __e2e__/recordCustom.spec.ts
  __integration-tests__/permissions/07-reposition-downwards.todo.ts
  __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
  __integration-tests__/server/pages/api/proposals/from-template.spec.ts
  __integration-tests__/server/pages/api/votes/index.spec.ts
  charmClient/apis/proposalsApi.ts
  components/common/PageLayout/components/Sidebar/NotificationsBadge.tsx
  components/nexus/ProposalTasksList.tsx
  components/nexus/TasksPage.tsx
  lib/pages/modifyChildPages.ts
  lib/proposal/__tests__/createProposal.spec.ts
  lib/proposal/__tests__/createProposalFromTemplate.spec.ts
  lib/proposal/__tests__/getProposal.spec.ts
  lib/proposal/__tests__/getProposalTasks.spec.ts
  lib/proposal/__tests__/getProposalsBySpace.spec.ts
  lib/proposal/createProposal.ts
  lib/proposal/createProposalFromTemplate.ts
  lib/proposal/getProposalAction.ts
  lib/proposal/getProposalTasks.ts
  lib/proposal/getProposalTasksFromWorkspaceEvents.ts
  lib/templates/exports/test-00c57c23-25ac-4e14-8da5-daf7decc537b.json
  lib/templates/exports/test-152907ec-c30e-47b9-a6f9-53180a673552.json
  lib/templates/exports/test-1c691adb-e422-4ad3-8b23-3172bcfb1f7c.json
  lib/templates/exports/test-41903ae3-6159-4930-9161-57f003047a29.json
  lib/templates/exports/test-7786b68a-8d29-492e-ad41-85aecb2345c2.json
  pages/api/pages/index.ts
  pages/api/proposals/from-template.ts
  pages/api/tasks/list.ts
  prisma/migrations/20220921165020_usernotification_taskid/migration.sql
  prisma/schema.prisma
  scripts/makeAPIKey.ts
Labels: :rocket: deploy

#948 Adding healthcheck endpoint and also fixed datadog metric submission
  background/tasks/updateVotesStatus/task.ts
  docker-compose.yml
  files_to_zip.txt
  lib/metrics/metrics.ts
  pages/api/health/index.ts
Labels: :rocket: deploy

#975 Rationalise permissions
  __integration-tests__/server/pages/api/pages/index.spec.ts
  __integration-tests__/server/pages/api/proposals/from-template.spec.ts
  __integration-tests__/server/pages/api/votes/[id]/index.spec.ts
  __integration-tests__/server/pages/api/votes/index.spec.ts
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/votes/components/NewProposalButton.tsx
  lib/permissions/meta/__tests__/getTemplateExplanation.spec.ts
  lib/permissions/pages/available-page-permissions.class.ts
  lib/permissions/pages/page-permission-mapping.ts
  lib/permissions/spaces/mapping.ts
  lib/votes/__tests__/deleteVote.spec.ts
  lib/votes/__tests__/updateVote.spec.ts
  lib/votes/deleteVote.ts
  lib/votes/updateVote.ts
  pages/api/pages/index.ts
  pages/api/proposals/from-template.ts
  pages/api/votes/[id]/index.ts
  pages/api/votes/index.ts
  prisma/migrations/20220922184953_add_create_poll_operation/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#993 update prisma
  package-lock.json
  package.json
Labels: :rocket: deploy

#997 update to node 18
  .env.test.local
  .github/actions/build/action.yml
  .github/actions/install/action.yml
  Dockerfile
  scripts/configure-db.sh
Labels: :rocket: deploy

#999 remove node-fetch now that fetch is part of node.js
  adapters/http/fetch.server.ts
  adapters/http/fetch.ts
  lib/aws/uploadToS3Server.ts
  lib/blockchain/poaps.ts
  lib/profile/__tests__/getAggregatedData.spec.ts
  lib/templates/exports/test-1a4ac432-3dec-49d7-9cf3-e920a58d1aba.json
  lib/templates/exports/test-export.json
  next.base.js
  package-lock.json
  package.json
  scripts/testApi.ts
Labels: work-in-progress
