Repository charmverse/app.charmverse.io, pull requests merged in 2022-04, with the labels that each got.

#341 add cdk deploy
  .cdk/bin/app.ts
  .cdk/staging-stack.ts
  .ebextensions/01_filesystem.config
  .ebextensions/01_setup_swap.config
  .env.staging
  .github/actions/install/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/destroy_staging.yml
  .github/workflows/test_and_deploy.yml
  .gitignore
  cdk.json
  files_to_zip.txt
  lib/log/userEvents.ts
  lib/session/config.ts
  package-lock.json
  package.json
Labels: work-in-progress, :rocket: deploy

#353 Update next.js
  components/common/CharmEditor/components/EmojiSuggest/EmojiSuggest.tsx
  components/common/CharmEditor/components/Placeholder.tsx
  next.config.js
  package-lock.json
  package.json
Labels: :rocket: deploy

#346 Notion import v4
  .ebextensions/01_filesystem.config
  charmClient.ts
  components/common/BoardEditor/focalboard/src/blocks/board.ts
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
  components/common/BoardEditor/focalboard/src/components/sidebar/sidebarAddBoardMenu.tsx
  components/common/BoardEditor/focalboard/src/components/table/calculation/calculationRow.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/BoardEditor/focalboard/src/utils.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
  components/common/CharmEditor/components/ColumnBlock.tsx
  components/common/CharmEditor/components/NestedPage.tsx
  components/common/CharmEditor/components/ResizableIframe.tsx
  components/common/CharmEditor/components/ResizableImage.tsx
  components/common/PageLayout/components/PageNavigation.tsx
  components/settings/workspace/ImportNotionWorkspace.tsx
  lib/discord/assignRoles.ts
  lib/discord/createRoles.ts
  lib/embed/constants.ts
  lib/embed/extractEmbedLink.ts
  lib/focalboard/block.ts
  lib/focalboard/board.ts
  lib/focalboard/boardView.ts
  lib/focalboard/card.ts
  lib/focalboard/charmBlock.ts
  lib/focalboard/filterClause.ts
  lib/focalboard/filterGroup.ts
  lib/image/constants.ts
  lib/notion/importFromWorkspace.ts
  lib/notion/types.ts
  models/Page.ts
  package-lock.json
  package.json
  pages/[domain]/settings/workspace.tsx
  pages/api/discord/connect.ts
  pages/api/discord/importRoles.ts
  pages/api/notion/import.ts
  pages/api/notion/login.ts
  prisma/migrations/20220407141820_page_card/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#358 use DNS for staging environment
  .cdk/bin/app.ts
  .cdk/staging-stack.ts
  .github/actions/build/action.yml
  .github/workflows/deploy_staging.yml
  .gitignore
Labels: :rocket: deploy

#363 Update all the things
  components/[pageId]/BoardPage/BoardPage.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  components/bounties/MultiPaymentButton.tsx
  components/common/ActionsMenu.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.test.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumn.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumnHeader.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanHiddenColumnItem.tsx
  components/common/BoardEditor/focalboard/src/components/table/table.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableGroup.tsx
  components/common/BoardEditor/focalboard/src/hooks/sortable.tsx
  components/common/CharmEditor/components/CryptoPrice.tsx
  components/common/Loader.tsx
  components/common/PageLayout/components/PageNavigation.tsx
  components/common/Snackbar.tsx
  components/common/WorkspaceAvatar.tsx
  components/settings/payment-methods/components/DeletePaymentMethodModal.tsx
  components/settings/payment-methods/components/PaymentMethodList.tsx
  components/settings/roles/components/RoleForm.tsx
  components/settings/roles/hooks/useRoles.ts
  hooks/useEffecientDragLayer.ts
  lib/middleware/requireApiKey.ts
  next.config.js
  package-lock.json
  package.json
  pages/api/discord/oauth.ts
  pages/api/payment-methods/index.ts
  pages/api/session/logout.ts
  pages/join.tsx
Labels: :rocket: deploy

#369 add swap file to avoid memory issues on deploy
  .ebextensions/01_setup_swap.config
  .ebextensions/setup_swap.sh
Labels: :rocket: deploy

#376 Implement prosemirror tables from Skiff
  .github/actions/install/action.yml
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
  components/common/CharmEditor/components/NestedPage.tsx
  components/common/CharmEditor/components/table/index.ts
  components/common/CharmEditor/components/table/table.ts
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/NewPageMenu.tsx
  components/common/PageLayout/components/PageNavigation.tsx
  components/common/PageLayout/components/Sidebar.tsx
  context/darkMode.ts
  package-lock.json
  package.json
  pages/_app.tsx
  patches/@bangle.dev+base-components+0.28.8.patch
  patches/@bangle.dev+pm+0.28.8.patch
  patches/@bangle.dev+tooltip+0.28.8.patch
  patches/@skiff-org+prosemirror-tables+3.4.21.patch
  public/svgs/active-drag-handle-vertical.svg
  public/svgs/check_box.svg
  public/svgs/checked_check_box.svg
  public/svgs/close_icon.svg
  public/svgs/color_palette.svg
  public/svgs/down_arrow.svg
  public/svgs/drag-handle-vertical.svg
  public/svgs/filter.svg
  public/svgs/no_entry.svg
  public/svgs/right-arrow.svg
  public/svgs/sort_down_empty.svg
  public/svgs/sort_up_empty.svg
  public/svgs/sorted_down.svg
  public/svgs/sorted_up.svg
  public/svgs/table_header_toggle.svg
  public/svgs/trash_can.svg
  public/svgs/trash_can_black.svg
  public/svgs/types/checkbox_type.svg
  public/svgs/types/currency.svg
  public/svgs/types/date.svg
  public/svgs/types/label.svg
  public/svgs/types/number_type.svg
  public/svgs/types/text_type.svg
  public/svgs/up_arrow.svg
  theme/@bangle.dev/styles.scss
  theme/color-mode.ts
  theme/colors.ts
  theme/cssVariables.ts
  theme/darkMode.ts
  theme/index.ts
  theme/prosemirror-tables/prosemirror-tables.scss
Labels: :rocket: deploy

#375 more column ui updates
  components/common/CharmEditor/components/columnLayout/columnLayout.tsx
Labels: work-in-progress

#395 Refactoring notion import code and potential fix for missing pages
  lib/log/logLevel.plugin.ts
  lib/notion/importFromWorkspace.ts
  lib/notion/types.ts
  models/Page.ts
Labels: :rocket: deploy

#398 Optimize rendering of sidebar components
  components/common/BoardEditor/focalboard/src/components/sidebar/sidebarAddBoardMenu.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/Mention.tsx
  components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/PageLayout/components/NewPageMenu.tsx
  components/common/PageLayout/components/PageNavigation.tsx
  components/common/PageLayout/components/Sidebar.tsx
  hooks/usePages.tsx
  lib/pages/addPage.ts
  lib/pages/index.ts
Labels: :rocket: deploy

#399 clean up layout of view titles and enable toggling for public boards
  components/[pageId]/BoardPage/BoardPage.tsx
  components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.scss
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderActionsMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/common/BoardEditor/focalboard/src/components/viewMenu.tsx
  components/common/BoardEditor/focalboard/src/widgets/icons/calendar.tsx
  components/common/Button.tsx
  lib/pages/deleteNestedChild.ts
  pages/_app.tsx
  pages/api/blocks/[id]/index.ts
  pages/api/pages/[id]/index.ts
  theme/index.ts
Labels: :rocket: deploy

#413 Make entering a title in focalboard cards faster + make FB table view faster
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageBanner.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/[pageId]/DocumentPage/components/PageTitleInput.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/bounties/BountyModal.tsx
  components/common/BoardEditor/focalboard/src/components/calendar/fullCalendar.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.test.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.test.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.test.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.test.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.test.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  components/common/BoardEditor/focalboard/src/components/properties/link/link.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.test.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/table.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx
  components/common/BoardEditor/focalboard/src/store/comments.ts
  components/common/BoardEditor/focalboard/src/store/contents.ts
  package-lock.json
  package.json
  pages/_app.tsx
Labels: :rocket: deploy

#424 Disable settings for non-admin users
  components/common/CreateSpaceForm.tsx
  components/common/PageLayout/components/Sidebar.tsx
  components/settings/roles/RoleSettings.tsx
  components/settings/roles/components/RoleMemberRow.tsx
  components/settings/roles/components/RoleRow.tsx
  hooks/useIsAdmin.ts
  pages/[domain]/settings/contributors.tsx
  pages/[domain]/settings/token-gates.tsx
  pages/[domain]/settings/workspace.tsx
  seedData.ts
Labels: :rocket: deploy
