Repository charmverse/app.charmverse.io, pull requests merged in 2022-07, with the labels that each got.

#646 Pdf integration
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/NodeViewWrapper.tsx
  components/common/CharmEditor/components/FloatingMenu.tsx
  components/common/CharmEditor/components/ResizablePDF.tsx
  components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx
  components/common/PdfSelector/PdfSelector.tsx
  components/common/PdfSelector/index.tsx
  lib/image/constants.ts
  next.config.js
  package-lock.json
  package.json
Labels: :rocket: deploy

#661 redirect user to the first page that appears in the sidebar by default
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  pages/[domain]/index.tsx
Labels: :rocket: deploy

#670 only include favorites of pages not deleted
  lib/discord/loginByDiscord.ts
  lib/session/config.ts
  lib/users/createUser.ts
  lib/users/getUser.ts
  models/User.ts
  pages/api/profile/favorites.ts
  pages/api/profile/index.ts
  pages/api/session/login.ts
Labels: :rocket: deploy

#667 Page level voting
  components/[pageId]/DocumentPage/components/PageInlineVotesList.tsx
  components/common/CharmEditor/components/inlineVote/inlineVote.components.tsx
  components/common/PageLayout/components/CreateVoteModal.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/nexus/VoteTasksList.tsx
  hooks/useInlineVotes.tsx
Labels: :rocket: deploy

#677 Calculations of vote state in the backend before sending to front-end
  background/tasks/updateVotesStatus/updateVoteStatus.ts
  charmClient.ts
  components/[pageId]/DocumentPage/components/PageInlineVotesList.tsx
  components/common/CharmEditor/components/PageInlineVote.tsx
  hooks/useInlineVotes.tsx
  lib/votes/aggregateVoteResult.ts
  lib/votes/calculateVoteStatus.ts
  lib/votes/createVote.ts
  lib/votes/deleteVote.ts
  lib/votes/getVote.ts
  lib/votes/getVoteTasks.ts
  lib/votes/getVotesByPage.ts
  lib/votes/getVotesBySpace.ts
  lib/votes/interfaces.ts
  lib/votes/updateVotesStatus.ts
  pages/api/pages/[id]/votes.ts
  pages/api/votes/[id]/index.ts
  pages/api/votes/[id]/user-votes.ts
  pages/api/votes/index.ts
Labels: :rocket: deploy

#678 Workspace search
  components/common/PageLayout/components/SearchInWorkspaceModal.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/TrashModal.tsx
Labels: :rocket: deploy

#686 Check for view existence before updating ls
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
Labels: :rocket: deploy

#683 Search inside workspace improvements
  components/common/Modal/Modal.tsx
  components/common/PageLayout/components/SearchInWorkspaceModal.tsx
  package-lock.json
  package.json
Labels: :rocket: deploy

#688 Added notification counts on tasks tabs
  components/nexus/TasksPage.tsx
  components/nexus/components/NexusPageTitle.tsx
  components/nexus/hooks/useTasks.ts
  lib/mentions/getMentionedTasks.ts
Labels: work-in-progress, :rocket: deploy

#668 Public bounties
  __integration-tests__/server/pages/api/bounties/index.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/set-public-bounty-board.spec.ts
  charmClient.ts
  components/bounties/BountyList.tsx
  components/bounties/[bountyId]/components/BountyApplicantList.tsx
  components/bounties/components/BountyCard.tsx
  components/bounties/components/BountyEditorForm.tsx
  components/common/PageLayout/components/Account/Account.tsx
  components/common/PageLayout/components/Header/BountyShareButton/BountyShareButton.tsx
  components/common/PageLayout/components/Header/BountyShareButton/ShareBountyBoard.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/settings/roles/RoleSettings.tsx
  components/share/PublicBountyList.tsx
  components/share/PublicBountyTokenGateForm.tsx
  components/share/PublicPage.tsx
  hooks/useBounties.tsx
  hooks/useCurrentSpace.ts
  lib/bounties/__tests__/createBounty.spec.ts
  lib/bounties/__tests__/listAvailableBounties.spec.ts
  lib/bounties/__tests__/updateBountySettings.spec.ts
  lib/bounties/createBounty.ts
  lib/bounties/interfaces.ts
  lib/bounties/listAvailableBounties.ts
  lib/bounties/updateBountySettings.ts
  lib/permissions/bounties/computeBountyPermissions.ts
  lib/permissions/bounties/humaniseAccessConditions.ts
  lib/permissions/interfaces.ts
  lib/permissions/meta/__tests__/getTemplateExplanation.spec.ts
  lib/permissions/meta/__tests__/updateSpacePermissionConfigurationMode.spec.ts
  lib/permissions/meta/interfaces.ts
  lib/permissions/meta/preset-templates.ts
  lib/spaces/__tests__/togglePublicBounties.spec.ts
  lib/spaces/getSpacePublicInfo.ts
  lib/spaces/interfaces.ts
  lib/spaces/togglePublicBounties.ts
  pages/[domain]/bounties/[bountyId].tsx
  pages/[domain]/bounties/index.tsx
  pages/api/bounties/index.ts
  pages/api/spaces/[id]/set-permissions-mode.ts
  pages/api/spaces/[id]/set-public-bounty-board.ts
  prisma/migrations/20220705120718_add_space_public_bounty_remove_bounty_reviewer/migration.sql
  prisma/schema.prisma
  scripts/migrateBountyReviewers.ts
  seedData.ts
Labels: work-in-progress, :rocket: deploy

#705 Cast votes from proposal and nexus page
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageThreadsList.tsx
  components/[pageId]/DocumentPage/components/VotesSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/InlineActionCounter.tsx
  components/common/CharmEditor/components/inlineVote/components/InlineVoteList.tsx
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/nexus/VoteTasksList.tsx
  components/votes/components/Proposal/ProposalDialog.tsx
  components/votes/components/VotesTable.tsx
  hooks/usePageActionDisplay.tsx
  hooks/useVotes.tsx
  lib/votes/getVoteTasks.ts
  lib/votes/getVotesBySpace.ts
  lib/votes/interfaces.ts
Labels: :rocket: deploy

#695 Remember last visited workspace pages and non-workspace page
  components/common/RouteGuard.tsx
  lib/spaces/index.ts
  pages/[domain]/index.tsx
  pages/[domain]/settings/workspace.tsx
  pages/index.tsx
Labels: :rocket: deploy

#717 Mobile improvements: signup and navigation
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BaseLayout/components/Header.tsx
  components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx
  components/common/BoardEditor/focalboard/src/components/calendar/fullcalendar.scss
  components/common/BoardEditor/focalboard/src/components/centerPanel.scss
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.scss
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderActionsMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/common/BoardEditor/focalboard/src/styles/_typography.scss
  components/common/BoardEditor/focalboard/src/styles/main.scss
  components/common/BoardEditor/focalboard/src/widgets/buttons/button.scss
  components/common/CharmEditor/CharmEditor.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/NotificationsBadge/NotificationsBadge.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/common/PageLayout/components/PageContent.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/Workspaces.tsx
  components/signup/SignupForm.tsx
  package-lock.json
  pages/createWorkspace.tsx
  pages/join.tsx
  theme/focalboard/focalboard.button.scss
  theme/focalboard/focalboard.main.scss
Labels: :rocket: deploy

#721 Update to Prisma 4.1
  package-lock.json
  package.json
  pages/api/v1/databases/[id]/search.ts
  prisma/schema.prisma
Labels: :rocket: deploy

#713 More resilient permissions inheritance
  .vscode/settings.json
  __integration-tests__/permissions/00-create-root-page.spec.ts
  __integration-tests__/permissions/01-create-child-page.spec.ts
  __integration-tests__/permissions/09-board-permission-updated.spec.ts
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  lib/pages/__tests__/mapPageTree.spec.ts
  lib/pages/interfaces.ts
  lib/pages/mapPageTree.ts
  lib/pages/server/__tests__/resolvePageTree.spec.ts
  lib/pages/server/__tests__/resolvePageTree_v2.spec.ts
  lib/pages/server/resolvePageTree.ts
  lib/permissions/pages/actions/__tests__/delete-page-permission.spec.ts
  lib/permissions/pages/actions/__tests__/has-same-or-more-permissions.spec.ts
  lib/permissions/pages/actions/__tests__/replaceIllegalPermissions.spec.ts
  lib/permissions/pages/actions/__tests__/upsert-permission.spec.ts
  lib/permissions/pages/actions/check-parent-for-same-permission.ts
  lib/permissions/pages/actions/copyPermission.ts
  lib/permissions/pages/actions/delete-permission.ts
  lib/permissions/pages/actions/find-existing-permission-for-group.ts
  lib/permissions/pages/actions/has-same-or-more-permissions.ts
  lib/permissions/pages/actions/index.ts
  lib/permissions/pages/actions/replaceIllegalPermissions.ts
  lib/permissions/pages/actions/upsert-permission.ts
  lib/permissions/pages/page-permission-compute.ts
  lib/permissions/pages/triggers/__tests__/page-became-root.spec.ts
  lib/permissions/pages/triggers/board-page-permission-updated.ts
  lib/permissions/pages/triggers/page-created.ts
  lib/permissions/pages/triggers/page-permission-added.ts
  lib/permissions/pages/triggers/page-repositioned.ts
  lib/spaces/exportData/exportPages.ts
  pages/[domain]/index.tsx
  prisma/schema.prisma
  scripts/assignPublicPages.ts
  scripts/explorePagePermissions.ts
  scripts/inheritPagePermissions.ts
  scripts/publishBoardCards.ts
  testing/generate-stubs.ts
Labels: :rocket: deploy

#731 Next update to 12.2.3
  files_to_zip.txt
  next.base.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  testing/createJestConfig.ts
Labels: :rocket: deploy

#727 Open Bounty permissions branch
  .github/workflows/test_and_deploy.yml
  __integration-tests__/server/pages/api/bounties/[id]/index.spec.ts
  __integration-tests__/server/pages/api/bounties/index.spec.ts
  __integration-tests__/server/pages/api/bounties/pool.spec.ts
  charmClient.ts
  components/bounties/[bountyId]/components_v3/BountyHeader.tsx
  components/bounties/components/BountyEditorForm.tsx
  lib/bounties/__tests__/createBounty.spec.ts
  lib/bounties/__tests__/listAvailableBounties.spec.ts
  lib/bounties/closeOutBounty.ts
  lib/bounties/createBounty.ts
  lib/bounties/getBounty.ts
  lib/bounties/listAvailableBounties.ts
  lib/bounties/reviewBountySuggestion.ts
  lib/bounties/rollupBountyStatus.ts
  lib/bounties/updateBountySettings.ts
  lib/pages/server/getAccessiblePages.ts
  lib/permissions/bounties/__tests__/addBountyPermissionGroup.spec.ts
  lib/permissions/bounties/__tests__/computeBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/getGroupsWithOperations.spec.ts
  lib/permissions/bounties/__tests__/mapBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/queryBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/setBountyPermissions.spec.ts
  lib/permissions/bounties/addBountyPermissionGroup.ts
  lib/permissions/bounties/availableBountyPermissions.ts
  lib/permissions/bounties/computeBountyPermissions.ts
  lib/permissions/bounties/humaniseAccessConditions.ts
  lib/permissions/bounties/mapBountyPermissions.ts
  lib/permissions/bounties/mapping.ts
  lib/permissions/bounties/setBountyPermissions.ts
  models/Bounty.ts
  pages/api/bounties/[id]/index.ts
  pages/api/bounties/[id]/permissions.ts
  pages/api/bounties/[id]/review-suggestion.ts
  pages/api/bounties/index.ts
  pages/api/bounties/pool.ts
  prisma/migrations/20220725130530_drop_bounty_perms_view_edit/migration.sql
  prisma/schema.prisma
  testing/setupDatabase.ts
Labels: work-in-progress

#734 fix extra space on focalboard in mobile view
  components/common/BoardEditor/focalboard/src/components/gallery/gallery.scss
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.scss
  components/common/BoardEditor/focalboard/src/components/viewTitle.scss
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
Labels: :rocket: deploy

#712 Use decorations for inline comments
  __integration-tests__/server/pages/api/threads/[id]/resolve.spec.ts
  charmClient.ts
  components/[pageId]/DocumentPage/components/CommentsSidebar.tsx
  components/[pageId]/DocumentPage/components/VotesSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/FloatingMenu.tsx
  components/common/CharmEditor/components/InlineActionCounter.tsx
  components/common/CharmEditor/components/PageThread.tsx
  components/common/CharmEditor/components/Paragraph.tsx
  components/common/CharmEditor/components/callout/components/Callout.tsx
  components/common/CharmEditor/components/heading/Heading.tsx
  components/common/CharmEditor/components/heading/index.ts
  components/common/CharmEditor/components/inlineComment/InlineComment.components.tsx
  components/common/CharmEditor/components/inlineComment/components/InlineCommentRowDecoration.tsx
  components/common/CharmEditor/components/inlineComment/inlineComment.plugins.ts
  components/common/CharmEditor/components/inlineComment/inlineComment.plugins.tsx
  components/common/CharmEditor/components/inlineComment/inlineComment.specs.ts
  components/common/CharmEditor/components/inlineComment/inlineComment.utils.ts
  components/common/CharmEditor/components/inlineVote/components/InlineVoteList.tsx
  components/common/CharmEditor/components/inlineVote/components/InlineVoteRowDecoration.tsx
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/common/CharmEditor/components/inlineVote/inlineVote.plugins.ts
  components/common/CharmEditor/components/inlineVote/inlineVote.plugins.tsx
  hooks/useInlineComment.ts
  hooks/useThreads.tsx
  lib/browser.ts
  lib/inline-comments/findTotalInlineComments.ts
  lib/inline-comments/removeInlineCommentMark.ts
  lib/inline-votes/findTotalInlineVotes.ts
  lib/prosemirror/highlightMarkedElement.ts
  lib/threads/__tests__/toggleThreadStatus.spec.ts
  lib/threads/toggleThreadStatus.ts
  package-lock.json
  pages/api/threads/[id]/index.ts
  pages/api/threads/[id]/resolve.ts
  theme/@bangle.dev/styles.scss
  theme/styles.scss
Labels: :rocket: deploy

#733 hide comment and vote sidebars on mobile
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/CommentsSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/components/ScrollableWindow.tsx
  hooks/usePageActionDisplay.tsx
  lib/browser.ts
Labels: :rocket: deploy

#719 Create bounty page
  __integration-tests__/server/pages/api/bounties/[id]/index.spec.ts
  __integration-tests__/server/pages/api/bounties/index.spec.ts
  __integration-tests__/server/pages/api/bounties/pool.spec.ts
  __integration-tests__/server/pages/api/v1/bounties/index.spec.ts
  charmClient.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyIntegration.tsx
  components/bounties/BountyList.tsx
  components/bounties/[bountyId]/BountyDetails.tsx
  components/bounties/[bountyId]/components_v3/BountyDescription.tsx
  components/bounties/[bountyId]/components_v3/BountyHeader.tsx
  components/bounties/components/BountyCard.tsx
  components/bounties/components/BountyEditorForm.tsx
  components/bounties/components/BountyModal.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/PageLayout/components/SearchInWorkspaceModal.tsx
  lib/bounties/__tests__/createBounty.spec.ts
  lib/bounties/__tests__/listAvailableBounties.spec.ts
  lib/bounties/__tests__/updateBountySettings.spec.ts
  lib/bounties/closeOutBounty.ts
  lib/bounties/createBounty.ts
  lib/bounties/getBounty.ts
  lib/bounties/interfaces.ts
  lib/bounties/listAvailableBounties.ts
  lib/bounties/reviewBountySuggestion.ts
  lib/bounties/rollupBountyStatus.ts
  lib/bounties/shared.ts
  lib/bounties/updateBountySettings.ts
  lib/mentions/getMentionedTasks.ts
  lib/pages/server/getAccessiblePages.ts
  lib/permissions/bounties/__tests__/addBountyPermissionGroup.spec.ts
  lib/permissions/bounties/__tests__/computeBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/getGroupsWithOperations.spec.ts
  lib/permissions/bounties/__tests__/mapBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/queryBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/setBountyPermissions.spec.ts
  lib/permissions/bounties/addBountyPermissionGroup.ts
  lib/permissions/bounties/availableBountyPermissions.ts
  lib/permissions/bounties/computeBountyPermissions.ts
  lib/permissions/bounties/humaniseAccessConditions.ts
  lib/permissions/bounties/mapBountyPermissions.ts
  lib/permissions/bounties/mapping.ts
  lib/permissions/bounties/setBountyPermissions.ts
  models/Bounty.ts
  pages/api/bounties/[id]/index.ts
  pages/api/bounties/[id]/permissions.ts
  pages/api/bounties/[id]/review-suggestion.ts
  pages/api/bounties/index.ts
  pages/api/bounties/pool.ts
  pages/api/pages/[id]/index.ts
  pages/api/v1/bounties/index.ts
  prisma/migrations/20220720103417_bounty_page/migration.sql
  prisma/migrations/20220725130530_drop_bounty_perms_view_edit/migration.sql
  prisma/schema.prisma
  scripts/createBountyPages.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#737 Multi token gates
  adapters/litProtocol/hooks/useLitProtocol.tsx
  charmClient.ts
  components/common/TokenGateForm.tsx
  components/common/TokenGateForm/TokenGateForm.tsx
  components/common/TokenGateForm/TokenGateOption.tsx
  components/common/TokenGateForm/index.ts
  components/settings/roles/components/TokenGates/components/TokenGatesTable.tsx
  components/share/PublicBountyList.tsx
  components/share/PublicBountyTokenGateForm.tsx
  components/share/PublicPage.tsx
  hooks/useSpaces.tsx
  lib/token-gates/applyTokenGates.ts
  lib/token-gates/evaluateEligibility.ts
  lib/token-gates/interfaces.ts
  pages/api/token-gates/[id]/verify.ts
  pages/api/token-gates/evaluate.ts
  pages/api/token-gates/index.ts
  pages/api/token-gates/verify.ts
  pages/join.tsx
Labels: :rocket: deploy

#755 Add token gate to new bounty v3 UI
  components/[pageId]/DocumentPage/components/BountyProperties.tsx
  components/bounties/[bountyId]/components/BountyApplicantList.tsx
  components/bounties/[bountyId]/components_v3/BountyHeader.tsx
  components/bounties/[bountyId]/components_v3/BountySubmissions.tsx
  components/bounties/components/BountyApplicantForm/BountyApplicantForm.tsx
  components/bounties/components/BountyApplicantForm/components/ApplicationEditorForm.tsx
  components/bounties/components/BountyApplicantForm/components/BountySignupButton.tsx
  components/bounties/components/BountyApplicantForm/components/SubmissionEditorForm.tsx
  components/bounties/components/BountyApplicantForm/index.tsx
  components/bounties/components/BountyApplicationForm.tsx
  components/bounties/components/BountySubmissionsTable.tsx
  components/share/PublicBountiesPage.tsx
Labels: :rocket: deploy
