Repository charmverse/app.charmverse.io, pull requests merged in 2022-12, with the labels that each got.

#1294 Allow users to upload video via mux
  .ebextensions/00_env_vars.config
  charmClient/apis/muxApi.ts
  charmClient/charmClient.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/BlockAligner.tsx
  components/common/CharmEditor/components/ResizableImage.tsx
  components/common/CharmEditor/components/common/MediaSelectionPopup.tsx
  components/common/CharmEditor/components/common/MediaUrlInput.tsx
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/nodeView/nodeView.ts
  components/common/CharmEditor/components/tweet/TweetNodeView.tsx
  components/common/CharmEditor/components/video/VideoNodeView.tsx
  components/common/CharmEditor/components/video/VideoUploadForm.tsx
  components/common/CharmEditor/components/video/videoSpec.ts
  components/common/ImageSelector/ImageSelector.tsx
  hooks/useOnScreen.ts
  lib/middleware/onError.ts
  lib/mux/createUpload.ts
  lib/mux/getAsset.ts
  lib/mux/getSignedToken.ts
  lib/mux/getUpload.ts
  lib/mux/muxClient.ts
  package-lock.json
  package.json
  pages/api/mux/asset/[id].ts
  pages/api/mux/upload.ts
  pages/api/mux/upload/[id].ts
Labels: :rocket: deploy

#1299 Airtable support
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/BlockAligner.tsx
  components/common/CharmEditor/components/common/MediaSelectionPopup.tsx
  components/common/CharmEditor/components/fiduswriter/fiduseditor.ts
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/iframe/config.tsx
  components/common/CharmEditor/components/iframe/iframe.ts
  components/common/CharmEditor/components/iframe/iframeSpec.ts
  components/common/CharmEditor/components/iframe/index.ts
  components/common/CharmEditor/components/iframe/utils.ts
  components/common/CharmEditor/components/tweet/TweetNodeView.tsx
  components/common/CharmEditor/components/video/VideoNodeView.tsx
  components/common/CharmEditor/components/video/videoSpec.ts
  components/common/CharmEditor/utils.ts
  lib/websockets/documentEvents/documentEvents.ts
Labels: :rocket: deploy

#1306 Public env vars
  .github/actions/build/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
Labels: :rocket: deploy

#1310 Fix broken e2e test
  __e2e__/joinWorkspace/privateLink.test.ts
  components/common/RouteGuard.tsx
  next.base.js
  pages/signup.tsx
Labels: :rocket: deploy

#1307 add slash command for Dune embeds
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/iframe/components/EmbedIcon.tsx
  components/common/CharmEditor/components/iframe/config.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
  public/images/cryptoLogos/duno_logo_color.png
  public/images/dune_logo_bw.png
Labels: :rocket: deploy

#1318 Update prosemirror to latest version
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/base-components/code-block.ts
  components/common/CharmEditor/components/@bangle.dev/react-menu/MenuButtons.tsx
  components/common/CharmEditor/components/@bangle.dev/react-menu/floating-menu.ts
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/node-view-helpers.tsx
  components/common/CharmEditor/components/@bangle.dev/tooltip/suggest-tooltip.ts
  components/common/CharmEditor/components/@bangle.dev/tooltip/trigger-input-rule.ts
  components/common/CharmEditor/components/bulletList.ts
  components/common/CharmEditor/components/columnLayout/columnLayout.tsx
  components/common/CharmEditor/components/disclosure/disclosure.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/schema.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/tools.ts
  components/common/CharmEditor/components/fiduswriter/fiduseditor.ts
  components/common/CharmEditor/components/fiduswriter/state_plugins/collab_carets.ts
  components/common/CharmEditor/components/fiduswriter/state_plugins/track/plugin.ts
  components/common/CharmEditor/components/fiduswriter/track/delete.ts
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/CharmEditor/components/floatingMenu/floatingMenu.plugins.ts
  components/common/CharmEditor/components/horizontalRule.ts
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx
  components/common/CharmEditor/components/inlinePalette/hooks.ts
  components/common/CharmEditor/components/inlinePalette/inlinePalette.ts
  components/common/CharmEditor/components/inlinePalette/paletteItem.ts
  components/common/CharmEditor/components/inlineVote/components/InlineVoteSubmenu.tsx
  components/common/CharmEditor/components/listItem/commands.ts
  components/common/CharmEditor/components/mention/components/MentionSuggest.tsx
  components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/CharmEditor/components/quote/quote.ts
  components/common/CharmEditor/utils.ts
  lib/pages/server/convertJsonPagesToPrisma.ts
  lib/pages/server/duplicatePage.ts
  lib/prosemirror/hasComponentInSchema.ts
  lib/prosemirror/interfaces.ts
  next.base.js
  next.config.js
  package-lock.json
  package.json
  pages/api/pages/index.ts
  patches/@bangle.dev+base-components+0.28.8.patch
  patches/@bangle.dev+base-components+0.31.6.patch
  patches/@bangle.dev+pm+0.28.8.patch
  patches/@bangle.dev+pm+0.31.6.patch
  patches/@bangle.dev+tooltip+0.28.8.patch
  patches/@bangle.dev+utils+0.31.6.patch
Labels: work-in-progress, :rocket: deploy

#1322 fix autofill color on safari
  theme/styles.scss
Labels: :rocket: deploy

#1330 support Loom embeds
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/iframe/config.tsx
  components/common/CharmEditor/components/iframe/utils.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
Labels: :rocket: deploy

#1328 Integrate forum API with UI
  charmClient/apis/forumApi.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/[pageId]/DocumentPage/components/PostProperties/PostProperties.tsx
  components/[pageId]/DocumentPage/components/PostProperties/components/PostCategoriesInput.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/PageActions.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PostDialog/PostDialog.tsx
  components/common/PostDialog/PostDialogGlobal.tsx
  components/common/PostDialog/hooks/usePostDialog.tsx
  components/common/PostDialog/index.tsx
  components/forum/ForumPage.tsx
  components/forum/components/CreateForumPost/CreateForumPost.tsx
  components/forum/components/ForumPost/ForumPost.tsx
  components/forum/components/ForumPost/PostVote.tsx
  components/forum/components/ForumPosts/ForumPosts.tsx
  components/share/PublicPage.tsx
  lib/forums/posts/__tests__/getForumPost.spec.ts
  lib/forums/posts/__tests__/listForumPosts.spec.ts
  lib/forums/posts/__tests__/updateForumPost.spec.ts
  lib/forums/posts/checkPostAccess.ts
  lib/forums/posts/createForumPost.ts
  lib/forums/posts/deleteForumPost.ts
  lib/forums/posts/getForumPost.ts
  lib/forums/posts/interfaces.ts
  lib/forums/posts/listForumPosts.ts
  lib/forums/posts/publishForumPost.ts
  lib/forums/posts/updateForumPost.ts
  lib/forums/posts/voteForumPost.ts
  lib/pages/addPage.ts
  pages/[domain]/forum/index.tsx
  pages/api/forums/posts/[pageId]/comments/[commentId].ts
  pages/api/forums/posts/[pageId]/comments/index.ts
  pages/api/forums/posts/[pageId]/index.ts
  pages/api/forums/posts/[pageId]/publish.ts
  pages/api/forums/posts/[pageId]/vote.ts
  pages/api/forums/posts/[postId]/index.ts
  pages/api/forums/posts/index.ts
  pages/api/pages/[id]/index.ts
  pages/api/spaces/[id]/post-categories/[postCategoryId]/index.ts
  testing/forums.ts
Labels: :rocket: deploy

#1333 set galleryimage and has content when editing a page thru websockets
  lib/pages/__tests__/getPreviewImageFromContent.spec.ts
  lib/pages/server/updatePage.ts
  lib/websockets/documentEvents/documentEvents.ts
  pages/api/pages/[id]/index.ts
  pages/api/pages/index.ts
Labels: :rocket: deploy

#1349 handle payload size errors in web sockets
  background/websockets.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/fiduswriter/collab/doc.ts
  components/common/CharmEditor/components/fiduswriter/fiduseditor.ts
  components/common/CharmEditor/components/fiduswriter/ws.ts
  components/common/CharmEditor/components/pasteChecker/pasteChecker.ts
  package.json
Labels: :rocket: deploy

#1351 Fix floating menu in comments
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
Labels: :rocket: deploy

#1352 Palette key for CharmEditor
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx
  components/common/CharmEditor/components/inlinePalette/config.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/advancedBlocks.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/media.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx
  components/common/CharmEditor/components/inlinePalette/hooks.ts
  components/common/CharmEditor/components/inlinePalette/inlinePalette.ts
  components/common/CharmEditor/components/inlinePalette/paletteItem.ts
Labels: :rocket: deploy

#1357 sanitize inputs for mentions
  components/common/CharmEditor/components/mention/components/MentionSuggest.tsx
  lib/utilities/__tests__/strings.spec.ts
  lib/utilities/strings.ts
Labels: :rocket: deploy

#1363 add embed support for google forms
  components/common/CharmEditor/components/iframe/__tests__/utils.spec.ts
  components/common/CharmEditor/components/iframe/config.ts
  components/common/CharmEditor/components/iframe/iframe.ts
  components/common/CharmEditor/components/iframe/utils.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
Labels: :rocket: deploy

#1358 update post dialog
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/[pageId]/DocumentPage/components/PostProperties/PostProperties.tsx
  components/[pageId]/DocumentPage/components/PostProperties/index.ts
  components/common/PageDialog/PageDialog.tsx
  components/common/PostDialog/PostDialog.tsx
  components/forum/ForumPage.tsx
  components/forum/components/CategoryMenu.tsx
  components/forum/components/CategoryPopup.tsx
  components/forum/components/CategorySelect.tsx
  components/forum/components/CreateForumPost.tsx
  components/forum/components/CreateForumPost/index.ts
  components/forum/components/ForumPost/PostVote.tsx
  components/forum/components/ForumPost/index.ts
  components/forum/components/ForumPostSkeleton/index.ts
  components/forum/components/ForumPosts/index.ts
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostDialog/PostDialogGlobal.tsx
  components/forum/components/PostDialog/hooks/usePostDialog.tsx
  components/forum/components/PostDialog/index.tsx
  components/forum/components/PostList/PostList.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostList/components/PostSkeleton.tsx
  components/forum/components/PostList/components/PostVote.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/PostCategoryInput.tsx
  pages/[domain]/forum/index.tsx
  scripts/query.ts
Labels: work-in-progress

#1331 Login with google
  .ebextensions/00_env_vars.config
  .github/actions/build/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  __e2e__/po/login.po.ts
  __e2e__/sessions/login.spec.ts
  __e2e__/sessions/loginDiscord.spec.ts
  __e2e__/sessions/logout.spec.ts
  __e2e__/sessions/signup.spec.ts
  __integration-tests__/server/pages/api/profile/profile.spec.ts
  charmClient/apis/profileApi.ts
  components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/index.ts
  components/common/Avatar.tsx
  components/login/Login.tsx
  components/login/LoginPageContent.tsx
  components/login/WalletSign.tsx
  components/login/hooks/useGoogleAuth.tsx
  components/profile/components/IdentityModal.tsx
  components/profile/components/UserDetails/UserDetails.tsx
  config/constants.ts
  connectors.ts
  hooks/useWeb3AuthSig.tsx
  lib/blockchain/unstoppableDomains/client.ts
  lib/blockchain/unstoppableDomains/index.ts
  lib/blockchain/unstoppableDomains/interfaces.ts
  lib/blockchain/unstoppableDomains/server.ts
  lib/google/loginWithGoogle.ts
  lib/middleware/saveSession.ts
  lib/session/config.ts
  lib/users/__tests__/updateUserProfile.spec.ts
  lib/users/updateUserProfile.ts
  models/User.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/google/login.ts
  pages/api/profile/index.ts
  pages/index.tsx
  prisma/migrations/20221208210740_unique_user_email_field/migration.sql
  prisma/migrations/20221213220739_add_google_model/migration.sql
  prisma/schema.prisma
  public/images/walletLogos/Google_G.png
  scripts/updateMixpanelProfiles.ts
Labels: :rocket: deploy

#1362 Refactor notion import code & fix known issues
  .vscode/launch.json
  components/common/PageActions.tsx
  components/common/PageLayout/components/Header/Header.tsx
  lib/notion/NotionImporter/CharmverseDatabasePage.ts
  lib/notion/NotionImporter/CharmversePage.ts
  lib/notion/NotionImporter/NotionBlock.ts
  lib/notion/NotionImporter/NotionCache.ts
  lib/notion/NotionImporter/NotionImporter.ts
  lib/notion/NotionImporter/NotionPage.ts
  lib/notion/__tests__/NotionImport.spec.ts
  lib/notion/convertPropertyType.ts
  lib/notion/convertRichText.ts
  lib/notion/convertToPlainText.ts
  lib/notion/createPrismaPage.ts
  lib/notion/getPageTitle.ts
  lib/notion/getPersistentImageUrl.ts
  lib/notion/importFromWorkspace.ts
  lib/notion/types.ts
  package-lock.json
  package.json
  pages/api/notion/import.ts
Labels: :rocket: deploy

#1385 Forum post comments
  __integration-tests__/server/pages/api/forums/posts/[postId]/index.spec.ts
  charmClient/apis/forumApi.ts
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/CharmEditor/components/PageThread.tsx
  components/forum/components/ForumVote.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/CommentReplyForm.tsx
  components/forum/components/PostPage/components/PostComment.tsx
  components/forum/components/PostPage/components/PostCommentForm.tsx
  components/forum/components/PostPage/components/PostCommentSort.tsx
  lib/forums/comments/createPostComment.ts
  lib/forums/comments/deletePostComment.ts
  lib/forums/comments/getPostComments.ts
  lib/forums/comments/interface.ts
  lib/forums/comments/updatePostComment.ts
  lib/forums/posts/__tests__/voteForumPost.spec.ts
  lib/forums/posts/getPostMeta.ts
  lib/forums/posts/getPostVote.ts
  lib/forums/posts/interfaces.ts
  lib/forums/posts/listForumPosts.ts
  lib/forums/posts/searchForumPosts.ts
  lib/forums/posts/voteForumComment.ts
  lib/forums/posts/voteForumPost.ts
  pages/api/forums/posts/[pageId]/comments/[commentId]/index.ts
  pages/api/forums/posts/[pageId]/comments/[commentId]/vote.ts
  prisma/migrations/20221221152601_page_comment_user/migration.sql
  prisma/migrations/20221223123735_commente_deleted_at/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1393 Autoverify wallet
  components/login/Login.tsx
  components/login/WalletSign.tsx
Labels: :rocket: deploy

#1394 Changes to Polls (Embedded Polls)
  components/[pageId]/DocumentPage/components/PageActionToggle.tsx
  components/[pageId]/DocumentPage/components/VotesSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/SidebarDrawer.tsx
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/CharmEditor/components/floatingMenu/MenuButtons.tsx
  components/common/CharmEditor/components/floatingMenu/floating-menu.ts
  components/common/CharmEditor/components/floatingMenu/floatingMenu.plugins.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/advancedBlocks.tsx
  components/common/CharmEditor/components/inlineVote/components/InlineVoteList.tsx
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/common/CharmEditor/components/inlineVote/inlineVote.plugins.tsx
  components/common/CharmEditor/components/poll/PollComponent.tsx
  components/common/CharmEditor/components/poll/index.ts
  components/common/CharmEditor/components/poll/pollPlugin.ts
  components/common/CharmEditor/components/poll/pollSpec.ts
  components/common/CharmEditor/components/suggestions/SuggestionCard.tsx
  components/common/CharmEditor/specRegistry.ts
  components/common/PageLayout/components/Header/Header.tsx
  hooks/usePageActionDisplay.tsx
  lib/prosemirror/checkIsContentEmpty.ts
  scripts/deleteVotes.ts
Labels: :rocket: deploy

#1397 Change view title when changing layout
  components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/common/CharmEditor/components/inlineDatabase/components/ViewSelection.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  lib/focalboard/boardView.ts
  lib/notion/NotionImporter/CharmverseDatabasePage.ts
  lib/pages/addPage.ts
Labels: :rocket: deploy

#1400 Full page view for forum post modal
  components/common/BoardEditor/focalboard/src/components/dialog.scss
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/forum/components/PostDialog/PostDialog.tsx
Labels: :rocket: deploy

#1406 fix auto adjustment of height for embeds
  components/common/CharmEditor/components/Resizable/HorizontalResizer.tsx
Labels: :rocket: deploy

#1408 Import markdown
  charmClient/apis/fileApi.ts
  charmClient/charmClient.ts
  components/common/CharmEditor/components/markdownParser/ImportZippedMarkdown.tsx
  components/common/CharmEditor/components/markdownParser/files/The Singularity.ts
  components/common/CharmEditor/components/markdownParser/files/index.ts
  components/common/CharmEditor/components/markdownParser/incrementalNote.ts
  components/common/CharmEditor/components/markdownParser/parseMarkdown.ts
  components/common/PageLayout/components/NewPageMenu.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/settings/workspace/ImportNotionWorkspace.tsx
  hooks/useFilePicker.ts
  package-lock.json
  package.json
  pages/api/pages/import/[spaceId]/zipped.ts
Labels: :rocket: deploy
