Repository charmverse/app.charmverse.io, pull requests merged in 2022-08, with the labels that each got.

#760 Fix select multiple lines
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/base-components/code-block.ts
  components/common/CharmEditor/components/@bangle.dev/base-components/image.ts
  components/common/CharmEditor/components/ResizableImage.tsx
  components/common/CharmEditor/components/ResizablePDF.tsx
  components/common/CharmEditor/components/columnLayout/columnLayout.tsx
  components/common/CharmEditor/components/emojiSuggest/emojiSuggest.specs.ts
  components/common/CharmEditor/components/iframe/IframeComponent.tsx
  components/common/CharmEditor/components/iframe/iframe.ts
  components/common/CharmEditor/components/mention/mention.specs.ts
  components/common/CharmEditor/components/nestedPage/nestedPage.specs.ts
  components/common/CharmEditor/components/paragraph/index.ts
  components/common/CharmEditor/components/quote/quote.ts
  lib/browser.ts
  theme/@bangle.dev/styles.scss
  theme/cssVariables.ts
Labels: :rocket: deploy

#690 Add global teardown
  jest.config.ts
  testing/wipeTestData.ts
Labels: work-in-progress

#757 Bounty actions inside card options menu
  .vscode/settings.json
  __integration-tests__/server/pages/api/bounties/[id]/index.spec.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyIntegration.tsx
  components/[pageId]/DocumentPage/components/BountyProperties.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/bounties/BountiesPage.tsx
  components/bounties/[bountyId]/BountyDetails.tsx
  components/bounties/[bountyId]/components/BountyApplicantList.tsx
  components/bounties/[bountyId]/components/BountyApplyButton.tsx
  components/bounties/[bountyId]/components_v3/BountyDescription.tsx
  components/bounties/[bountyId]/components_v3/BountyHeader.tsx
  components/bounties/[bountyId]/components_v3/BountySubmissions.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/BountyApplicantForm/components/SubmissionEditorForm.tsx
  components/bounties/components/BountyDelete.tsx
  components/bounties/components/BountyHeader.tsx
  components/bounties/components/BountyPaymentButton.tsx
  components/bounties/components/BountyReviewers.tsx
  components/bounties/components/BountySubmissionReviewActions.tsx
  components/bounties/components/BountySubmissionsTable.tsx
  components/bounties/components/BountySuggestionApproval.tsx
  components/bounties/components/NewBountyButton.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/common/Page/PageDialog.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PopperPopup.tsx
  hooks/useBounties.tsx
  hooks/usePages.tsx
  lib/bounties/createBounty.ts
  lib/pages/modifyChildPages.ts
  pages/[domain]/bounties/[bountyId].tsx
  pages/[domain]/bounties/index.tsx
  pages/api/bounties/[id]/index.ts
Labels: :rocket: deploy

#765 Inline proposal votes
  .vscode/settings.json
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/VotesSidebar.tsx
  components/nexus/VoteTasksList.tsx
  components/votes/VotesPage.tsx
  components/votes/components/CreateVoteModal.tsx
  components/votes/components/VoteIcon.tsx
  components/votes/components/VotesTable.tsx
  hooks/usePageActionDisplay.tsx
  lib/votes/__tests__/createVote.spec.ts
  lib/votes/createVote.ts
  prisma/migrations/20220803162559_add_vote_context/migration.sql
  prisma/schema.prisma
  scripts/setupVotesContext.ts
Labels: :rocket: deploy

#762 Lazy-load the CharmEditor
  charmClient.ts
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/bounties/[bountyId]/components_v3/BountyDescription.tsx
  components/bounties/components/BountyEditorForm.tsx
  components/common/BoardEditor/charmClient.interface.ts
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/PDFViewer.tsx
  components/common/CharmEditor/components/ResizablePDF.tsx
  components/common/CharmEditor/specRegistry.ts
  components/common/IntlProvider.tsx
  components/common/Page/PageDialog.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/components/Header/components/Snapshot/PublishingForm.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/votes/components/CreateVoteModal.tsx
  hooks/useBounties.tsx
  lib/pages/generateMarkdown.ts
  pages/_app.tsx
Labels: :rocket: deploy

#768 Use CharmEditor for comments
  adapters/http/fetch.server.ts
  adapters/http/fetch.ts
  adapters/http/index.ts
  components/[pageId]/BoardPage/BoardPage.tsx
  components/common/Avatar.tsx
  components/common/BoardEditor/focalboard/src/blocks/commentBlock.ts
  components/common/BoardEditor/focalboard/src/components/__snapshots__/markdownEditor.test.tsx.snap
  components/common/BoardEditor/focalboard/src/components/cardDetail/comment.test.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/comment.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.test.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.test.tsx
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/block-types/codeBlockStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/block-types/headingBlockStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/boldStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/headingDelimiterStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/inlineCodeStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/italicStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/olDelimiterStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/quoteStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/strikethroughStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/inline-styles/ulDelimiterStyleStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/liveMarkdownPlugin.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/pluginStrategy.ts
  components/common/BoardEditor/focalboard/src/components/live-markdown-plugin/utils/findRangesWithRegex.ts
  components/common/BoardEditor/focalboard/src/components/markdownEditor.scss
  components/common/BoardEditor/focalboard/src/components/markdownEditor.test.tsx
  components/common/BoardEditor/focalboard/src/components/markdownEditor.tsx
  components/common/BoardEditor/focalboard/src/components/markdownEditorInput/entryComponent/entryComponent.scss
  components/common/BoardEditor/focalboard/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
  components/common/BoardEditor/focalboard/src/components/markdownEditorInput/markdownEditorInput.scss
  components/common/BoardEditor/focalboard/src/components/markdownEditorInput/markdownEditorInput.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderActionsMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.test.tsx
  components/common/BoardEditor/focalboard/src/store/users.ts
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/CharmEditor/components/PopoverMenu.tsx
  components/common/CharmEditor/components/mention/components/MentionSuggest.tsx
  components/common/form/InputSearchContributor.tsx
  components/common/form/InputSearchReviewers.tsx
  lib/crypto-price/dataSources/coinMarketCap.ts
  lib/crypto-price/dataSources/cryptoCompare.ts
  package-lock.json
  package.json
  pages/_app.tsx
  theme/focalboard/focalboard.main.scss
Labels: :rocket: deploy

#785 Organize bounty code according to heierarchal components and remove old code
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/BountyApplicantForm.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/ApplicationEditorForm.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/BountySignupButton.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/BountySubmissionStatus.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/SubmissionEditorForm.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/index.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantActions.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantTableRow.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantsTable.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/index.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyReviewers.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySlots.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySuggestionApproval.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/index.tsx
  components/bounties/[bountyId]/components_v3/BountyDescription.tsx
  components/bounties/components/BountyEditorForm.tsx
  components/bounties/components/BountyModal.tsx
  components/bounties/components/BountySubmissionContent.tsx
  components/bounties/components/InputBountyStatus.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  tsconfig.json
Labels: :rocket: deploy

#789 Confirm card conversion to bounty
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/Page/PageDialog.tsx
  components/common/form/InputSearchBlockchain.tsx
  hooks/useBounties.tsx
Labels: :rocket: deploy

#790 update lit protocol
  components/settings/roles/components/TokenGates/TokenGates.tsx
  package-lock.json
  package.json
Labels: :rocket: deploy

#788 Simplify submissions UI for bounties
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/BountyApplicantForm.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/ApplicationInput.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/BountySubmissionStatus.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/SubmissionInput.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantStatus.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantActions.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantTableRow.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantsTable.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyPropertiesHeader.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyReviewers.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySlots.tsx
  components/[pageId]/DocumentPage/components/PageTitleInput.tsx
  components/bounties/BountiesPage.tsx
  components/bounties/components/BountiesEmptyState.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.scss
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/BoardEditor/focalboard/src/theme.ts
  components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
  components/common/Page/PageDialog.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/UserDisplay.tsx
  components/common/form/InputSearchBlockchain.tsx
  components/settings/contributors/InviteLinks/InviteLinks.tsx
  hooks/useBounties.tsx
  theme/colors.ts
  theme/index.ts
Labels: :rocket: deploy

#807 Show single comment count for multi line paragraphs
  components/common/CharmEditor/components/inlineComment/inlineComment.plugins.tsx
Labels: :rocket: deploy

#813 Auto-upload the embedded image
  components/common/CharmEditor/components/ResizableImage.tsx
Labels: :rocket: deploy

#824 fix share button not appearing on database pages
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/BountyShareButton/BountyShareButton.tsx
  components/common/PageLayout/components/Header/components/BountyShareButton/ShareBountyBoard.tsx
  components/common/PageLayout/components/Header/components/ShareButton/ShareButton.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/AddPagePermissionsForm.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/index.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx
  components/common/PageLayout/components/Header/components/ShareButton/index.tsx
  components/settings/roles/RoleSettings.tsx
  components/share/PublicPage.tsx
Labels: :rocket: deploy

#823 update lit modal
  components/settings/contributors/InviteLinks/InviteLinks.tsx
  components/settings/contributors/InviteLinks/InviteLinksTable.tsx
  components/settings/roles/RoleSettings.tsx
  components/settings/roles/components/RoleRow.tsx
  components/settings/roles/components/TokenGates/components/TokenGateRolesSelect.tsx
  components/settings/roles/components/TokenGates/components/TokenGatesTable.tsx
  package-lock.json
  package.json
Labels: :rocket: deploy

#815 Server tree error
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  pages/api/pages/[id]/index.ts
Labels: :rocket: deploy

#830 upgrade prisma to support db tracing
  package-lock.json
  package.json
Labels: :rocket: deploy

#834 bring back top-left icon for Nexus
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/NotificationsBadge/NotificationsBadge.tsx
  components/common/PageLayout/components/Header/components/NotificationsBadge/index.tsx
  components/common/PageLayout/components/Sidebar/NexusAvatar.tsx
  components/common/PageLayout/components/Sidebar/NotificationsBadge.tsx
  components/common/PageLayout/components/Sidebar/Workspaces.tsx
Labels: :rocket: deploy

#828 Inline database views
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/common/BoardEditor/focalboard/src/blocks/boardView.ts
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/CharmEditor/components/PageList.tsx
  components/common/CharmEditor/components/inlineDatabase/components/BoardSelection.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/CharmEditor/components/inlineDatabase/inlineDatabase.ts
  components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  components/share/PublicPage.tsx
  lib/pages/addPage.ts
  prisma/migrations/20220824160656_inline_linked_board/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#839 Tt3 deploy docker compose
  .ebextensions/00_env_vars.config
  .ebextensions/99_datadog.config
  .ebextensions_cron/00_env_vars.config
  .ebextensions_cron/99_datadog.config
  .env.staging
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  Dockerfile
  Dockerrun.aws.json
  docker-compose-cron.yml
  docker-compose.yml
  files_to_zip.txt
  package.json
Labels: :rocket: deploy

#844 Display inline database in public pages
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/focalboard/src/components/SourceSelection.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/common/BoardEditor/focalboard/src/store/boards.ts
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  components/share/PublicPage.tsx
  lib/pages/addPage.ts
  lib/pages/interfaces.ts
  lib/pages/mapPageTree.ts
  pages/api/pages/[id]/archive.ts
  pages/api/permissions/index.ts
  pages/api/public/pages/[...pageId]/index.ts
Labels: work-in-progress, :rocket: deploy

#849 Adding dao api and others
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .github/workflows/test_and_deploy.yml
  docker-compose-cron.yml
Labels: :rocket: deploy

#858 Changing ElasticBeanstalk environment names
  .cdk/staging-stack.ts
  .github/workflows/test_and_deploy.yml
Labels: :rocket: deploy
