Repository charmverse/app.charmverse.io, pull requests merged in 2022-10, with the labels that each got.

#1021 Add signatures for wallet ID
  .env.test.local
  .github/workflows/test_and_deploy.yml
  __e2e__/publicPage.spec.ts
  __e2e__/utils.ts
  __integration-tests__/permissions/00-create-root-page.spec.ts
  __integration-tests__/permissions/01-create-child-page.spec.ts
  __integration-tests__/permissions/02-update-existing-permission.spec.ts
  __integration-tests__/permissions/03-delete-permission.spec.ts
  __integration-tests__/permissions/04-add-page-permission.spec.ts
  __integration-tests__/permissions/05-reposition-to-root.spec.ts
  __integration-tests__/permissions/06-reposition-upwards.spec.ts
  __integration-tests__/permissions/08-reposition-different-tree.spec.ts
  __integration-tests__/permissions/09-board-permission-updated.spec.ts
  __integration-tests__/server/pages/api/applications/[id]/index.spec.ts
  __integration-tests__/server/pages/api/applications/index.spec.ts
  __integration-tests__/server/pages/api/bounties/[id]/close.spec.ts
  __integration-tests__/server/pages/api/bounties/[id]/lock.spec.ts
  __integration-tests__/server/pages/api/bounties/[id]/permissions.spec.ts
  __integration-tests__/server/pages/api/bounties/[id]/review-suggestions.spec.ts
  __integration-tests__/server/pages/api/bounties/index.spec.ts
  __integration-tests__/server/pages/api/comments/[id]/index.spec.ts
  __integration-tests__/server/pages/api/comments/index.spec.ts
  __integration-tests__/server/pages/api/pages/[id]/restrict-permissions.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/status.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/set-default-page-permissions.spec.ts
  __integration-tests__/server/pages/api/submissions/[id]/index.spec.ts
  __integration-tests__/server/pages/api/submissions/index.spec.ts
  __integration-tests__/server/pages/api/threads/[id]/resolve.spec.ts
  __integration-tests__/server/pages/api/token-gates/[id]/roles.spec.ts
  charmClient/charmClient.ts
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySignupButton.tsx
  components/common/RouteGuard.tsx
  components/common/TokenGateForm/TokenGateForm.tsx
  components/invite/InviteLinkPage.tsx
  components/login/LoginPageContent.tsx
  components/login/WalletSign.tsx
  components/login/index.ts
  components/settings/roles/components/TokenGates/TokenGates.tsx
  components/share/PublicPage.tsx
  hooks/useLocalStorage.tsx
  hooks/useUser.tsx
  hooks/useWeb3AuthSig.tsx
  lib/blockchain/interfaces.ts
  lib/blockchain/signAndVerify.ts
  lib/middleware/requireWalletSignature.ts
  lib/utilities/errors/errors.ts
  lib/utilities/strings.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/profile/dev.ts
  pages/api/profile/index.ts
  pages/api/session/login-testenv.ts
  pages/api/session/login.ts
  pages/index.tsx
  testing/mockApiCall.ts
Labels: work-in-progress, :rocket: deploy

#1039 Secrets script
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .platform/confighooks/predeploy/01_pull_secrets.sh
  .platform/hooks/predeploy/01_pull_secrets.sh
  files_to_zip.txt
Labels: :rocket: deploy

#1052 Add space from sidebar bugfix
  components/common/CreateSpaceForm.tsx
  components/common/PageLayout/components/Sidebar/Workspaces.tsx
  hooks/useSpaces.tsx
  pages/createWorkspace.tsx
Labels: :rocket: deploy

#1055 Updated user sign/signup flow
  charmClient/charmClient.ts
  components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
  components/common/TokenGateForm/JoinPredefinedSpaceDomain.tsx
  components/common/TokenGateForm/TokenGateForm.tsx
  components/share/PublicPage.tsx
  lib/spaces/__tests__/getSpaceByDomain.spec.ts
  lib/spaces/__tests__/getSpacePublicInfo.spec.ts
  lib/spaces/__tests__/getSpacesByName.spec.ts
  lib/spaces/getSpaceByDomain.ts
  lib/spaces/getSpacePublicInfo.ts
  lib/spaces/getSpacesByName.ts
  pages/api/spaces/[id]/public.ts
  pages/api/spaces/search-domain.ts
  pages/api/spaces/search-name.ts
  pages/join.tsx
  testing/setupDatabase.ts
Labels: :rocket: deploy

#1065 fix markdown export with tracking marks
  components/common/CharmEditor/components/suggestions/schema/common/track.ts
Labels: :rocket: deploy

#1030 Pages list jumps to top when selecting a page
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
Labels: work-in-progress

#1105 upgrade prisma to 4.4
  package-lock.json
  package.json
Labels: :rocket: deploy

#1106 adding tags to every resource in staging
  .cdk/staging-stack.ts
  docker-compose.yml
Labels: :rocket: deploy

#1107 Added bounties table to My Nexus
  components/bounties/components/BountyStatusBadge.tsx
  components/nexus/BountyTasksList.tsx
  components/nexus/MentionedTasksList.tsx
  components/nexus/TasksPage.tsx
  components/nexus/VoteTasksList.tsx
  lib/applications/actions/createApplication.ts
  lib/applications/interfaces.ts
  lib/bounties/__tests__/getBountyTasks.spec.ts
  lib/bounties/getBountyAction.ts
  lib/bounties/getBountyTasks.ts
  lib/permissions/interfaces.ts
  lib/proposal/getProposalTasks.ts
  pages/api/tasks/list.ts
  prisma/migrations/20221017155636_add_bounty_notification_type/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1108 Nexus -> Keep votes visible after cast
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/nexus/TasksPage.tsx
  components/nexus/VoteTasksList.tsx
  lib/votes/__tests__/getVoteTasks.spec.ts
  lib/votes/getVoteTasks.ts
Labels: :rocket: deploy

#1112 Real time board updates
  .ebextensions/00_env_vars.config
  .ebextensions/03_setup_websocket_config
  .env
  components/WebSocketTester.tsx
  components/[pageId]/BoardPage/BoardPage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/FocalBoardProvider.tsx
  components/common/BoardEditor/focalboard/src/components/newVersionBanner.scss
  components/common/BoardEditor/focalboard/src/components/newVersionBanner.tsx
  components/common/BoardEditor/focalboard/src/hooks/cardListener.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/octoClient.ts
  components/common/BoardEditor/focalboard/src/store/boards.ts
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/BoardEditor/focalboard/src/store/initialLoad.ts
  components/common/BoardEditor/focalboard/src/store/users.ts
  components/common/BoardEditor/focalboard/src/store/views.ts
  components/common/BoardEditor/focalboard/src/wsclient.ts
  components/common/BoardEditor/publisher.ts
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  hooks/useKeydownPress.ts
  hooks/usePages.tsx
  hooks/useSocketClient.tsx
  lib/cache/redisClient.ts
  lib/pages/modifyChildPages.ts
  lib/pages/server/getPageMetaList.ts
  lib/websockets/broadcaster.ts
  lib/websockets/interfaces.ts
  lib/websockets/pubSub.ts
  lib/websockets/relay.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/blocks/[id]/index.ts
  pages/api/blocks/index.ts
  pages/api/pages/[id]/archive.ts
  pages/api/pages/[id]/index.ts
  pages/api/pages/index.ts
  pages/api/socket.ts
Labels: :rocket: deploy

#1137 add debug info for sockets
  charmClient/charmClient.ts
  hooks/useSocketClient.tsx
  lib/permissions/errors.ts
  lib/websockets/broadcaster.ts
  lib/websockets/interfaces.ts
  pages/api/socket.ts
Labels: :rocket: deploy

#1129 Feat - better discord account association
  lib/users/mergeUserDiscordAccounts.ts
  pages/api/discord/connect.ts
  pages/api/email-templates/index.ts
  pages/api/spaces/[id]/members/index.ts
  prisma/migrations/20221025120519_user_deleted_at_field/migration.sql
  prisma/schema.prisma
Labels: enhancement

#1143 fix toggle for edit mode disappearing
  components/[pageId]/EditorPage/EditorPage.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/EditingModeToggle.tsx
Labels: bug
