Repository charmverse/app.charmverse.io, pull requests merged in 2022-11, with the labels that each got.

#1160 add robots.txt file and hide invite links from web crawlers
  pages/invite/[inviteCode].tsx
  public/robots.txt
Labels: bug

#1170 Member directory property visibility
  charmClient/apis/membersApi.ts
  components/common/BoardEditor/focalboard/src/widgets/icons/gallery.tsx
  components/common/BoardEditor/focalboard/src/widgets/icons/table.tsx
  components/members/MemberDirectoryPage.tsx
  components/members/components/MemberDirectoryGalleryView.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertySidebarDetails.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertyVisibility.tsx
  components/members/components/MemberDirectorySort/MemberDirectorySort.tsx
  components/members/components/MemberDirectoryTableView.tsx
  components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
  components/profile/components/UserDetails/SocialIcons.tsx
  hooks/useMemberProperties.tsx
  lib/members/__tests__/updateMemberPropertyVisibility.spec.ts
  lib/members/constants.ts
  lib/members/interfaces.ts
  lib/members/updateMemberPropertyVisibility.ts
  lib/members/utils.ts
  pages/api/spaces/[id]/members/properties/visibility.ts
  prisma/migrations/20221104103637_property_views/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1188 add Twitter embed
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
  components/common/CharmEditor/components/tweet/components/Tweet.tsx
  components/common/CharmEditor/components/tweet/components/TweetInput.tsx
  components/common/CharmEditor/components/tweet/tweet.ts
  components/common/CharmEditor/components/tweet/twitterJSUrl.ts
  components/common/CharmEditor/specRegistry.ts
  lib/prosemirror/insertNode.ts
  pages/_app.tsx
  theme/cssVariables.ts
Labels: :rocket: deploy

#1204 Allow non-native tokens thru Gnosis safe
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantTableRow.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx
  components/bounties/components/MultiPaymentModal.tsx
  hooks/useGnosisPayment.ts
  hooks/useMultiBountyPayment.ts
  lib/payment-methods/defaultPaymentMethods.ts
Labels: :rocket: deploy

#1205 Feat/focalboard select port
  components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx
  components/common/BoardEditor/components/properties/SelectProperty/mappers.ts
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/form/fields/FieldWrapper.tsx
  components/common/form/fields/Select/SelectPreview.tsx
  components/common/form/fields/SelectField.tsx
  components/profile/components/SpacesMemberDetails/components/useMutateMemberPropertyValues.ts
  theme/utils/getPropertyColorName.ts
Labels: :rocket: deploy

#1199 Feat/select editable options
  components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx
  components/common/BoardEditor/components/properties/SelectProperty/mappers.ts
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/BoardEditor/interfaces.ts
  components/common/BoardEditor/utils/convertFocalboardToMUIColor.ts
  components/common/BoardEditor/utils/mapMUIColorToProperty.ts
  components/common/PopperPopup.tsx
  components/common/form/fields/FieldTypeRenderer.tsx
  components/common/form/fields/FieldWrapper.tsx
  components/common/form/fields/Select/SelectOptionEdit.tsx
  components/common/form/fields/Select/SelectOptionItem.tsx
  components/common/form/fields/Select/SelectPreview.tsx
  components/common/form/fields/Select/interfaces.ts
  components/common/form/fields/SelectField.tsx
  components/common/form/interfaces.ts
  components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopupForm.tsx
  components/profile/components/SpacesMemberDetails/components/useMutateMemberPropertyValues.ts
  hooks/useIsAdmin.ts
  lib/members/utils.ts
  theme/colors.ts
Labels: :rocket: deploy

#1224 Fix for Gnosis safes + bounties
  components/bounties/components/MultiPaymentButton.tsx
  components/bounties/components/MultiPaymentModal.tsx
  hooks/useGnosisPayment.ts
  hooks/useMultiBountyPayment.ts
Labels: bug, :rocket: deploy

#1215 Member directory immutable join date property
  components/members/components/AddMemberPropertyButton.tsx
  components/members/components/MemberDirectoryGalleryView.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertyItem.tsx
  components/members/components/MemberDirectorySort/MemberDirectorySort.tsx
  components/members/components/MemberDirectorySort/utils.ts
  components/members/components/MemberDirectoryTableView.tsx
  components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
  lib/members/__tests__/getSpaceMemberRoles.spec.ts
  lib/members/__tests__/updateMemberProperty.spec.ts
  lib/members/__tests__/updateMemberPropertyVisibility.spec.ts
  lib/members/constants.ts
  lib/members/createMemberProperty.ts
  lib/members/generateDefaultPropertiesInput.ts
  lib/members/getSpaceMemberMetadata.ts
  lib/members/getSpacesPropertyValues.ts
  pages/api/spaces/[id]/members/properties/index.ts
  prisma/migrations/20221113095431_md_join_date/migration.sql
  prisma/schema.prisma
  scripts/addJoinDateMemberDirectoryProperty.ts
  scripts/reorderMemberDirectoryProperties.ts
  scripts/seedMemberProp.ts
  testing/utils/members.ts
Labels: :rocket: deploy

#1241 add secrets for S3
  .ebextensions/00_env_vars.config
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  README.md
  lib/aws/getS3ClientConfig.ts
  lib/aws/uploadToS3Server.ts
  pages/api/aws/s3-delete.ts
  pages/api/aws/s3-upload.ts
  testing/generate-page-stub.ts
Labels: :rocket: deploy

#1230 Fix double click issue on iOS
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.scss
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.scss
  components/common/BoardEditor/focalboard/src/components/table/tableRow.scss
  next.base.js
  package-lock.json
  package.json
Labels: :rocket: deploy

#1246 Edited/created by
  components/common/PageLayout/components/DocumentHistory/DocumentHistory.tsx
  components/common/PageLayout/components/DocumentHistory/index.tsx
  components/common/PageLayout/components/Header/Header.tsx
  lib/utilities/dates.ts
Labels: :rocket: deploy

#1257 convert user wallet address to checksum when querying gnosis
  lib/gnosis/gnosis.ts
Labels: bug

#1258 fix check for member property on user profiles
  components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
Labels: bug

#1264 add media query for link hover effects
  components/common/ActionsMenu.tsx
  components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx
  components/common/BoardEditor/focalboard/src/widgets/menu/menu.scss
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/BlockAligner.tsx
  components/common/Emoji.tsx
  components/common/Link.tsx
  components/common/PrimaryButton.tsx
  theme/focalboard/focalboard.main.scss
Labels: :rocket: deploy

#1266 Add merging support to multiplayer
  components/common/CharmEditor/components/fiduswriter/collab/doc.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/changeset.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/index.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/recreate_transform.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/schema.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/tools.ts
  components/common/CharmEditor/components/fiduswriter/schema/convert.ts
  package-lock.json
  package.json
  scripts/query.ts
Labels: :rocket: deploy

#1262 Signup from join invite
  .ebextensions/00_env_vars.config
  __e2e__/joinWorkspace/tokenGates/tokenGateSuccess.spec.ts
  components/[pageId]/BoardPage/BoardPage.tsx
  components/common/Debug/MountTracker.tsx
  components/common/Debug/WebSocketTester.tsx
  components/common/Debug/index.ts
  components/common/RouteGuard.tsx
  components/common/Snackbar.tsx
  components/common/TokenGateForm/JoinPredefinedSpaceDomain.tsx
  components/common/TokenGateForm/TokenGateForm.tsx
  components/invite/InviteLinkPage.tsx
  components/login/WalletSign.tsx
  hooks/useSpaces.tsx
  hooks/useUser.tsx
  pages/join.tsx
Labels: work-in-progress, :rocket: deploy

#1274 Always show Gnosis even with 0 tasks
  components/nexus/GnosisTasksList.tsx
Labels: work-in-progress

#1263 Feat/super api token
  .cdk/staging-stack.ts
  .env.staging
  __integration-tests__/server/pages/api/token-gates/[id]/roles.spec.ts
  __integration-tests__/server/pages/api/v1/spaces/index.spec.ts
  components/common/CreateSpaceForm.tsx
  components/common/RouteGuard.tsx
  components/common/form/fields/getFieldRendererConfig.tsx
  jest.config-server.ts
  lib/discord/upsertUserForDiscordId.ts
  lib/middleware/index.ts
  lib/middleware/requireKeys.ts
  lib/middleware/requireSudoApiKey.ts
  lib/middleware/requireSuperApiKey.ts
  lib/public-api/createWorkspaceApi.ts
  lib/public-api/interfaces.ts
  lib/spaces/createWorkspace.ts
  lib/spaces/getAvailableDomainName.ts
  lib/spaces/utils.ts
  lib/spaces/validateDomainName.ts
  lib/utilities/errors/errors.ts
  lib/utilities/isValidUrl.ts
  pages/api-docs.tsx
  pages/api/discord/connect.ts
  pages/api/spaces/index.ts
  pages/api/sudo/api-tokens/index.ts
  pages/api/sudo/super-api-tokens/index.ts
  pages/api/v1/spaces/index.ts
  pages/index.tsx
  prisma/migrations/20221124144103_super_api_token/migration.sql
  prisma/schema.prisma
  scripts/makeSuperAPIKey.ts
  testing/utils/members.ts
  testing/utils/middleware.ts
  testing/utils/spaces.ts
Labels: :rocket: deploy

#1289 make member editing fullscreen
  components/common/Modal/Modal.tsx
  components/members/components/MemberDirectoryGalleryView.tsx
  components/members/components/MemberDirectoryTableView.tsx
  components/members/components/MemberOnboardingForm.tsx
  components/profile/components/SpacesMemberDetails/SpacesMemberDetails.tsx
  components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
Labels: :rocket: deploy

#1267 Forum main page
  __integration-tests__/server/pages/api/spaces/[id]/post-categories/[postCategoryId]/index.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/post-categories/index.spec.ts
  background/tasks/deleteArchivedPages/task.ts
  charmClient/apis/forumApi.ts
  charmClient/charmClient.ts
  components/common/PageLayout/components/SearchInWorkspaceModal.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/UserDisplay.tsx
  components/forum/ForumPage.tsx
  components/forum/components/CreateForumPost/CreateForumPost.tsx
  components/forum/components/CreateForumPost/index.ts
  components/forum/components/FilterList/FilterList.tsx
  components/forum/components/FilterList/index.ts
  components/forum/components/FilterSelect/FilterSelect.tsx
  components/forum/components/FilterSelect/index.ts
  components/forum/components/ForumPost/ForumPost.tsx
  components/forum/components/ForumPost/index.ts
  components/forum/components/ForumPostSkeleton/ForumPostSkeleton.tsx
  components/forum/components/ForumPostSkeleton/index.ts
  components/forum/components/ForumPosts/ForumPosts.tsx
  components/forum/components/ForumPosts/index.ts
  hooks/useForumFilters.ts
  hooks/useOnScreen.ts
  lib/forum/getForumPosts.ts
  lib/forum/interfaces.ts
  lib/pages/interfaces.ts
  lib/pages/server/deleteArchivedPages.ts
  lib/pages/server/getAccessiblePages.ts
  lib/posts/__tests__/createPostCategory.spec.ts
  lib/posts/__tests__/getPostCategories.spec.ts
  lib/posts/__tests__/updatePostCategory.spec.ts
  lib/posts/createPostCategory.ts
  lib/posts/generateDefaultPostCategories.ts
  lib/posts/getPostCategories.ts
  lib/posts/updatePostCategory.ts
  lib/spaces/__tests__/createWorkspace.spec.ts
  lib/spaces/createWorkspace.ts
  lib/templates/importWorkspacePages.ts
  pages/[domain]/forum/index.tsx
  pages/api/forum/posts.ts
  pages/api/spaces/[id]/post-categories/[postCategoryId]/index.ts
  pages/api/spaces/[id]/post-categories/index.ts
  prisma/migrations/20221125155909_add_forum_post_m/migration.sql
  prisma/migrations/20221128155029_add_page_post_type/migration.sql
  prisma/migrations/20221129095053_fix_unique_postcategory/migration.sql
  prisma/schema.prisma
  scripts/migrations/provisionDefaultPostCategories.ts
Labels: work-in-progress, :rocket: deploy
