Repository charmverse/app.charmverse.io, pull requests merged in 2023-05, with the labels that each got.

#2107 dont use custom server in production/staging
  docker-compose.yml
  package.json
  tsconfig.server.json
Labels: :rocket: deploy

#2100 Typeform - map the types & CSV - Transform Options
  components/common/PageLayout/components/Header/components/utils/__tests__/databasePageOptions.spec.ts
  components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
  components/common/PageLayout/components/Header/components/utils/mocks.ts
  lib/focalboard/board.ts
  lib/pages/createFormResponseCard.ts
  lib/pages/interfaces.ts
  lib/public-api/createDatabaseCardPage.ts
  lib/public-api/updateDatabaseBlocks.ts
  lib/typeform/interfaces.ts
  lib/typeform/simplifyTypeformResponse.ts
  lib/typeform/transformWebhookBodyFormResponse.ts
  pages/api/v1/webhooks/addToDatabase/[key]/index.ts
Labels: :rocket: deploy

#2117 bump socket.io-client to 4.6.1 to match server
  package-lock.json
  package.json
Labels: :rocket: deploy

#2109 Fix action bar click on mobile
  components/common/CharmEditor/components/floatingMenu/Icon.tsx
  components/common/CharmEditor/components/floatingMenu/MenuButtons.tsx
Labels: :rocket: deploy

#2119 Refactor page actions
  .cdk/staging-stack.ts
  __e2e__/po/forumHome.po.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/bounties/BountiesPage.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/BountyGalleryCard.tsx
  components/bounties/components/BountyGalleryView.tsx
  components/bounties/components/BountyKanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/PageActions/FullPageActionsMenuButton.tsx
  components/common/PageActions/KanbanPageActionButton.tsx
  components/common/PageActions/components/AddToFavoritesAction.tsx
  components/common/PageActions/components/BountyActions.tsx
  components/common/PageActions/components/CopyPageLinkAction.tsx
  components/common/PageActions/components/DatabasePageActionList.tsx
  components/common/PageActions/components/DeletePageAction.tsx
  components/common/PageActions/components/DocumentHistory.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/DuplicatePageAction.tsx
  components/common/PageActions/components/ExportMarkdownAction.tsx
  components/common/PageActions/components/ExportToPDFAction.tsx
  components/common/PageActions/components/ForumPostActionList.tsx
  components/common/PageActions/components/PageActionsMenu.tsx
  components/common/PageActions/components/SnapshotAction/ConnectSnapshot.tsx
  components/common/PageActions/components/SnapshotAction/InputVotingStrategies.tsx
  components/common/PageActions/components/SnapshotAction/PublishToSnapshot.tsx
  components/common/PageActions/components/SnapshotAction/PublishingForm.tsx
  components/common/PageActions/components/UndoAction.tsx
  components/common/PageActions/utils/__tests__/databasePageOptions.spec.ts
  components/common/PageActions/utils/databasePageOptions.ts
  components/common/PageActions/utils/exportMarkdown.ts
  components/common/PageActions/utils/mocks.ts
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/PageDialogGlobal.tsx
  components/common/PageDialog/index.tsx
  components/common/PageLayout/NexusLayout.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/SharedPageLayout.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/hooks/usePostByPath.ts
  components/proposals/ProposalsPage.tsx
  components/proposals/components/ProposalActionsMenu.tsx
  components/settings/workspace/Space.tsx
  components/votes/components/CreateVoteModal.tsx
  hooks/usePostPermissions.ts
  hooks/useToggleFavorite.ts
  lib/typeform/simplifyTypeformResponse.ts
  pages/api/forums/posts/[postId]/index.ts
  theme/fonts.ts
Labels: :rocket: deploy

#2118 Fix deletion for inline dbs
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  lib/pages/__tests__/modifyChildPages.spec.ts
  lib/pages/modifyChildPages.ts
Labels: :rocket: deploy

#1885 Comment form browser UT
  components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts
  components/common/BoardEditor/focalboard/csvExporter/__tests__/mocks.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/listItem/listItem.nodeViewPlugin.ts
  components/common/CharmEditor/components/table/index.ts
  components/common/CharmEditor/components/table/table.ts
  components/common/CharmEditor/components/video/VideoNodeView.tsx
  components/common/CharmEditor/specRegistry.ts
  components/common/comments/__tests__/ComentForm.spec.tsx
  components/common/errors/ErrorBoundary.tsx
  components/integrations/components/IdentityProviders.tsx
  hooks/usePageActionDisplay.tsx
  hooks/useUser.tsx
  jest.config-all.ts
  jest.config-browser.ts
  lib/public-api/updateDatabaseBlocks.ts
  lib/token-gates/__tests__/verifyTokenGateMemberships.spec.ts
  next.base.js
  package-lock.json
  package.json
  patches/@skiff-org+prosemirror-tables+3.5.1.patch
  testing/createJestConfig.ts
  testing/customRender.tsx
  testing/fileMock.js
  testing/mocks/user.ts
Labels: work-in-progress, :rocket: deploy

#2135 remove snapshot id from page meta
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/nodeView/nodeView.ts
  components/common/CharmEditor/components/poll/PollComponent.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/SnapshotAction/PublishToSnapshot.tsx
  components/common/PageActions/components/SnapshotAction/PublishingForm.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/votes/components/CreateVoteModal.tsx
  lib/pages/interfaces.ts
  lib/pages/server/getAccessiblePages.ts
  lib/pages/server/getPageMeta.ts
  lib/websockets/interfaces.ts
  pages/api/pages/[id]/snapshot.ts
Labels: :rocket: deploy

#2161 adding in permissions api to run alongside webapp
  docker-compose.yml
Labels: :rocket: deploy

#2165 track post and page views
  .github/actions/install/action.yml
  __integration-tests__/server/pages/api/events/index.spec.ts
  components/[pageId]/EditorPage/EditorPage.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  pages/api/events/index.ts
  pages/api/session/login-testenv.ts
  testing/mockApiCall.ts
Labels: :rocket: deploy

#2168 Feat/subdomain cookies
  __integration-tests__/server/pages/api/session/logout.spec.ts
  lib/session/config.ts
  lib/session/getIronOptions.ts
  lib/session/withSession.ts
  lib/utilities/getValidSubdomain.ts
  lib/websockets/authentication.ts
Labels: :rocket: deploy

#2132 Stripe integration
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .env.example
  .github/actions/build/action.yml
  .github/actions/install/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  .gitignore
  __integration-tests__/server/pages/api/spaces/[id]/subscription.spec.ts
  charmClient/apis/subscriptionApi.ts
  charmClient/charmClient.ts
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/components/SubmissionInput.tsx
  components/common/Modal/SettingsDialog.tsx
  components/settings/config.tsx
  components/subscription/CheckoutForm.tsx
  components/subscription/SubscriptionSettings.tsx
  lib/metrics/mixpanel/interfaces/SubscriptionEvent.ts
  lib/metrics/mixpanel/interfaces/index.ts
  lib/subscription/__tests__/createProSubscription.spec.ts
  lib/subscription/__tests__/getSpaceSubscription.spec.ts
  lib/subscription/constants.ts
  lib/subscription/createProSubscription.ts
  lib/subscription/getSpaceSubscription.ts
  lib/subscription/stripe.ts
  package-lock.json
  package.json
  pages/api/mux/upload.ts
  pages/api/spaces/[id]/subscription.ts
  pages/authenticate.tsx
  scripts/createStripeProducts.ts
  testing/utils/spaces.ts
Labels: work-in-progress, :rocket: deploy

#2181 Remove old domain cookie
  lib/session/getCookieDomain.ts
  lib/session/getIronOptions.ts
  pages/api/session/logout.ts
  pages/index.tsx
Labels: :rocket: deploy

#2187 Fix member search
  components/common/form/InputSearchMember.tsx
  components/members/MemberDirectoryPage.tsx
  lib/members/getMemberSearchValue.ts
  lib/members/getSpaceMembers.ts
Labels: bug

#2189 Fix/properly remove session cookie
  lib/session/removeOldCookie.ts
  pages/api/profile/index.ts
  pages/api/session/logout.ts
  pages/index.tsx
Labels: bug, :rocket: deploy

#2183 Fix user created another user account when logged in through google after having a verified email
  lib/google/__tests__/loginWithGoogle.spec.ts
  lib/google/loginWithGoogle.ts
Labels: bug

#2192 modified the pull secret script to operate on separate set of files
  .dockerignore
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .ebextensions_websockets/00_env_vars.config
  .ebstalk.apps.env/cron.env
  .ebstalk.apps.env/webapp.env
  .ebstalk.apps.env/websocket.env
  .github/workflows/deploy_staging.yml
  .platform/hooks/predeploy/01_pull_secrets.sh
  files_to_zip.txt
Labels: :rocket: deploy

#2191 Simplify rules to switch web3 accounts
  components/_app/hooks/useSpaceGatesReevaluate.ts
  components/common/SpaceAccessGate/SpaceAccessGate.tsx
  components/common/SpaceAccessGate/components/TokenGate/hooks/useTokenGates.ts
  hooks/useWeb3AuthSig.tsx
Labels: bug, :rocket: deploy

#2213 fix setup of columns for linked database views
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx
Labels: bug

#2207 allow running socket server w/o next.js compiler
  background/websockets.ts
  components/_app/Web3ConnectionManager/hooks/useInactiveListener.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/CharmEditor/components/fiduswriter/collab/doc.ts
  components/common/CharmEditor/components/fiduswriter/collab/merge/index.ts
  components/common/CharmEditor/components/fiduswriter/ws.ts
  components/common/CharmEditor/components/floatingMenu/index.ts
  components/common/CharmEditor/components/inlineComment/index.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
  components/common/CharmEditor/components/inlinePalette/index.ts
  components/common/CharmEditor/components/inlinePalette/useEditorItems.ts
  components/common/CharmEditor/components/nft/NFTNodeView.tsx
  components/common/CharmEditor/components/nft/config.ts
  esbuild.websockets.js
  lib/websockets/broadcaster.ts
  lib/websockets/documentEvents/documentEvents.ts
  lib/websockets/documentEvents/interfaces.ts
  package-lock.json
  package.json
  tsconfig.websockets.json
Labels: :rocket: deploy

#2164 Subdomains with middleware POC
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/BountyGalleryView.tsx
  components/bounties/hooks/useOnBountyCardClose.ts
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/Button.tsx
  components/common/Link.tsx
  components/common/PageActions/components/CopyPageLinkAction.tsx
  components/common/PageLayout/components/Header/components/BountyShareButton/ShareBountyBoard.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/Sidebar/SpaceListItem.tsx
  components/common/RouteGuard.tsx
  components/login/LoginPage.tsx
  components/settings/workspace/Space.tsx
  hooks/useCurrentSpace.ts
  hooks/useRouterTransition.ts
  hooks/useSharedPage.ts
  lib/session/getIronOptions.ts
  lib/session/removeOldCookie.ts
  lib/spaces/filterSpaceByDomain.ts
  lib/spaces/utils.ts
  lib/utilities/browser.ts
  lib/utilities/domains/getAppApexDomain.ts
  lib/utilities/domains/getValidCustomDomain.ts
  lib/utilities/domains/getValidDefaultHost.ts
  lib/utilities/domains/isLocalhostAlias.ts
  lib/utilities/getSpaceDomainFromUrlPath.ts
  lib/utilities/getValidSubdomain.ts
  middleware.ts
  pages/[domain]/index.tsx
  pages/api/blocks/index.ts
  pages/api/discord/callback.ts
  pages/api/discord/oauth.ts
  pages/createSpace.tsx
  pages/index.tsx
  pages/join.tsx
Labels: :rocket: deploy

#2219 only load stripe on checkout
  components/subscription/SubscriptionSettings.tsx
  components/subscription/loadStripe.ts
  scripts/getPageHistory.ts
  scripts/query.ts
Labels: :rocket: deploy

#2229 add missing env vars
  .ebstalk.apps.env/webapp.env
Labels: :rocket: deploy

#2233 Decrease spam filters from alchemy
  adapters/http/fetch.ts
  lib/blockchain/provider/alchemy.ts
Labels: :rocket: deploy

#2235 Fix table headers selection
  components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx
Labels: :rocket: deploy
