Repository charmverse/app.charmverse.io, pull requests merged in 2023-04, with the labels that each got.

#1967 Remove extra step in signup flow
  __e2e__/po/signup.po.ts
  __e2e__/sessions/signup.spec.ts
  __e2e__/sessions/signupDiscord.spec.ts
  charmClient/charmClient.ts
  components/common/BaseLayout/components/Header.tsx
  components/common/CreateSpaceForm/CreateSpaceForm.tsx
  components/common/CreateSpaceForm/SelectNewSpaceTemplate.tsx
  components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx
  components/common/SpaceAccessGate/SpaceAccessGateWithSearch.tsx
  components/login/Footer.tsx
  components/login/LoginPageContent.tsx
  components/login/components/LoginLayout.tsx
  components/signup/SignupForm.tsx
  hooks/useSpaces.tsx
  lib/public-api/createWorkspaceApi.ts
  lib/spaces/__tests__/createWorkspace.spec.ts
  lib/spaces/config.ts
  lib/spaces/createSpace.ts
  next.config.js
  pages/api/spaces/index.ts
  pages/createSpace.tsx
  pages/createWorkspace.tsx
  pages/index.tsx
  pages/join.tsx
  pages/signup.tsx
Labels: :rocket: deploy

#1961 Permission selector
  __integration-tests__/server/pages/api/pages/index.spec.ts
  __integration-tests__/server/pages/api/permissions/index.spec.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/ProposalPagePermissions.tsx
  components/forum/components/permissions/PostCategoryPermissionRow.tsx
  components/forum/components/permissions/PostCategoryPermissions.tsx
  components/proposals/components/permissions/ProposalCategoryPermissionRow.tsx
  components/proposals/components/permissions/ProposalCategoryPermissions.tsx
  hooks/usePages.tsx
  lib/metrics/mixpanel/interfaces/SettingEvent.ts
  lib/permissions/__tests__/basePermissions.class.spec.ts
  lib/permissions/__tests__/filterApplicablePermissions.spec.ts
  lib/permissions/basePermissions.class.ts
  lib/permissions/bounties/availableBountyPermissions.ts
  lib/permissions/filterApplicablePermissions.ts
  lib/permissions/forum/__tests__/computePostCategoryPermissions.spec.ts
  lib/permissions/forum/__tests__/computePostPermissions.spec.ts
  lib/permissions/forum/computePostCategoryPermissions.ts
  lib/permissions/forum/computePostPermissions.ts
  lib/permissions/meta/preset-templates.ts
  lib/permissions/pages/__tests__/page-permission-compute.spec.ts
  lib/permissions/pages/available-page-permissions.class.ts
  lib/permissions/pages/page-permission-compute.ts
  lib/permissions/permissions.class.ts
  lib/permissions/proposals/computeProposalCategoryPermissions.ts
  lib/permissions/proposals/computeProposalPermissions/computeProposalPermissions.ts
  lib/permissions/spaces/__tests__/computeSpacePermissions.spec.ts
  lib/permissions/spaces/availableSpacePermissions.ts
  lib/permissions/spaces/computeSpacePermissions.ts
  lib/permissions/spaces/interfaces.ts
  lib/users/__tests__/countConnectableIdentities.spec.ts
  lib/users/__tests__/disconnectWallet.spec.ts
  lib/users/__tests__/updateUsedIdentity.spec.ts
  pages/api/bounties/index.ts
  pages/api/pages/index.ts
  pages/api/permissions/index.ts
  pages/api/permissions/space/[spaceId]/compute.ts
  prisma/migrations/20230403143706_drop_create_vote_operation/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1976 clear cache when user logs out
  hooks/useUser.tsx
Labels: :rocket: deploy

#1963 Connect button for invite links
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
  components/invite/InviteLinkPage.tsx
  components/login/Login.tsx
  hooks/useFirebaseAuth.tsx
Labels: :rocket: deploy

#1894 Add a script to count block usages of spaces
  lib/prosemirror/countBlocks.ts
  lib/spaces/countData.ts
  next.config.js
  scripts/countSpaceData.ts
Labels: work-in-progress

#1983 Fix restrict editing for bounty page
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyPropertiesHeader.tsx
Labels: :rocket: deploy

#1978 Confirm csv import with 2 actions
  charmClient/charmClient.ts
  components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/Modal/ConfirmImportModal.tsx
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  lib/pages/interfaces.ts
  pages/api/blocks/index.ts
  pages/api/pages/[id]/archive.ts
  pages/api/pages/[id]/index.ts
  pages/api/pages/index.ts
Labels: :rocket: deploy

#1989 Guest label
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/AddPagePermissionsForm.tsx
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
  lib/permissions/pages/actions/list-page-permissions.ts
  lib/permissions/pages/page-permission-interfaces.ts
Labels: :rocket: deploy

#1977 Save proposal and forum categories via Save button
  __e2e__/forum/assignSpaceWideForumModerators.spec.ts
  __e2e__/po/settings/spacePermissionSettings.po.ts
  __e2e__/settings/applyCorrectSpace.spec.ts
  __integration-tests__/server/pages/api/permissions/forum/list-post-category-permissions.spec.ts
  __integration-tests__/server/pages/api/permissions/proposals/list-proposal-category-permissions.spec.ts
  __integration-tests__/server/pages/api/permissions/spaces/[spaceId]/add.spec.ts
  __integration-tests__/server/pages/api/permissions/spaces/[spaceId]/remove.spec.ts
  __integration-tests__/server/pages/api/permissions/spaces/[spaceId]/settings.spec.ts
  charmClient/apis/permissions/forumApi.ts
  charmClient/apis/permissions/index.ts
  charmClient/apis/permissions/proposalsApi.ts
  charmClient/apis/permissions/spacePermissionsApi.ts
  charmClient/charmClient.ts
  components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/ProposalPagePermissions.tsx
  components/forum/components/permissions/PostCategoryPermissionRow.tsx
  components/proposals/components/permissions/ProposalCategoryPermissionRow.tsx
  components/proposals/hooks/useProposalCategories.ts
  components/settings/roles/RoleSettings.tsx
  components/settings/roles/components/MemberRoleRow.tsx
  components/settings/roles/components/RolePermissions/RolePermissions.tsx
  components/settings/roles/components/RolePermissions/components/DefaultPagePermissions.tsx
  hooks/useCurrentSpacePermissions.ts
  hooks/useForumCategories.tsx
  lib/permissions/forum/__tests__/listPostCategoryPermissions.spec.ts
  lib/permissions/forum/listGroupPostCategoryPermissions.ts
  lib/permissions/forum/listPostCategoryPermissions.ts
  lib/permissions/interfaces.ts
  lib/permissions/proposals/listGroupProposalCategoryPermissions.ts
  lib/permissions/proposals/listProposalCategoryPermissions.ts
  lib/permissions/spaces/__tests__/addSpaceOperations.spec.ts
  lib/permissions/spaces/__tests__/removeSpaceOperations.spec.ts
  lib/permissions/spaces/addSpaceOperations.ts
  lib/permissions/spaces/computeGroupSpacePermissions.ts
  lib/permissions/spaces/listPermissions.ts
  lib/permissions/spaces/mapSpacePermissionToAssignee.ts
  lib/permissions/spaces/savePermissions.ts
  lib/permissions/utils.ts
  pages/api/permissions/forum/list-group-post-category-permissions.ts
  pages/api/permissions/forum/list-post-category-permissions.ts
  pages/api/permissions/proposals/list-group-proposal-category-permissions.ts
  pages/api/permissions/proposals/list-proposal-category-permissions.ts
  pages/api/permissions/space/[spaceId]/add.ts
  pages/api/permissions/space/[spaceId]/query.ts
  pages/api/permissions/space/[spaceId]/remove.ts
  pages/api/permissions/space/[spaceId]/settings.ts
Labels: work-in-progress, :rocket: deploy

#1991 updates to login page ui
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  components/invite/InviteLinkPage.tsx
  components/login/LoginButton.tsx
  components/login/LoginPageContent.tsx
  hooks/useFirebaseAuth.tsx
Labels: :rocket: deploy

#1984 Feat/notifications modal
  __e2e__/notifications/notificationsRedirect.spec.ts
  __e2e__/settings/notificationsRedirect.spec.ts
  background/tasks/sendNotifications/sendNotifications.ts
  charmClient/apis/tasksApi.ts
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationButton.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationModal.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationPreview.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationPreviewPopover.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/useNotificationModal.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/useNotificationPreview.ts
  components/common/PageLayout/components/Header/components/NotificationPreview/useNotifications.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/utils.ts
  components/common/PageLayout/components/Sidebar/NotificationsBadge.tsx
  components/common/PageLayout/components/Sidebar/SidebarButton.tsx
  components/integrations/components/MultiSigConnectCard.tsx
  components/integrations/components/MultiSigList.tsx
  components/nexus/BountyTasksList.tsx
  components/nexus/DiscussionTasksList.tsx
  components/nexus/ForumTasksList.tsx
  components/nexus/GnosisTasksList/GnosisTasksList.tsx
  components/nexus/GnosisTasksList/GnosisTasksTable.tsx
  components/nexus/GnosisTasksList/index.ts
  components/nexus/ProposalTasksList.tsx
  components/nexus/TasksPage.tsx
  components/nexus/TasksPageHeader.tsx
  components/nexus/VoteTasksList.tsx
  components/nexus/components/EmptyTaskState.tsx
  components/nexus/hooks/useTasks.ts
  components/nexus/index.ts
  components/proposals/components/ProposalActionsMenu.tsx
  components/proposals/components/ProposalsTable.tsx
  components/settings/config.tsx
  components/votes/components/NewProposalButton.tsx
  hooks/useSettingsDialog.tsx
  hooks/useVotes.tsx
  lib/emails/templates/PendingTasks.tsx
  lib/gnosis/gnosis.tasks.ts
  pages/_app.tsx
  pages/api/email-templates/index.ts
  pages/api/tasks/gnosis.ts
  pages/index.tsx
  scripts/readNotifications.ts
Labels: :rocket: deploy

#2009 Feat/post draft matt
  components/forum/ForumFeedPage.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostDialog/PostDialogGlobal.tsx
  components/forum/components/PostDialog/hooks/usePostDialog.tsx
  components/forum/components/PostPage/PostPage.tsx
Labels: :rocket: deploy

#2003 Create draft post for author
  __integration-tests__/server/pages/api/forums/posts/[postId]/comments/[commentId].spec.ts
  __integration-tests__/server/pages/api/forums/posts/[postId]/index.spec.ts
  __integration-tests__/server/pages/api/forums/posts/index.spec.ts
  __integration-tests__/server/pages/api/posts/[postId]/convert-to-proposal.spec.ts
  charmClient/apis/forumApi.ts
  components/common/PageLayout/components/Header/Header.tsx
  components/forum/ForumFeedPage.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostDialog/PostDialogGlobal.tsx
  components/forum/components/PostDialog/hooks/usePostDialog.tsx
  components/forum/components/PostList/DraftPostList.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostPage/DraftPostBanner.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/PostComment.tsx
  lib/forums/categories/__tests__/deletePostCategory.spec.ts
  lib/forums/getForumNotifications/getForumNotifications.ts
  lib/forums/posts/__tests__/createForumPost.spec.ts
  lib/forums/posts/__tests__/voteForumPost.spec.ts
  lib/forums/posts/createForumPost.ts
  lib/forums/posts/getPostMeta.ts
  lib/forums/posts/interfaces.ts
  lib/forums/posts/listDraftPosts.ts
  lib/forums/posts/listForumPosts.ts
  lib/forums/posts/searchForumPosts.ts
  lib/forums/posts/updateForumPost.ts
  lib/metrics/mixpanel/interfaces/ForumEvent.ts
  lib/permissions/forum/__tests__/computePostPermissions.spec.ts
  lib/permissions/forum/computePostPermissions.ts
  pages/api/forums/posts/[postId]/comments/index.ts
  pages/api/forums/posts/[postId]/convert-to-proposal.ts
  pages/api/forums/posts/[postId]/index.ts
  pages/api/forums/posts/[postId]/vote.ts
  pages/api/forums/posts/drafts.ts
  pages/api/forums/posts/index.ts
  prisma/migrations/20230411120259_draft_forum_post/migration.sql
  prisma/schema.prisma
  testing/forums.ts
  testing/utils/forums.ts
Labels: :rocket: deploy

#2008 Add multiple wallets to account
  components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
  components/integrations/components/AddWalletStep.tsx
  components/integrations/components/IdentityProviderItem.tsx
  components/integrations/components/NewIdentityModal.tsx
  hooks/useWeb3AuthSig.tsx
  pages/api/profile/add-wallets.ts
Labels: :rocket: deploy

#1996 support votes on forum posts
  __integration-tests__/server/pages/api/spaces/[id]/votes.spec.ts
  __integration-tests__/server/pages/api/votes/index.spec.ts
  background/tasks/updateVotesStatus/updateVoteStatus.ts
  charmClient/apis/votesApi.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/floatingMenu/floatingMenu.plugins.ts
  components/common/CharmEditor/components/inlineVote/components/InlineVoteSubmenu.tsx
  components/common/CharmEditor/components/nodeView/nodeView.ts
  components/common/CharmEditor/components/poll/PollComponent.tsx
  components/common/PageActionsMenu.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/hooks/usePostByPath.ts
  components/votes/components/CreateVoteModal.tsx
  hooks/usePageActionDisplay.tsx
  hooks/usePostPermissions.ts
  hooks/useVotes.tsx
  lib/emails/templates/PendingTasks.tsx
  lib/forums/posts/__tests__/createForumPost.spec.ts
  lib/forums/posts/createForumPost.ts
  lib/prosemirror/extractPollIdsFromDoc.ts
  lib/templates/importWorkspacePages.ts
  lib/votes/__tests__/getVotesBySpace.spec.ts
  lib/votes/__tests__/utils.spec.ts
  lib/votes/castVote.ts
  lib/votes/createVote.ts
  lib/votes/getVoteTasks.ts
  lib/votes/getVotesByPage.ts
  lib/votes/getVotesBySpace.ts
  lib/votes/index.ts
  lib/votes/interfaces.ts
  pages/[domain]/forum/post/[pagePath].tsx
  pages/api/pages/[id]/votes.ts
  pages/api/spaces/[id]/votes.ts
  pages/api/votes/[id]/cast.ts
  pages/api/votes/[id]/index.ts
  pages/api/votes/index.ts
  prisma/migrations/20230410184050_add_post_to_votes/migration.sql
  prisma/schema.prisma
  testing/prosemirror.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#2005 Csv import as a data source
  components/common/BoardEditor/focalboard/csvExporter/csvExporter.ts
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/createLinkedView.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceType.tsx
  components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
Labels: :rocket: deploy

#2034 Typeform questions
  lib/focalboard/board.ts
  lib/pages/createFormResponseCard.ts
Labels: :rocket: deploy

#2033 Remove some focalboard styles
  components/common/BoardEditor/focalboard/src/components/calculations/calculation.scss
  components/common/BoardEditor/focalboard/src/components/calculations/calculation.tsx
  components/common/BoardEditor/focalboard/src/components/calculations/options.tsx
  components/common/BoardEditor/focalboard/src/components/calendar/fullcalendar.scss
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
  components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.scss
  components/common/BoardEditor/focalboard/src/components/kanban/calculation/calculation.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/calculation/calculationOption.scss
  components/common/BoardEditor/focalboard/src/components/kanban/calculation/calculationOptions.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/calculation/kanbanOption.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.scss
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumnHeader.tsx
  components/common/BoardEditor/focalboard/src/components/properties/createdBy/createdBy.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.scss
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.spec.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  components/common/BoardEditor/focalboard/src/components/properties/user/user.scss
  components/common/BoardEditor/focalboard/src/components/table/calculation/calculationRow.scss
  components/common/BoardEditor/focalboard/src/components/table/calculation/calculationRow.tsx
  components/common/BoardEditor/focalboard/src/components/table/calculation/tableCalculationOptions.tsx
  components/common/BoardEditor/focalboard/src/components/topBar.scss
  components/common/BoardEditor/focalboard/src/components/topBar.spec.tsx
  components/common/BoardEditor/focalboard/src/components/topBar.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.scss
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/BoardEditor/focalboard/src/i18n.tsx
  components/common/BoardEditor/focalboard/src/nativeApp.ts
  components/common/BoardEditor/focalboard/src/octoClient.ts
  components/common/BoardEditor/focalboard/src/styles/labels.scss
  components/common/BoardEditor/focalboard/src/styles/shared-variables.scss
  components/common/BoardEditor/focalboard/src/styles/variables.scss
  components/common/BoardEditor/focalboard/src/theme.ts
  components/common/BoardEditor/focalboard/src/userSettings.ts
  components/common/BoardEditor/focalboard/src/widgets/buttons/button.tsx
  components/common/BoardEditor/focalboard/src/widgets/buttons/buttonWithMenu.scss
  components/common/BoardEditor/focalboard/src/widgets/buttons/buttonWithMenu.tsx
  components/common/BoardEditor/focalboard/src/widgets/editable.scss
  components/common/BoardEditor/focalboard/src/widgets/menu/menu.scss
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationModal.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  theme/colors.ts
  theme/cssVariables.ts
  theme/focalboard/focalboard.main.scss
  theme/focalboard/focalboard.typography.scss
  theme/focalboard/theme.ts
  theme/index.ts
Labels: :rocket: deploy

#2038 Allow changing font family and size of documents
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/[pageId]/DocumentPage/components/PageTitleInput.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/DevTools.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/forum/components/PostPage/PostPage.tsx
  lib/emails/templates/components/EmailWrapper.tsx
  lib/emails/templates/theme/styles.ts
  lib/pages/interfaces.ts
  lib/pages/server/getAccessiblePages.ts
  lib/pages/server/getPageMetaList.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/socket/index.ts
  prisma/migrations/20230418060215_add_font_styles/migration.sql
  prisma/schema.prisma
  seedData/proposalTemplates.ts
  theme/@bangle.dev/styles.scss
  theme/cssVariables.ts
  theme/fonts.ts
  theme/index.ts
  theme/styles.scss
Labels: :rocket: deploy

#2035 Wrap column in database
  components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx
  components/common/BoardEditor/focalboard/src/components/properties/link/link.tsx
  components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/widgets/TextInput.tsx
  components/common/form/fields/Select/SelectPreview.tsx
  lib/focalboard/boardView.ts
  package-lock.json
Labels: :rocket: deploy

#2020 Advanced board filters
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.spec.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.scss
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.spec.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterValue.spec.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterValue.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/BoardEditor/focalboard/src/test/testBlockFactory.ts
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  lib/focalboard/__tests__/cardFilter.spec.ts
  lib/focalboard/board.ts
  lib/focalboard/cardFilter.ts
  lib/focalboard/filterClause.ts
  pages/_app.tsx
  scripts/migrations/2023_04_14_update_card_properties.ts
Labels: :rocket: deploy

#2045 set custom health check for staging
  .cdk/staging-stack.ts
Labels: :rocket: deploy

#2050 Typeform Db page - add banner and custom title
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/Banners/Banner.tsx
  components/common/Banners/PageWebhookBanner.tsx
  components/common/Banners/ProposalBanner.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  components/common/PageLayout/components/Header/components/utils/__tests__/databasePageOptions.spec.ts
  components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
  components/common/ProposalBanner.tsx
  components/forum/components/PostPage/PostPage.tsx
  config/constants.ts
Labels: :rocket: deploy

#2051 bump next.js to get native next/font library
  lib/emails/templates/components/EmailWrapper.tsx
  next.config.js
  package-lock.json
  package.json
  theme/fonts.ts
  tsconfig.json
  tsconfig.next.json
Labels: :rocket: deploy

#2052 have socket process close itself on SIGTERM
  .ebextensions_websockets/00_env_vars.config
  background/server/app.ts
  background/websockets.ts
  docker-compose.yml
  package.json
Labels: :rocket: deploy

#2058 cleanup unused docker profiles
  docker-compose.yml
  next.config.js
  package.json
  pages/_app.tsx
  ping_results.log
  theme/styles.scss
Labels: :rocket: deploy

#2063 use custom next.js server and redo docker-compose
  .ebextensions/00_env_vars.config
  .ebextensions_cron/00_env_vars.config
  .ebextensions_websockets/00_env_vars.config
  .env.staging
  .github/actions/build/action.yml
  .gitignore
  Dockerfile
  background/websockets.ts
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/forum/components/ForumFilterListLink.tsx
  docker-compose.yml
  lib/log/logLevel.ts
  next.base.js
  package.json
  ping_results.log
  server.ts
  tsconfig.server.json
Labels: :rocket: deploy

#2074 Fix create new user on disconnect wallet
  components/common/Modal/ConfirmDeleteModal.tsx
  components/common/RouteGuard.tsx
  components/integrations/components/AddWalletStep.tsx
  components/integrations/components/IdentityProviders.tsx
  components/integrations/components/NewIdentityModal.tsx
  components/login/LoginButton.tsx
  hooks/useWeb3AuthSig.tsx
Labels: :rocket: deploy

#2073 Load full page every time
  __integration-tests__/permissions/05-reposition-to-root.spec.ts
  __integration-tests__/server/pages/api/pages/[id]/index.spec.ts
  charmClient/apis/pagesApi.ts
  components/[pageId]/Comments/PageComments.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/CommentsSidebar.tsx
  components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  components/bounties/components/BountyGalleryCard.tsx
  components/bounties/components/BountyKanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.spec.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/createLinkedView.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/PageThread.tsx
  components/common/CharmEditor/components/fiduswriter/ws.ts
  components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
  components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx
  components/common/CharmEditor/components/inlinePalette/useEditorItems.ts
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/CharmEditor/components/nodeView/nodeView.ts
  components/common/CharmEditor/components/poll/PollComponent.tsx
  components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
  components/common/DuplicatePageAction.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/PageDialogGlobal.tsx
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  components/common/comments/Comment.tsx
  components/common/comments/CommentForm.tsx
  hooks/useApiPageKeys.tsx
  hooks/usePage.ts
  hooks/usePageDetails.tsx
  hooks/usePagePermissions.tsx
  hooks/usePages.tsx
  lib/metrics/mixpanel/updateTrackPageProfile.ts
  lib/pages/createNewDataSource.ts
  lib/pages/index.ts
  lib/pages/interfaces.ts
  pages/[domain]/[pageId].tsx
  pages/api/pages/[id]/index.ts
  pages/api/profile/remote.ts
  pages/api/public/pages/[...pageId]/index.ts
  theme/styles.scss
  tsconfig.json
Labels: :rocket: deploy
