Repository charmverse/app.charmverse.io, pull requests merged in 2023-02, with the labels that each got.

#1619 update Lit Protocol modal
  components/common/Modal/Modal.tsx
  components/settings/invites/components/TokenGates/TokenGates.tsx
  lit-share-modal-v3.d.ts
  next.base.js
  package-lock.json
  package.json
  pages/_app.tsx
Labels: :rocket: deploy

#1618 clear form state before redirecting after saving space url
  pages/[domain]/settings/space.tsx
Labels: bug, :rocket: deploy

#1610 Fix dropping parent page onto child in nav tree
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeRoot.tsx
  lib/pages/mapPageTree.ts
Labels: :rocket: deploy

#1617 fix error when searching for undefined profile path
  charmClient/charmClient.ts
  components/profile/components/UserPathModal.tsx
  pages/api/profile/check-path-availability.ts
Labels: bug

#1616 turn missing crypto price into a warning
  components/common/CharmEditor/components/CryptoPrice.tsx
  lib/crypto-price/dataSources/cryptoCompare.ts
  lib/crypto-price/getters.ts
  pages/api/crypto-price/index.ts
Labels: bug

#1615 improve UX of selecting an avatar
  components/profile/components/UserDetails/hooks/useUpdateProfileAvatar.ts
  components/settings/workspace/LargeAvatar.tsx
  components/settings/workspace/ProgressOverlay.tsx
  lib/deepdao/client.ts
  pages/api/profile/avatar.ts
Labels: :rocket: deploy

#1550 fix error related to reloading charmeditor
  components/common/CharmEditor/components/inlinePalette/hooks.ts
  components/common/CharmEditor/components/inlinePalette/inlinePalette.ts
Labels: work-in-progress

#1631 Fix/comment sidebar
  components/[pageId]/DocumentPage/components/CommentsSidebar.tsx
Labels: :rocket: deploy

#1621 Update mobile comments sidebar to be displayed as modal
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/CommentsSidebar.tsx
  components/common/CharmEditor/components/SidebarDrawer.tsx
  components/common/MobileDialog/MobileDialog.tsx
  components/common/Modal/Modal.tsx
  hooks/useMediaScreens.ts
  hooks/usePageActionDisplay.tsx
  lib/prosemirror/highlightMarkedElement.ts
Labels: :rocket: deploy

#1638 Prevent updates to title, header image or icon by people who dont have edit_content permission
  __integration-tests__/server/pages/api/pages/[id]/index.spec.ts
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  pages/api/pages/[id]/index.ts
Labels: :rocket: deploy

#1636 Test: uninstall ts-jest
  jest.config.ts
  package-lock.json
  package.json
  testing/createJestConfig.ts
Labels: work-in-progress

#1633 using matrix to run tests in parallel
  .github/actions/build/action.yml
  .github/actions/install/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/destroy_staging.yml
  .github/workflows/test_and_deploy.yml
  jest.config.ts
  lib/members/getSpacePropertyValues.ts
  lib/token-gates/__tests__/verifyTokenGateMembership.spec.ts
  lib/token-gates/applyTokenGates.ts
  lib/token-gates/interfaces.ts
  lib/token-gates/verifyTokenGateMembership.ts
  lit-js-sdk.d.ts
  package-lock.json
  package.json
  playwright.config.ts
  testing/createJestConfig.ts
Labels: :rocket: deploy

#1648 Add support for Odysee video
  components/common/CharmEditor/components/iframe/config.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
  components/common/CharmEditor/components/video/VideoNodeView.tsx
  lib/utilities/__tests__/strings.spec.ts
  lib/utilities/strings.ts
Labels: :rocket: deploy

#1651 Fix issue of post not being editable on initial page load
  __e2e__/forum/commentOnForumPost.spec.ts
  __e2e__/forum/editPost.spec.ts
  __e2e__/po/forumPost.po.ts
  components/forum/components/ForumVote.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/PostComment.tsx
  components/forum/hooks/usePostPermissions.ts
Labels: :rocket: deploy

#1626 feat: fix SQS call for webhook worker
  .github/workflows/deploy_serverless_prod.yml
  components/settings/api/Api.tsx
  lib/aws/SQS.ts
  lib/forums/comments/createPostComment.ts
  lib/webhook/index.ts
  package-lock.json
  serverless/webhook/worker.ts
Labels: :rocket: deploy, :rocket: serverless

#1657 Apply forum moderator permissions
  __e2e__/forum/editPost.spec.ts
  __e2e__/forum/moderationFromPostPage.spec.ts
  __e2e__/po/forumHome.po.ts
  __e2e__/po/forumPost.po.ts
  __e2e__/po/pageHeader.ts
  __integration-tests__/server/pages/api/permissions/forum/compute-post-permissions.spec.ts
  charmClient/apis/forumApi.ts
  charmClient/apis/permissionsApi.ts
  components/common/PageLayout/components/Header/Header.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostDialog/PostDialogGlobal.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/PostComment.tsx
  components/forum/hooks/usePostByPath.ts
  components/forum/hooks/usePostPermissions.ts
  lib/forums/comments/__tests__/deletePostComment.spec.ts
  lib/forums/comments/deletePostComment.ts
  lib/forums/posts/__tests__/getForumPost.spec.ts
  lib/forums/posts/getForumPost.ts
  pages/[domain]/forum/post/[pagePath].tsx
  pages/api/forums/posts/[postId]/comments/[commentId]/index.ts
  pages/api/forums/posts/[postId]/index.ts
  pages/api/permissions/forum/compute-post-permissions.ts
  prisma/migrations/20230207135633_track_post_deletedby/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1670 refine setup for emotion cache based on MUI
  pages/_app.tsx
  pages/_document.tsx
  theme/createEmotionCache.ts
Labels: :rocket: deploy

#1627 Settings modal
  __e2e__/joinWorkspace/privateLink.test.ts
  __e2e__/joinWorkspace/tokenGates/joinWorkspace.spec.ts
  __e2e__/po/nexus.po.ts
  __e2e__/po/spaceSettings.po.ts
  __e2e__/po/spacesDropdown.po.ts
  __e2e__/sessions/logout.spec.ts
  __e2e__/updateSpace.spec.ts
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx
  components/common/Modal/ConfirmDeleteModal.tsx
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/NexusLayout.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/common/PageLayout/components/Sidebar/NexusAvatar.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/SidebarBtn.tsx
  components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx
  components/common/PageLayout/components/Sidebar/Workspaces.tsx
  components/common/RouteGuard.tsx
  components/common/form/InputSearchRole.tsx
  components/integrations/IntegrationsPage.tsx
  components/integrations/components/GnosisSafes.tsx
  components/integrations/components/IdentityProviders.tsx
  components/nexus/GnosisTasksList/GnosisTasksList.tsx
  components/nexus/TasksPage.tsx
  components/nexus/components/NexusLayout.tsx
  components/nexus/components/NexusPageTitle.tsx
  components/nexus/components/NexusSidebar.tsx
  components/profile/ProfileSettings.tsx
  components/settings/Layout.tsx
  components/settings/Legend.tsx
  components/settings/api/Api.tsx
  components/settings/invites/Invites.tsx
  components/settings/invites/components/InviteLinks/components/InviteActions.tsx
  components/settings/members/MemberSettings.tsx
  components/settings/pages.tsx
  components/settings/roles/RoleSettings.tsx
  components/settings/workspace/LargeAvatar.tsx
  components/settings/workspace/Space.tsx
  hooks/useMobileSidebar.ts
  hooks/useSettingsDialog.tsx
  hooks/useSpaces.tsx
  lib/notion/generateNotionImportRedirectUrl.ts
  lib/spaces/config.ts
  next.config.js
  package-lock.json
  package.json
  pages/[domain]/index.tsx
  pages/[domain]/settings/api.tsx
  pages/[domain]/settings/invites.tsx
  pages/[domain]/settings/members.tsx
  pages/[domain]/settings/roles.tsx
  pages/_app.tsx
  pages/integrations.tsx
  pages/nexus.tsx
  pages/profile.tsx
  pages/u/[userPath].tsx
Labels: :rocket: deploy

#1681 Optimize opening cards in inline databases
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  components/bounties/components/BountiesKanbanView.tsx
  components/bounties/components/BountyCard.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/table/table.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableGroup.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/PageThread.tsx
  components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx
  components/common/CharmEditor/components/inlinePalette/useEditorItems.ts
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
  components/common/PageActions.tsx
  components/common/PageActionsMenu.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageLayout/NexusLayout.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/SharedPageLayout.tsx
  components/common/PageLayout/components/CurrentPageFavicon.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  components/common/PageLayout/components/Header/components/DocumentParticipants.tsx
  components/common/PageLayout/components/Header/components/EditingModeToggle.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/common/PageLayout/components/Header/index.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx
  components/common/PageLayout/components/TrashModal.tsx
  components/profile/components/UserDetails/UserDetails.tsx
  components/profile/components/UserDetails/hooks/useUserDetails.ts
  components/votes/components/CreateVoteModal.tsx
  hooks/useCharmEditor.tsx
  hooks/useCurrentPage.tsx
  hooks/usePageActionDisplay.tsx
  hooks/usePageFromPath.ts
  hooks/usePages.tsx
  hooks/useThreads.tsx
  hooks/useVotes.tsx
  lib/focalboard/board.ts
  lib/focalboard/card.ts
  pages/[domain]/[pageId].tsx
  pages/_app.tsx
Labels: :rocket: deploy

#1696 Fix space context
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySuggestionApproval.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/common/CharmEditor/components/markdownParser/ImportZippedMarkdown.tsx
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/NexusLayout.tsx
  components/common/PageLayout/components/Header/components/BountyShareButton/ShareBountyBoard.tsx
  components/common/PageLayout/components/Header/components/Snapshot/ConnectSnapshot.tsx
  components/common/PageLayout/components/Header/components/Snapshot/PublishingForm.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/forum/components/CategoryContextMenu.tsx
  components/forum/components/CategoryMenu.tsx
  components/members/components/AddMemberPropertyButton.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
  components/members/components/MemberDirectoryProperties/MemberPropertyVisibility.tsx
  components/proposals/components/ProposalActionsMenu.tsx
  components/proposals/hooks/useProposalCategories.ts
  components/settings/api/Api.tsx
  components/settings/invites/Invites.tsx
  components/settings/members/MemberSettings.tsx
  components/settings/roles/RoleSettings.tsx
  components/settings/roles/components/ImportDiscordRolesMenuItem.tsx
  components/settings/roles/components/SpacePermissions/SpacePermissions.tsx
  components/settings/roles/components/SpacePermissions/components/DefaultPagePermissions.tsx
  components/settings/roles/components/SpacePermissions/components/PermissionConfigurationMode.tsx
  components/settings/roles/hooks/useImportDiscordRoles.ts
  components/settings/workspace/ImportNotionWorkspace.tsx
  components/settings/workspace/Space.tsx
  components/votes/components/NewProposalButton.tsx
  hooks/useIsAdmin.ts
  hooks/usePages.tsx
  hooks/useRoles.ts
Labels: :rocket: deploy

#1691 Space wide forum moderators
  __e2e__/forum/assignSpaceWideForumModerators.spec.ts
  __e2e__/forum/commentOnForumPost.spec.ts
  __e2e__/forum/createForumCategory.spec.ts
  __e2e__/forum/editPost.spec.ts
  __e2e__/forum/moderationFromPostPage.spec.ts
  __e2e__/forum/viewVisibleForumCategory.spec.ts
  __e2e__/po/forumHome.po.ts
  __e2e__/po/forumPost.po.ts
  __e2e__/po/loggedIn.po.ts
  __e2e__/po/nexus.po.ts
  __e2e__/po/spaceSettings.po.ts
  __e2e__/po/spaceSettingsTabRoles.po.ts
  __e2e__/sessions/logout.spec.ts
  __e2e__/utils/mocks.ts
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx
  components/settings/pages.tsx
  components/settings/roles/components/RoleRow.tsx
  components/settings/roles/components/SpacePermissions/SpacePermissions.tsx
  lib/permissions/errors.ts
  lib/permissions/forum/__tests__/computePostCategoryPermissions.spec.ts
  lib/permissions/forum/__tests__/computePostPermissions.spec.ts
  lib/permissions/forum/__tests__/filterAccessiblePostCategories.spec.ts
  lib/permissions/forum/__tests__/hasSpaceWideModerateForumsPermission.spec.ts
  lib/permissions/forum/__tests__/mutatePostCategorySearch.spec.ts
  lib/permissions/forum/computePostCategoryPermissions.ts
  lib/permissions/forum/computePostPermissions.ts
  lib/permissions/forum/filterAccessiblePostCategories.ts
  lib/permissions/forum/hasSpaceWideModerateForumsPermission.ts
  lib/permissions/forum/listPostCategoryPermissions.ts
  lib/permissions/forum/mutatePostCategorySearch.ts
  lib/permissions/meta/preset-templates.ts
  lib/permissions/spaces/__tests__/addSpaceOperations.spec.ts
  lib/permissions/spaces/addSpaceOperations.ts
  lib/permissions/spaces/availableSpacePermissions.ts
  lib/permissions/spaces/mapping.ts
  prisma/migrations/20230210002427_add_moderate_forums_operation/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1675 Show mini profile when joining a space
  __e2e__/memberOnboarding.spec.ts
  __e2e__/utils/mocks.ts
  components/members/MemberOnboardingModal.tsx
  components/members/components/MemberOnboardingForm.tsx
  components/profile/components/MemberMiniProfile/BlockchainData/NftsList.tsx
  components/profile/components/MemberMiniProfile/BlockchainData/OrgsList.tsx
  components/profile/components/MemberMiniProfile/BlockchainData/PoapsList.tsx
  components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx
  components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
  components/profile/components/NftAvatarGallery/NftAvatarGalleryPopup.tsx
Labels: :rocket: deploy

#1710 Game7 updates
  .ebextensions/00_env_vars.config
  .env.example
  .github/workflows/deploy_serverless_prod.yml
  components/settings/api/Api.tsx
  components/settings/api/utils.ts
  lib/discord/upsertUserForDiscordId.ts
  lib/public-api/createWorkspaceApi.ts
  lib/public-api/interfaces.ts
  lib/spaces/createWorkspace.ts
  lib/users/createUser.ts
  lib/webhook/interfaces.ts
  lib/webhook/publisher.ts
  lib/webhook/subscribeToEvents.ts
  pages/api/spaces/[id]/set-webhook.ts
  pages/api/v1/spaces/index.ts
Labels: :rocket: deploy

#1637 Support og meta data for profiles
  pages/u/[userPath].tsx
Labels: :rocket: deploy

#1713 Format focalboard dates based on user preference locale
  components/_app/LocalizationProvider.tsx
  components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts
  components/common/BoardEditor/focalboard/csvExporter/csvExporter.ts
  components/common/BoardEditor/focalboard/src/components/calendar/fullCalendar.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/comment.tsx
  components/common/BoardEditor/focalboard/src/components/properties/createdAt/createdAt.tsx
  components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
  components/common/BoardEditor/focalboard/src/csvExporter.ts
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/BoardEditor/focalboard/src/widgets/editableDayPicker.scss
  components/common/BoardEditor/focalboard/src/widgets/editableDayPicker.tsx
  components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
  pages/_app.tsx
Labels: :rocket: deploy

#1722 Fix long property names and values
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/widgets/TextInput.tsx
  theme/focalboard/focalboard.main.scss
Labels: :rocket: deploy

#1676 Convert Forum Post to Proposal
  __e2e__/forum/convertToProposal.spec.ts
  __e2e__/po/forumPost.po.ts
  __integration-tests__/server/pages/api/forums/posts/[postId]/comments/index.spec.ts
  __integration-tests__/server/pages/api/posts/[postId]/convert-to-proposal.spec.ts
  charmClient/apis/forumApi.ts
  components/common/PageLayout/components/Header/Header.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/forum/components/PostPage/components/PostComment.tsx
  lib/forums/posts/convertPostToProposal.ts
  lib/permissions/__tests__/buildComputePermissionsWithPermissionFilteringPolicies.spec.ts
  lib/permissions/buildComputePermissionsWithPermissionFilteringPolicies.ts
  lib/permissions/forum/__tests__/computePostPermissions.spec.ts
  lib/permissions/forum/computePostPermissions.ts
  lib/proposal/__tests__/getProposal.spec.ts
  lib/proposal/createProposal.ts
  pages/api/forums/posts/[postId]/comments/[commentId]/index.ts
  pages/api/forums/posts/[postId]/convert-to-proposal.ts
  prisma/migrations/20230209132718_post_proposal_id/migration.sql
  prisma/schema.prisma
Labels: :rocket: deploy

#1720 Allow forums to be made public
  __e2e__/forum/publicForum.spec.ts
  __e2e__/utils/session.ts
  __integration-tests__/server/pages/api/forums/posts/[postId]/comments/index.spec.ts
  __integration-tests__/server/pages/api/forums/posts/[postId]/index.spec.ts
  __integration-tests__/server/pages/api/forums/posts/index.spec.ts
  __integration-tests__/server/pages/api/forums/posts/search.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/members/index.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/post-categories/index.spec.ts
  components/common/PageLayout/PageLayout.tsx
  components/forum/components/permissions/PostCategoryPermissions.tsx
  components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx
  hooks/useSharedPage.ts
  lib/members/interfaces.ts
  lib/permissions/requestOperations.ts
  lib/utilities/__tests__/randomName.spec.ts
  lib/utilities/randomName.ts
  pages/api/forums/posts/[postId]/comments/index.ts
  pages/api/forums/posts/[postId]/index.ts
  pages/api/spaces/[id]/members/index.ts
  testing/utils/forums.ts
Labels: :rocket: deploy

#1732 Return space before public space
  __e2e__/po/settings/settings.po.ts
  __e2e__/po/settings/spaceMembersSettings.po.ts
  __e2e__/settings/applyCorrectSpace.spec.ts
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/settings/members/MemberListItem.tsx
  hooks/useCurrentSpace.ts
  hooks/useSpaceWebhook.ts
Labels: :rocket: deploy

#1728 Update getting started
  scripts/updateGettingStartedPage.ts
  seedData/gettingStartedPage.ts
Labels: :rocket: deploy

#1729 Feat/show more data
  components/PageSizeInputPopup.tsx
  components/common/BoardEditor/components/kanban/KanbanGroupColumn.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/common/BoardEditor/focalboard/src/components/table/table.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx
  components/common/PopperPopup.tsx
  hooks/__tests__/usePaginatedData.spec.ts
  hooks/usePaginatedData.ts
  scripts/testWebhooks.ts
Labels: :rocket: deploy

#1743 Fixed public pages (forums & bounties)
  hooks/useSharedPage.ts
  pages/_app.tsx
Labels: :rocket: deploy

#1738 Feat/proposal UI updates
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/proposals/components/ProposalStepSummary.tsx
  components/proposals/components/ProposalStepper.tsx
  lib/proposal/canChangeProposalStatus.ts
  lib/proposal/proposalStatusTransition.ts
Labels: :rocket: deploy

#1740 Add space template
  components/common/CreateSpaceForm/SelectNewSpaceTemplate.tsx
  lib/spaces/config.ts
  lib/spaces/createWorkspace.ts
  lib/templates/exports/templateCreator.json
  lib/templates/exports/templateNftCommunity.json
  scripts/exportData/exportNewTemplate.ts
Labels: :rocket: deploy

#1751 update community template
  lib/templates/exports/templateNftCommunity.json
Labels: :rocket: deploy

#1750 support pasting markdown into CharmEditor
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/markdown/markdown.plugins.ts
  components/common/CharmEditor/components/markdownParser/files/The Singularity.ts
  components/common/CharmEditor/components/markdownParser/files/index.ts
  components/common/CharmEditor/components/markdownParser/incrementalNote.ts
  components/common/CreateSpaceForm/CreateSpaceForm.tsx
  components/common/ImportZippedMarkdown.tsx
  components/common/PageLayout/components/Header/components/Snapshot/PublishingForm.tsx
  components/common/PageLayout/components/Header/components/utils/exportMarkdown.ts
  components/settings/workspace/ImportContent.tsx
  components/settings/workspace/Space.tsx
  lib/pages/generateMarkdown.ts
  lib/pages/index.ts
  lib/prosemirror/plugins/markdown/generateMarkdown.ts
  lib/prosemirror/plugins/markdown/parseMarkdown.ts
  lib/public-api/getPageInBoard.ts
  pages/api/pages/import/[spaceId]/zipped.ts
  pages/api/v1/bounties/index.ts
  pages/api/v1/pages/[pageId].ts
  pages/api/v1/proposals/index.ts
Labels: work-in-progress, :rocket: deploy

#1761 Save some space in Settings sidebar
  components/common/Modal/SettingsDialog.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
Labels: :rocket: deploy

#1736 New UI for Profile view
  __e2e__/memberOnboarding.spec.ts
  __e2e__/po/spacesDropdown.po.ts
  __e2e__/sidebarAddNewSpace.spec.ts
  components/common/Modal/SettingsDialog.tsx
  components/common/form/fields/FieldTypeRenderer.tsx
  components/common/form/fields/FieldWrapper.tsx
  components/common/form/fields/TextInputField.tsx
  components/common/form/fields/util.tsx
  components/members/MemberDirectoryPage.tsx
  components/members/MemberOnboardingModal.tsx
  components/members/components/MemberDirectoryGalleryView.tsx
  components/members/components/MemberOnboardingForm.tsx
  components/profile/PublicProfile.tsx
  components/profile/components/CommunityRow.tsx
  components/profile/components/DescriptionModal.tsx
  components/profile/components/IdentityModal.tsx
  components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx
  components/profile/components/SocialInputs.tsx
  components/profile/components/SocialModal.tsx
  components/profile/components/SpacesMemberDetails/SpacesMemberDetails.tsx
  components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
  components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
  components/profile/components/TimezoneAutocomplete.tsx
  components/profile/components/TimezoneModal.tsx
  components/profile/components/UserDescription.tsx
  components/profile/components/UserDetails/UserDetails.tsx
  components/profile/components/UserDetails/UserDetailsMini.tsx
  components/profile/components/UserDetails/index.ts
  components/profile/components/UserDetails/utils.ts
  components/profile/components/index.ts
  lib/profile/getUserNFTs.ts
  lib/profile/updateProfileAvatar.ts
  lib/users/createUser.ts
  lib/users/prepopulateUserProfile.ts
  pages/api/nft/list/[userId].ts
  pages/api/profile/avatar.ts
  pages/api/spaces/[id]/members/index.ts
Labels: :rocket: deploy

#1764 Public page details are not visible
  __e2e__/publicBounties.spec.ts
  __e2e__/publicPage.spec.ts
  __e2e__/publicProposals.spec.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyPropertiesHeader.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx
  components/common/form/InputSearchRole.tsx
  lib/bounties/interfaces.ts
  lib/pages/interfaces.ts
  lib/votes/getVotesByPage.ts
  lib/votes/interfaces.ts
  pages/api/bounties/[id]/permissions.ts
  pages/api/pages/[id]/votes.ts
  pages/api/proposals/[id]/index.ts
  pages/api/public/pages/[...pageId]/index.ts
  pages/api/roles/index.ts
  pages/api/votes/[id]/user-votes.ts
Labels: :rocket: deploy

#1771 Deploy hotfix for AWS lib
  .github/actions/build_docker_image/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/destroy_staging.yml
  scripts/migrations/2023_02_23_migrateProposals.ts
Labels: :rocket: deploy

#1762 Access space via XPS Engine
  lib/xpsEngine/client.ts
  lib/xpsEngine/interfaces.ts
  scripts/xpsEngine.ts
Labels: work-in-progress

#1776 add hierarchy to token gate components
  __e2e__/joinWorkspace/tokenGates/joinWorkspace.spec.ts
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySignupButton.tsx
  components/common/CreateSpaceForm/CreateSpaceForm.tsx
  components/common/SpaceAccessGate/SpaceAccessGate.tsx
  components/common/SpaceAccessGate/SpaceAccessGateWithSearch.tsx
  components/common/SpaceAccessGate/components/DiscordGate/DiscordGate.tsx
  components/common/SpaceAccessGate/components/DiscordGate/hooks/useDiscordGate.ts
  components/common/SpaceAccessGate/components/TokenGate/TokenGate.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateContent.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateOption.tsx
  components/common/SpaceAccessGate/components/TokenGate/VerifyCheckmark.tsx
  components/common/TokenGateForm/index.ts
  components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
  pages/join.tsx
Labels: :rocket: deploy
