Repository charmverse/app.charmverse.io, pull requests merged in 2023-11, with the labels that each got.

#3032 Fixed links with apostrophes when pasting
  components/common/CharmEditor/components/@bangle.dev/base-components/link.ts
  components/common/CharmEditor/components/link/link.plugins.ts
Labels: :rocket: deploy

#2815 Update next.js to 14
  .env.test.local.example
  .github/workflows/deploy_staging.yml
  __e2e__/database/databaseProposalsAsSource.spec.ts
  __e2e__/po/proposalsList.po.ts
  adapters/postgres/postgresClient.ts
  adapters/redis/redisClient.ts
  components/[pageId]/Comments/usePageComments.ts
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  jest.config.nodejs.ts
  lib/websockets/broadcaster.ts
  next.config.js
  package.json
  pages/invite/page.tsx
  pages/invite/page/index.tsx
Labels: :rocket: deploy

#3037 Fixed forum category rename issue
  components/forum/components/CategoryContextMenu.tsx
  components/forum/components/EditCategoryDialog.tsx
  pages/api/spaces/[id]/post-categories/[postCategoryId]/index.ts
Labels: :rocket: deploy

#3038 Revert "Revert nextjs 14 upgrade (#3036)"
  .env.test.local.example
  .github/workflows/deploy_staging.yml
  __e2e__/database/databaseProposalsAsSource.spec.ts
  __e2e__/po/proposalsList.po.ts
  adapters/postgres/postgresClient.ts
  adapters/redis/redisClient.ts
  components/[pageId]/Comments/usePageComments.ts
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  jest.config.nodejs.ts
  lib/websockets/broadcaster.ts
  next.config.js
  package.json
  pages/invite/page.tsx
  pages/invite/page/index.tsx
Labels: :rocket: deploy

#3042 Drag and drop pages inside linked card pages
  components/common/CharmEditor/components/nestedPage/nestedPage.plugins.ts
  components/common/CharmEditor/components/prosemirror/prosemirror-dropcursor/dropcursor.ts
Labels: :rocket: deploy

#3047 Fix invite code page
  components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
  components/invite/SpaceInviteLink.tsx
  components/proposals/ProposalsPage.tsx
  components/proposals/ProposalsPageWithProviders.tsx
  components/proposals/components/NewProposalButton.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalDialog/ProposalDialog.tsx
  components/proposals/components/ProposalDialog/ProposalDialogGlobal.tsx
  components/proposals/components/ProposalDialog/hooks/useNewProposal.tsx
  components/proposals/components/ProposalDialog/hooks/useProposalDialog.tsx
  lib/invites/getInviteLink.ts
  lib/invites/validateInviteLink.ts
  pages/[domain]/proposals/index.tsx
  pages/invite/[inviteCode].tsx
  stories/ProposalsPage/Proposals.stories.tsx
  stories/ProposalsPage/ProposalsPageStory.tsx
Labels: :rocket: deploy

#3023 Reward application flow updates
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/ExpandableSection.tsx
  components/common/ExpandableSectionTitle.tsx
  components/common/PageDialog/PageDialog.tsx
  components/proposals/components/ProposalsBoard/utils/boardData.ts
  components/rewards/RewardsPage.tsx
  components/rewards/components/RewardApplicationDialog.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplications/NewWorkButton.tsx
  components/rewards/components/RewardApplications/RewardApplicantTableRow.tsx
  components/rewards/components/RewardApplications/RewardApplicationFilter.tsx
  components/rewards/components/RewardApplications/RewardApplications.tsx
  components/rewards/components/RewardApplications/RewardSubmissionsTable.tsx
  components/rewards/components/RewardProperties/RewardProperties.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  components/rewards/components/RewardProperties/components/RewardPropertiesHeader.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  components/rewards/components/RewardsBoard/utils/boardData.ts
  components/rewards/hooks/useApplication.tsx
  components/rewards/hooks/useApplicationDialog.tsx
  components/rewards/hooks/useNewApplication.ts
Labels: :rocket: deploy

#3046 dont save proposal templates immediately
  __integration-tests__/server/pages/api/pages/[id]/index.spec.ts
  __integration-tests__/server/pages/api/proposals/index.spec.ts
  __integration-tests__/server/pages/api/proposals/templates/[id].spec.ts
  __integration-tests__/server/pages/api/proposals/templates/index.spec.ts
  charmClient/apis/proposalsApi.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/proposals/components/NewProposalButton.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalDialog/hooks/useNewProposal.tsx
  components/proposals/components/ProposalProperties/ProposalProperties.tsx
  lib/proposal/createProposal.ts
  lib/templates/proposals/__tests__/createProposalTemplate.spec.ts
  lib/templates/proposals/createProposalTemplate.ts
  lib/webhookPublisher/publisher.ts
  pages/api/proposals/index.ts
  pages/api/proposals/templates/index.ts
  stories/ProposalsPage/Proposals.stories.tsx
Labels: :rocket: deploy

#3049 fix usage of router.push to not affect custom domains
  __e2e__/forum/moderationFromPostPage.spec.ts
  __e2e__/utils/mocks.ts
  components/[pageId]/DatabasePage/DatabasePage.tsx
  components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  components/bounties/components/NewBountyButton.tsx
  components/bounties/hooks/useOnBountyCardClose.ts
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/DuplicatePageAction.tsx
  components/common/PageActions/components/ForumPostActionList.tsx
  components/common/PageLayout/components/AddNewCard.tsx
  components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/TrashModal.tsx
  components/forum/ForumFeedPage.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  connectors/config.ts
  hooks/useCharmRouter.ts
  lib/pages/addPage.ts
  pages/authenticate/index.tsx
  pages/join.tsx
  testing/utils/forums.ts
Labels: :rocket: deploy

#3050 Mention roles, admin and everyone in editor
  .husky/pre-commit
  components/common/CharmEditor/components/mention/components/Mention.tsx
  components/common/CharmEditor/components/mention/components/MentionSuggest.tsx
  components/common/CharmEditor/components/mention/mention.specs.ts
  lib/notifications/documents/__tests__/createDocumentNotifications.spec.ts
  lib/notifications/documents/createDocumentNotifications.ts
  lib/notifications/getNotificationMetadata.tsx
  lib/prosemirror/__tests__/extractMentions.spec.ts
  lib/prosemirror/extractMentions.ts
  lib/websockets/documentEvents/documentEvents.ts
Labels: :rocket: deploy, :rocket: serverless

#3058 Fixed page icon/emoji offset
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/common/BoardEditor/focalboard/src/components/__snapshots__/centerPanel.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/gallery/__snapshots__/galleryCard.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/kanban/__snapshots__/kanban.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/kanban/__snapshots__/kanbanCard.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap
  components/common/Emoji.tsx
Labels: :rocket: deploy

#3055 Allow drag and drop images into editor
  components/common/CharmEditor/components/@bangle.dev/base-components/image.ts
  components/common/CharmEditor/plugins.ts
  patches/prosemirror-utils+1.0.0-0.patch
Labels: :rocket: deploy

#3069 Include card property metadata for `person_assigned` notification
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
  lib/mailer/emails/emails.ts
  lib/mailer/emails/templates/NotificationTemplate.tsx
  lib/mailer/emails/templates/components/Avatar.tsx
  lib/notifications/cards/getCardNotifications.ts
  lib/notifications/documents/getDocumentNotifications.ts
  lib/notifications/getNotificationMetadata.tsx
  lib/notifications/interfaces.ts
  lib/notifications/mailer/sendNotificationEmail.ts
  pages/api/email-templates/user-notifications.ts
  public/images/person.png
  stories/Emails/PendingNotificationTemplate.stories.tsx
  stories/Notifications/Notifications.stories.tsx
Labels: :rocket: deploy

#3076 Rewards ux
  __e2e__/proposals/proposalFlow.spec.ts
  charmClient/hooks/rewards.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/ExpandableSection.tsx
  components/common/PageDialog/components/NewDocumentPage.tsx
  components/common/PageLayout/components/DatabasePageContent.tsx
  components/common/comments/CommentForm.tsx
  components/common/form/InputSearchBlockchain.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalDialog/ProposalDialog.tsx
  components/proposals/components/ProposalDialog/hooks/useNewProposal.tsx
  components/proposals/components/ProposalProperties/ProposalProperties.tsx
  components/rewards/components/NewRewardButton.tsx
  components/rewards/components/RewardApplicationDialog.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplicationPage/RewardSubmissionInput.tsx
  components/rewards/components/RewardApplicationPage/components/AcceptOrRejectButtons.tsx
  components/rewards/components/RewardApplicationPage/components/ApplicationComments.tsx
  components/rewards/components/RewardApplicationPage/components/RewardApplicationInput.tsx
  components/rewards/components/RewardApplicationPage/components/RewardPaymentButton.tsx
  components/rewards/components/RewardApplicationPage/components/RewardReviewerActions.tsx
  components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
  components/rewards/components/RewardApplicationStatusChip.tsx
  components/rewards/components/RewardApplications/RewardApplications.tsx
  components/rewards/components/RewardChip.tsx
  components/rewards/components/RewardProperties/RewardProperties.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  components/rewards/components/RewardProperties/components/RewardPropertiesHeader.tsx
  components/rewards/components/RewardProperties/components/RewardTokenProperty.tsx
  components/rewards/components/RewardProperties/components/RewardTokenSelect.tsx
  components/rewards/components/RewardStatusBadge.tsx
  components/rewards/hooks/useNewReward.tsx
  components/rewards/hooks/useRewards.tsx
  lib/prosemirror/conversions/convertOldListNodes.ts
  lib/rewards/getRewardTemplates.ts
  pages/[domain]/rewards/applications/[applicationId].tsx
  pages/api/proposals/index.ts
  pages/api/rewards/[id]/permissions.ts
  stories/Rewards/Elements/RewardStatusChip.stories.tsx
Labels: :rocket: deploy

#3089 Disable sending multiple notifications for same event
  lib/forums/categories/getPostCategoriesUsersRecord.ts
  lib/notifications/documents/__tests__/createDocumentNotifications.spec.ts
  lib/notifications/documents/createDocumentNotifications.ts
  lib/notifications/forum/createForumNotifications.ts
  lib/notifications/polls/__tests__/createPollNotifications.spec.ts
  lib/notifications/polls/createPollNotifications.ts
  lib/notifications/polls/getPollNotifications.ts
  lib/notifications/proposals/createProposalNotifications.ts
  lib/notifications/rewards/createRewardNotifications.ts
  lib/notifications/saveNotification.ts
Labels: :rocket: deploy

#3088 Improved ux for uploading images via dnd
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/base-components/image.ts
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/ResizableImage.tsx
  components/forum/components/PostPage/PostPage.tsx
Labels: :rocket: deploy

#3071 Humanize LIT protocol conditions
  charmClient/apis/spacesApi.ts
  charmClient/hooks/spaces.ts
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountySignupButton.tsx
  components/common/LitProtocolModal/reusableComponents/litChainSelector/LitChainSelector.jsx
  components/common/LitProtocolModal/shareModal/helpers/multipleConditionHelpers.js
  components/common/SpaceAccessGate/components/TokenGate/TokenGate.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateConditions.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateContent.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateOption.tsx
  components/rewards/components/RewardProperties/components/RewardSignupButton.tsx
  components/settings/invites/components/TokenGates/TokenGates.tsx
  components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
  hooks/useSharedPage.ts
  lib/blockchain/getNFTs.ts
  lib/blockchain/provider/alchemy/client.ts
  lib/blockchain/updateTokenGateDetails.ts
  lib/spaces/getSpaceWithTokenGates.ts
  lib/spaces/getSpacesByName.ts
  lib/tokenGates/__tests__/humanizeConditions.spec.ts
  lib/tokenGates/applyTokenGates.ts
  lib/tokenGates/evaluateEligibility.ts
  lib/tokenGates/humanizeConditions.ts
  lib/tokenGates/interfaces.ts
  lib/tokenGates/verifyTokenGates.ts
  pages/api/spaces/search-domain.ts
  pages/api/token-gates/index.ts
  pages/join.tsx
  stories/Common/TokenGate.stories.tsx
  stories/lib/mockData.ts
  stories/lib/mockTokenGataData.ts
  testing/mocks/tokenGate.ts
Labels: :rocket: deploy

#3091 Fix adding video node inside page/post comments
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/video/VideoNodeView.tsx
  components/common/CharmEditor/plugins.ts
  components/common/comments/Comment.tsx
  components/common/comments/CommentForm.tsx
  components/common/comments/CommentReply.tsx
  components/votes/components/CreateVoteModal.tsx
Labels: :rocket: deploy

#3103 Replace cardDialog with PageDialog, and address local page context for dialogs on rewards page and inline DBs
  .storybook/preview.tsx
  components/[pageId]/DatabasePage/DatabasePage.tsx
  components/common/BoardEditor/focalboard/src/components/cardDialog.scss
  components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/PageDialog/PageDialog.tsx
  pages/_app.tsx
Labels: :rocket: deploy

#3077 Release rewards! 🚢 🏆
  __e2e__/bounties/createBountyComments.spec.ts
  __e2e__/bounties/createEditBounty.spec.ts
  __e2e__/bounties/publicBounties.spec.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/AddBountyButton/AddBountyAction.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
  components/common/PageLayout/components/PageIcon.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/utils/staticPages.ts
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/NewInlineReward.tsx
  components/rewards/components/RewardApplicationDialog.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplicationPage/components/RewardPaymentButton.tsx
  components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
  components/rewards/components/RewardProperties/components/RewardTokenProperty.tsx
  components/rewards/components/RewardStatusBadge.tsx
  components/rewards/hooks/useApplicationDialog.tsx
  components/rewards/hooks/useNewReward.tsx
  components/rewards/hooks/useRewards.tsx
  lib/notifications/getNotificationMetadata.tsx
  next.config.js
  pages/_app.tsx
  pages/api/rewards/[id]/index.ts
Labels: :rocket: deploy, :rocket: serverless

#3108 allow admins and reviewers to change evaluation type
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalProperties/components/ProposalEvaluationTypeSelect.tsx
  components/proposals/hooks/useProposalTemplates.tsx
Labels: :rocket: deploy

#3106 Switching content in page dialog +query based navigation
  components/[pageId]/EditorPage/EditorPage.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/PageDialogGlobal.tsx
  components/common/PageDialog/hooks/usePageDialog.tsx
  components/common/PageLayout/PageLayout.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/RewardApplicationDialog.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplications/NewWorkButton.tsx
  components/rewards/components/RewardApplications/RewardApplications.tsx
  components/rewards/components/RewardApplications/RewardSubmissionsTable.tsx
  components/rewards/hooks/useApplicationDialog.tsx
  components/rewards/hooks/useRewardsNavigation.ts
  hooks/useCharmRouter.ts
  pages/_app.tsx
Labels: :rocket: deploy

#3114 When pasting a link to a page in CV, convert it to a page mention
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/CharmEditor/components/link/link.plugins.ts
  components/common/CharmEditor/components/link/link.ts
  components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
Labels: :rocket: deploy

#3122 "Open page in" option for database views
  components/[pageId]/DatabasePage/DatabasePage.tsx
  components/common/BoardEditor/components/kanban/KanbanGroupColumn.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.spec.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/createLinkedView.tsx
  components/common/BoardEditor/focalboard/src/components/gallery/gallery.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumnHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/table.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableGroup.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableGroupHeaderRow.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewLayoutOptions.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/Menu.tsx
  components/common/PageDialog/PageDialog.tsx
  components/proposals/ProposalsPage.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/components/RewardsBoard/utils/boardData.ts
  lib/focalboard/boardView.ts
  pages/api/blocks/index.ts
Labels: :rocket: deploy

#3133 Show card properties during template creation
  components/[pageId]/DocumentPage/DocumentPage.tsx
Labels: :rocket: deploy

#3145 Fix opening evaluation sidebar
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/components/Sidebar/components/CommentsSidebar.tsx
  components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/ProposalSidebar.tsx
  components/[pageId]/DocumentPage/hooks/useLastSidebarView.ts
  components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageLayout/components/Header/components/ToggleEvaluationButton.tsx
  hooks/usePageSidebar.tsx
  testing/customRender.tsx
Labels: :rocket: deploy

#3143 Select and update proposal category color
  components/common/form/ColorSelectMenu.tsx
  components/common/form/fields/Select/SelectOptionEdit.tsx
  components/proposals/components/ProposalCategoriesList.tsx
  components/proposals/components/ProposalViewOptions/components/ProposalCategoryContextMenu.tsx
Labels: :rocket: deploy

#3142 Feat/local sort filter
  charmClient/charmClient.ts
  components/common/BoardEditor/components/ViewFilterControl.tsx
  components/common/BoardEditor/components/ViewSettingsRow.tsx
  components/common/BoardEditor/components/ViewSortControl.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/proposals/ProposalsPage.tsx
  components/proposals/ProposalsPageWithProviders.tsx
  components/proposals/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/hooks/useProposalsBoard.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  components/rewards/hooks/useRewardsBoard.tsx
  hooks/useLocalDbViewSettings.ts
  hooks/useLocalDbViewSettings.tsx
  hooks/useViewFilter.ts
  hooks/useViewSortOptions.ts
  pages/api/reward-applications/mark-paid.ts
  pages/api/reward-applications/review.ts
  pages/api/reward-applications/work.ts
  pages/api/rewards/[id]/close.ts
Labels: :rocket: deploy

#3138 Show view header with 0 proposal/rewards
  components/proposals/ProposalsPage.tsx
  components/rewards/RewardsPage.tsx
Labels: :rocket: deploy

#3147 tweaks to Evaluation copy
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/ProposalSidebar.tsx
  components/proposals/components/ProposalProperties/ProposalPropertiesBase.tsx
Labels: :rocket: deploy

#3146 add reward token information to rewards table
  charmClient/charmClient.ts
  charmClient/hooks/spaces.ts
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/common/BoardEditor/focalboard/src/components/properties/tokenAmount/tokenAmount.tsx
  components/common/BoardEditor/focalboard/src/components/properties/tokenChain/tokenChain.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewGroupOptions.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewPropertyOptions.tsx
  components/common/BoardEditor/focalboard/src/octoUtils.tsx
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/BoardEditor/focalboard/src/widgets/iconForPropertyType.tsx
  components/common/BoardEditor/focalboard/src/widgets/propertyTypes.tsx
  components/common/form/CustomERCTokenForm.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  components/rewards/components/RewardsBoard/utils/boardData.ts
  hooks/usePaymentMethods.tsx
  lib/focalboard/board.ts
  lib/focalboard/cardFilter.ts
  lib/focalboard/filterClause.ts
  lib/focalboard/rewardDbProperties.ts
  lib/rewards/blocks/constants.ts
Labels: :rocket: deploy

#3151 Cleanup custom boards blocks
  charmClient/hooks/proposals.ts
  charmClient/hooks/rewards.ts
  components/proposals/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/components/ProposalProperties/proposalsMutator.ts
  components/proposals/components/ProposalsBoard/utils/boardData.ts
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  components/rewards/components/RewardProperties/rewardsMutator.ts
  components/rewards/components/RewardsBoard/utils/boardData.ts
  hooks/useProposalBlocks.tsx
  hooks/useRewardBlocks.tsx
  lib/focalboard/customBlocks/constants.ts
  lib/focalboard/customBlocks/getUpsertBlockInput.ts
  lib/proposal/blocks/__tests__/updateBlock.spec.ts
  lib/proposal/blocks/__tests__/upsertBlock.spec.ts
  lib/proposal/blocks/__tests__/upsertBlocks.spec.ts
  lib/proposal/blocks/createBlock.ts
  lib/proposal/blocks/createBlocks.ts
  lib/proposal/blocks/interfaces.ts
  lib/proposal/blocks/updateBlock.ts
  lib/proposal/blocks/upsertBlock.ts
  lib/proposal/blocks/upsertBlocks.ts
  lib/rewards/blocks/__tests__/createBlock.spec.ts
  lib/rewards/blocks/__tests__/upsertBlock.spec.ts
  lib/rewards/blocks/__tests__/upsertBlocks.spec.ts
  lib/rewards/blocks/createBlock.ts
  lib/rewards/blocks/createBlocks.ts
  lib/rewards/blocks/interfaces.ts
  lib/rewards/blocks/updateBlock.ts
  lib/rewards/blocks/upsertBlock.ts
  lib/rewards/blocks/upsertBlocks.ts
  pages/api/spaces/[id]/proposals/blocks/index.ts
  pages/api/spaces/[id]/rewards/blocks/index.ts
  scripts/migrations/2023_11_22_migrateCustomBoardsBlocks.ts
Labels: work-in-progress

#3161 Fixed showing current user's lens profile in others profile
  charmClient/apis/publicProfileApi.ts
  components/members/components/MemberProfile/components/ProfileWidgets/ProfileWidgets.tsx
  components/members/components/MemberProfile/components/ProfileWidgets/components/LensProfileWidget.tsx
  components/settings/account/hooks/useLensProfile.ts
  lib/lens/fetchLensPostComments.ts
  lib/lens/fetchLensProfile.ts
  lib/pages/__tests__/comments/syncPageCommentsWithLensPost.spec.ts
  lib/pages/comments/syncPageCommentsWithLensPost.ts
  pages/api/public/profile/[userId]/lens.ts
Labels: :rocket: deploy

#3163 Fixed issue with custom reward submission
  components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
Labels: :rocket: deploy

#3136 Fixed text filter for title property
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/components/ViewFilterControl.tsx
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/BoardEditor/focalboard/src/store/cards.ts
  components/common/BoardEditor/focalboard/src/store/databaseBlocksLoad.ts
  components/common/BoardEditor/focalboard/src/svg/dashboard-onboarding.tsx
  components/common/BoardEditor/focalboard/src/svg/search-illustration.tsx
  components/common/PageActions/components/DatabasePageActionList.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
  components/proposals/ProposalsPage.tsx
  components/proposals/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/rewards/RewardsPage.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  hooks/usePages.tsx
  lib/focalboard/__tests__/cardFilter.spec.ts
  lib/focalboard/cardFilter.ts
  lib/proposal/blocks/interfaces.ts
  lib/utilities/file.ts
  pages/_app.tsx
Labels: :rocket: deploy

#3176 Misc updates to public rewards and proposals view option
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewLayoutOptions.tsx
  components/common/Menu.tsx
  components/proposals/ProposalsPage.tsx
  components/proposals/components/ProposalCategoriesList.tsx
  components/proposals/components/ProposalViewOptions/components/ProposalCategoryContextMenu.tsx
  components/rewards/components/NewRewardButton.tsx
Labels: :rocket: deploy

#3168 Consistent user display avatar and username
  components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/RubricResults.tsx
  components/common/BaseLayout/components/Header.tsx
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/common/BoardEditor/components/properties/UserSelect.tsx
  components/common/BoardEditor/focalboard/src/components/properties/createdBy/createdBy.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/CharmEditor/components/mention/components/MentionSuggest.tsx
  components/common/CharmEditor/components/suggestions/SuggestionCard.tsx
  components/common/CharmEditor/components/thread/PageThread.tsx
  components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
  components/common/UserDisplay.tsx
  components/common/comments/Comment.tsx
  components/common/comments/CommentForm.tsx
  components/common/comments/CommentReply.tsx
  components/common/form/InputSearchMember.tsx
  components/forum/components/CreateForumPost.tsx
  components/forum/components/PostList/components/PostCard.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplications/RewardApplicantTableRow.tsx
Labels: :rocket: deploy

#3189 fix events not being able to be dragged on inline calendars
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  hooks/useCharmRouter.ts
Labels: :rocket: deploy

#3191 Fix data migration
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderDisplayByMenu.tsx
  components/rewards/RewardsPage.tsx
  hooks/useProposalBlocks.tsx
  hooks/useRewardBlocks.tsx
  lib/proposal/blocks/interfaces.ts
  lib/rewards/blocks/interfaces.ts
  lib/rewards/blocks/upsertDefaultRewardsBoard.ts
  lib/rewards/blocks/views.ts
  scripts/migrations/2023_11_22_migrateCustomBoardsBlocks.ts
Labels: :rocket: deploy

#3209 Rewards link
  components/common/PageDialog/PageDialog.tsx
  components/rewards/components/RewardStatusBadge.tsx
Labels: :rocket: deploy
