Repository charmverse/app.charmverse.io, pull requests merged in 2023-10, with the labels that each got.

#2860 changed github action to only update the function as part of the deploy
  .github/workflows/deploy_serverless_prod.yml
  .github/workflows/deploy_serverless_staging.yml
  serverless/webhook/worker.ts
Labels: :rocket: serverless

#2861 changing serverless github action to use cache from main
  .github/workflows/deploy_serverless_prod.yml
  .github/workflows/deploy_serverless_staging.yml
  serverless/webhook/worker.ts
Labels: :rocket: serverless

#2863 fix markdown parse and export of new lists
  components/common/CharmEditor/components/bulletList.ts
  components/common/CharmEditor/components/listItem/listItem.component.ts
  components/common/CharmEditor/components/listItemNew/bulletListSpecs.ts
  components/common/CharmEditor/components/listItemNew/listItemSpecs.ts
  components/common/CharmEditor/components/listItemNew/orderedListSpecs.ts
  components/common/CharmEditor/components/listItemNew/splitListItem.ts
  components/common/CharmEditor/components/orderedList.ts
  components/common/CharmEditor/plugins.ts
  lib/notion/NotionImporter/NotionBlock.ts
  lib/prosemirror/__tests__/applyStepsToNode.spec.ts
  lib/prosemirror/interfaces.ts
  lib/prosemirror/plugins/markdown/__tests__/generateMarkdown.spec.ts
  lib/prosemirror/plugins/markdown/__tests__/parseMarkdown.spec.ts
  lib/prosemirror/plugins/markdown/parseMarkdown.ts
Labels: :rocket: deploy

#2872 Patch Metamask connector
  hooks/useWeb3Account.tsx
Labels: :rocket: deploy

#2866 Feat/reward properties
  .eslintrc.json
  charmClient/hooks/rewards.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/components/properties/TextInput.tsx
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/common/BoardEditor/focalboard/src/widgets/switch.tsx
  components/common/form/InputSearchCrypto.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/NewRewardButton.tsx
  components/rewards/components/RewardProperties/RewardProperties.tsx
  components/rewards/components/RewardProperties/components/RewardPropertiesHeader.tsx
  components/rewards/components/RewardProperties/components/RewardTokenProperty.tsx
  components/rewards/components/RewardProperties/components/RewardTokenSelect.tsx
  components/rewards/components/RewardProperties/components/RewardTypeSelect.tsx
  components/rewards/components/RewardProperties/interfaces.ts
  components/rewards/components/RewardStatusBadge.tsx
  components/rewards/hooks/useRewards.tsx
  lib/rewards/blocks/__tests__/updateBlock.spec.ts
  lib/rewards/blocks/createBlock.ts
  lib/rewards/blocks/deleteBlock.ts
  lib/rewards/blocks/getBlocks.ts
  lib/rewards/blocks/updateBlock.ts
  lib/rewards/blocks/updateBlocks.ts
  lib/rewards/setRewardUsers.ts
  pages/api/applications/index.ts
Labels: :rocket: deploy

#2883 Reward custom properties
  charmClient/apis/rewardsApi.ts
  components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantStatus.tsx
  components/common/BoardEditor/components/properties/PropertyLabel.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/proposals/components/ProposalProperties/ProposalProperties.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardApplicationPage/RewardSubmissionInput.tsx
  components/rewards/components/RewardProperties/CustomPropertiesAdapter.tsx
  components/rewards/components/RewardProperties/RewardProperties.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantForm/RewardApplicantForm.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantForm/components/ApplicationInput.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantForm/components/SubmissionInput.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantForm/index.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantsTable/RewardApplicantTableRow.tsx
  components/rewards/components/RewardProperties/components/RewardApplicantsTable/RewardApplicantsTable.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  components/rewards/hooks/useRewards.tsx
Labels: :rocket: deploy

#2893 Add upgrade to community flows
  __integration-tests__/server/pages/api/spaces/[id]/switch-to-community-tier.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/switch-to-free-tier.spec.ts
  charmClient/apis/subscriptionApi.ts
  components/settings/subscription/CreateSubscriptionInformation.tsx
  lib/subscription/__tests__/updateToCommunityTier.spec.ts
  lib/subscription/__tests__/updateToFreeTier.spec.ts
  lib/subscription/updateToCommunityTier.ts
  lib/subscription/updateToFreeTier.ts
  pages/api/spaces/[id]/switch-to-community-tier.ts
Labels: :rocket: deploy

#2891 Ux proposal connect
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/OpenWalletSelectorButton.tsx
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  components/common/CharmEditor/components/inlineVote/components/SnapshotVoteDetails.tsx
  components/common/PageActions/components/SnapshotAction/PublishingForm.tsx
  components/proposals/components/SnapshotVoting/hooks/useSnapshotVoting.ts
Labels: :rocket: deploy

#2894 Notion based notifications
  .storybook/mockApi.ts
  background/tasks/sendNotifications/sendNotifications.ts
  charmClient/apis/notificationsApi.ts
  charmClient/apis/tasksApi.ts
  charmClient/charmClient.ts
  components/common/MultiTabs.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationButton.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationModal.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationPreview.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationPreviewPopover.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/NotificationsBadge.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/useNotificationModal.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/useNotifications.tsx
  components/common/PageLayout/components/Header/components/NotificationPreview/utils.ts
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
  components/nexus/components/SnoozeButton.tsx
  components/nexus/hooks/useTasks.ts
  components/nexus/hooks/useTasksState.ts
  components/rewards/components/RewardChip.tsx
  hooks/useVotes.tsx
  lib/mailer/emails/emails.ts
  lib/mailer/emails/templates/PendingTasksTemplate.tsx
  lib/notifications/getBountyNotifications.ts
  lib/notifications/getCardNotifications.ts
  lib/notifications/getDiscussionNotifications.ts
  lib/notifications/getDocumentNotifications.ts
  lib/notifications/getForumNotifications.ts
  lib/notifications/getNotificationMetadata.ts
  lib/notifications/getPostNotifications.ts
  lib/notifications/getProposalNotifications.ts
  lib/notifications/getVoteNotifications.ts
  lib/notifications/interfaces.ts
  lib/notifications/markNotifications.ts
  lib/notifications/utils.ts
  lib/rewards/getRewardAction.ts
  lib/rewards/getRewardTasks.ts
  lib/userNotifications/markTasks.ts
  lib/votes/__tests__/getVoteTasks.spec.ts
  lib/votes/getVoteTasks.ts
  package.json
  pages/_app.tsx
  pages/api/email-templates/user-tasks.ts
  pages/api/notifications/list.ts
  pages/api/notifications/mark.ts
  pages/api/notifications/state.ts
  pages/api/tasks/list.ts
  pages/api/tasks/mark.ts
  pages/api/tasks/state.ts
  stories/lib/mockData.ts
Labels: :rocket: deploy

#2909 Fixed issue with mobile page icon selection
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/common/BoardEditor/focalboard/src/widgets/emojiPicker.scss
Labels: :rocket: deploy

#2916 more fixes for hover on iOS
  components/common/CharmEditor/CharmEditor.tsx
  components/common/Grid/GridContainer.tsx
  components/common/Grid/GridHeader.tsx
  components/common/Grid/GridHeaderColumn.tsx
  components/common/PageLayout/components/NewPageMenu.tsx
  components/common/PageLayout/components/PageNavigation/components/NavIconHover.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/PageNavigation/components/TreeItemContent.tsx
  components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
  components/common/TreeItemContent.tsx
  components/nexus/components/NexusTable.tsx
Labels: :rocket: deploy

#2915 Sticky page dialog header
  .storybook/main.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/AlertContainer.tsx
  components/[pageId]/DocumentPage/components/ProposalBanner.tsx
  components/[pageId]/EditorPage/EditorPage.tsx
  components/[pageId]/SharedPage/SharedPage.tsx
  components/bounties/components/NewBountyButton.tsx
  components/common/Banners/Alert.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.scss
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/common/CharmEditor/components/SidebarDrawer.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/PageDialogGlobal.tsx
  components/common/PageDialog/hooks/usePageDialog.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Header/components/DocumentHeaderElements.tsx
  components/common/PageLayout/components/Header/components/EditingModeToggle.tsx
  components/common/PageLayout/components/Header/components/ShareButton/ShareButton.tsx
  components/common/PageLayout/components/Header/components/ShareButton/index.tsx
  components/common/PageLayout/components/PageContent.tsx
  components/forum/components/PostDialog/PostDialog.tsx
  components/forum/components/PostPage/PostPage.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalDialog/ProposalDialog.tsx
  components/rewards/components/RewardApplicationDialog.tsx
  components/rewards/components/RewardApplicationPage/NewApplication.tsx
  components/settings/account/components/AccountPreferences.tsx
  hooks/useCharmEditor.tsx
  stories/ProposalsPage/Proposals.stories.tsx
Labels: :rocket: deploy

#2919 Fixed page header controls for board pages
  .storybook/preview.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/common/BoardEditor/focalboard/src/components/__snapshots__/viewTitle.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/blockIconSelector.scss
  components/common/BoardEditor/focalboard/src/components/blockIconSelector.tsx
  components/common/BoardEditor/focalboard/src/components/viewTitle.scss
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/common/BoardEditor/focalboard/src/widgets/emojiPicker.tsx
  components/common/CustomEmojiPicker.tsx
  components/common/MultiTabs.tsx
  pages/_app.tsx
Labels: :rocket: deploy

#2920 adding script to pull secrets from aws
  .ebstalk.apps.env/serverless.env
  .github/workflows/deploy_serverless_prod.yml
  .github/workflows/deploy_serverless_staging.yml
  serverless.yml
Labels: :rocket: serverless

#2928 Send email notifications in realtime with webhooks
  .ebstalk.apps.env/cron.env
  .ebstalk.apps.env/serverless.env
  .env.test.local.example
  .github/workflows/deploy_serverless_staging.yml
  .github/workflows/test_and_deploy.yml
  .gitignore
  .husky/pre-commit
  .vscode/settings.json
  __serverless-tests__/sqsWorker.spec.ts
  __serverless-tests__/webhookChecker.spec.ts
  background/cron.ts
  background/tasks/sendNotifications/__tests__/sendUserNotifications.spec.ts
  background/tasks/sendNotifications/index.ts
  background/tasks/sendNotifications/sendNotifications.ts
  background/tasks/sendNotifications/task.ts
  copyPrismaFiles.js
  jest.config.serverless.ts
  lib/mailer/emails/templates/PendingNotificationsTemplate.tsx
  lib/notifications/cards/createCardNotifications.ts
  lib/notifications/cards/getCardNotifications.ts
  lib/notifications/constants.ts
  lib/notifications/createNotificationsFromEvent.ts
  lib/notifications/documents/createDocumentNotifications.ts
  lib/notifications/documents/getDocumentNotifications.ts
  lib/notifications/forum/createForumNotifications.ts
  lib/notifications/forum/getForumNotifications.ts
  lib/notifications/interfaces.ts
  lib/notifications/mailer/__tests__/sendNotificationEmail.spec.ts
  lib/notifications/mailer/sendNotifications.ts
  lib/notifications/polls/createPollNotifications.ts
  lib/notifications/polls/getPollNotifications.ts
  lib/notifications/proposals/createProposalNotifications.ts
  lib/notifications/proposals/getProposalNotifications.ts
  lib/notifications/rewards/createRewardNotifications.ts
  lib/notifications/rewards/getRewardNotifications.ts
  lib/notifications/saveNotification.ts
  lib/notifications/utils.ts
  lib/utilities/dates.ts
  lib/webhookPublisher/authentication.ts
  package.json
  pages/api/notifications/list.ts
  scripts/readNotifications.ts
  scripts/sendNotifications.ts
  serverless.yml
  serverless/handler.ts
  serverless/packageShim.js
  serverless/schema.prisma
  serverless/sqs/worker.ts
  serverless/webhook/checker.ts
  serverless/webhook/worker.ts
  serverless/webhooks/checker.ts
  serverless/webhooks/publisher.ts
Labels: :rocket: serverless

#2934 add required fields to proposal form
  .storybook/mockApi.ts
  components/common/BoardEditor/components/properties/PropertyLabel.tsx
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/proposals/components/ProposalProperties/ProposalProperties.tsx
  stories/ProposalsPage/Proposals.stories.tsx
Labels: :rocket: deploy

#2939 Space specific notifications UI
  components/common/Avatar.tsx
  components/common/PageLayout/components/Header/Header.tsx
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
  components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
  components/common/PageLayout/components/Sidebar/components/SpaceListItem.tsx
  components/nexus/hooks/useNotifications.ts
Labels: :rocket: deploy

#2949 Feat/sticky save proposal button
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/proposals/components/ProposalDialog/NewProposalPage.tsx
  components/proposals/components/ProposalDialog/ProposalDialog.tsx
  components/proposals/components/ProposalDialog/hooks/useNewProposal.tsx
  stories/ProposalsPage/Proposals.stories.tsx
Labels: :rocket: deploy

#2913 import connectors from wagmi using central config
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
  connectors/config.ts
  hooks/useWeb3Account.tsx
Labels: :rocket: deploy

#2938 Migrated notification emails to react-email
  .eslintrc.json
  components/_app/GlobalComponents.tsx
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
  hooks/useMarkNotificationFromUrl.ts
  lib/mailer/emails/emails.ts
  lib/mailer/emails/templates/NotificationTemplate.tsx
  lib/mailer/emails/templates/PageInviteEmail.tsx
  lib/mailer/emails/templates/PendingNotificationsTemplate.tsx
  lib/mailer/emails/templates/__tests__/templates.spec.ts
  lib/mailer/emails/templates/components/Avatar.tsx
  lib/mailer/emails/templates/components/Button.tsx
  lib/mailer/emails/templates/components/EmailWrapper.tsx
  lib/mailer/emails/templates/components/Feedback.tsx
  lib/mailer/emails/templates/components/Footer.tsx
  lib/mailer/emails/templates/components/Header.tsx
  lib/mailer/emails/templates/components/HorizontalRule.tsx
  lib/mailer/emails/templates/components/Link.tsx
  lib/mailer/emails/templates/components/Text.tsx
  lib/mailer/emails/templates/components/index.tsx
  lib/mailer/emails/templates/theme/styles.ts
  lib/mailer/emails/templates/utils.ts
  lib/mailer/mailer.ts
  lib/notifications/createNotificationsFromEvent.ts
  lib/notifications/documents/__tests__/createDocumentNotifications.spec.ts
  lib/notifications/documents/createDocumentNotifications.ts
  lib/notifications/forum/__tests__/createForumNotifications.spec.ts
  lib/notifications/forum/createForumNotifications.ts
  lib/notifications/getNotificationMetadata.tsx
  lib/notifications/mailer/__tests__/sendNotificationEmail.spec.ts
  lib/notifications/mailer/sendNotificationEmail.ts
  lib/notifications/mailer/sendNotifications.ts
  lib/notifications/markNotifications.ts
  lib/notifications/polls/__tests__/createPollNotifications.spec.ts
  lib/notifications/polls/createPollNotifications.ts
  lib/notifications/proposals/getProposalNotifications.ts
  lib/notifications/publishForumPostEvents.ts
  lib/webhookPublisher/interfaces.ts
  lib/webhookPublisher/publishEvent.ts
  package.json
  pages/api/email-templates/user-notifications.ts
  pages/api/forums/posts/[postId]/index.ts
  pages/api/forums/posts/index.ts
  scripts/readNotifications.ts
  scripts/sendEmail.ts
  serverless.yml
  serverless/sqs/worker.ts
Labels: :rocket: deploy, :rocket: serverless

#2968 Fix links to views from sidebar and also empty state for linked databases
  __e2e__/po/databasePage.po.ts
  components/[pageId]/DatabasePage/DatabasePage.tsx
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/createLinkedView.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebarSelect.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions/useSourceOptions.tsx
Labels: :rocket: deploy

#2970 Feat/save new reward
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/PageHeader.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/common/PageDialog/NewPageDialog.tsx
  components/common/PageDialog/components/NewPageDocument.tsx
  components/common/PageDialog/hooks/useNewPage.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/components/NewRewardButton.tsx
  components/rewards/components/RewardProperties/RewardProperties.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  components/rewards/hooks/useNewReward.tsx
  components/rewards/hooks/useRewards.tsx
  lib/rewards/createReward.ts
  lib/rewards/interfaces.ts
Labels: :rocket: deploy

#2972 improve page search for charmeditor component
  components/common/CharmEditor/components/PageList.tsx
  components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx
  components/common/PageLayout/components/PageIcon.tsx
  lib/utilities/__tests__/strings.spec.ts
  lib/utilities/strings.ts
Labels: :rocket: deploy

#2976 better UX for inline dbs
  components/common/BoardEditor/focalboard/i18n/en.json
  components/common/BoardEditor/focalboard/i18n/en_AU.json
  components/common/BoardEditor/focalboard/src/components/calendar/fullCalendar.tsx
  components/common/BoardEditor/focalboard/src/components/calendar/fullcalendar.scss
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx
  components/common/CharmEditor/components/inlineDatabase/inlineDatabase.ts
  components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx
  components/common/CharmEditor/components/listItemNew/splitListItem.ts
  components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts
  components/common/CharmEditor/utils.ts
  lib/pages/addPage.ts
  theme/prosemirror-tables/prosemirror-tables.scss
Labels: :rocket: deploy

#2985 fix layout for gallery cards and also rewards queries
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/common/BoardEditor/components/properties/UserSelect.tsx
  components/common/BoardEditor/focalboard/src/components/__snapshots__/centerPanel.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/__snapshots__/kanban.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/kanban/__snapshots__/kanbanCard.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.spec.tsx
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/mutator.ts
  hooks/usePages.tsx
  pages/api/rewards/index.ts
Labels: :rocket: deploy

#2988 swap toggle with checkbox ui
  .storybook/preview.tsx
  components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
  components/common/BoardEditor/components/properties/UserSelect.tsx
  components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderPropertiesMenu.tsx
  components/common/BoardEditor/focalboard/src/widgets/checkbox.scss
  components/common/BoardEditor/focalboard/src/widgets/checkbox.tsx
  components/common/BoardEditor/focalboard/src/widgets/menu/checkboxOption.tsx
  components/common/BoardEditor/focalboard/src/widgets/menu/menu.tsx
  components/common/BoardEditor/focalboard/src/widgets/switch.tsx
  components/common/BoardEditor/focalboard/src/widgets/typeDisplayName.ts
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  pages/_app.tsx
Labels: :rocket: deploy

#2991 updaet page mentions when importing templates
  lib/templates/importWorkspacePages.ts
Labels: :rocket: deploy

#2995 Sync and assign collabland roles after connecting space
  lib/aws/webhookSqs.ts
  lib/collabland/__tests__/connectSpace.spec.ts
  lib/collabland/assignRolesCollabland.ts
  lib/collabland/connectSpace.ts
  lib/discord/removeSpaceMemberDiscord.tsx
  lib/discord/syncDiscordRoles.ts
  lib/discord/unassignRolesDiscord.ts
  lib/discord/updateMemberRolesFromDiscord.ts
  lib/discord/upsertSpaceRolesFromDiscord.ts
  lib/discord/verifyDiscordGateForSpace.ts
  lib/members/getSpaceMemberMetadata.ts
  lib/public-api/createWorkspaceApi.ts
  lib/webhookConsumer/interfaces.ts
  lib/webhookConsumer/processWebhookMessage.ts
Labels: :rocket: deploy

#3014 Fixed notification author display name in ui
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
  components/members/components/MemberDirectoryGalleryView.tsx
  components/members/components/MemberDirectoryTableView.tsx
  lib/notifications/getNotificationMetadata.tsx
  lib/notifications/mailer/sendNotificationEmail.ts
  lib/webhookPublisher/publisher.ts
  stories/Notifications/Notifications.stories.tsx
Labels: :rocket: deploy, :rocket: serverless

#2998 Blacklist space user
  charmClient/apis/membersApi.ts
  components/common/SpaceAccessGate/SpaceAccessGate.tsx
  components/common/SpaceAccessGate/SpaceBanModal.tsx
  components/common/SpaceAccessGate/components/DiscordGate/hooks/useDiscordGate.ts
  components/common/SpaceAccessGate/components/SummonGate/hooks/useSummonGate.tsx
  components/common/SpaceAccessGate/components/TokenGate/hooks/useTokenGates.ts
  components/invite/SpaceInviteLink.tsx
  components/settings/account/components/NewIdentityModal.tsx
  components/settings/roles/components/MemberRow.tsx
  hooks/useDiscordConnection.tsx
  hooks/useGoogleLogin.ts
  hooks/useMembers.tsx
  lib/discord/applyDiscordGate.ts
  lib/google/connectGoogleAccount.ts
  lib/google/connectGoogleAccountWithCode.ts
  lib/google/loginWithMagicLink.ts
  lib/invites/acceptInvite.ts
  lib/members/__tests__/checkUserSpaceBanStatus.spec.ts
  lib/members/banMember.ts
  lib/members/checkUserSpaceBanStatus.ts
  lib/roles/addGuest.ts
  lib/summon/addUserToSpace.ts
  lib/token-gates/applyTokenGates.ts
  lib/token-gates/evaluateEligibility.ts
  package.json
  pages/api/discord/connect.ts
  pages/api/google/code.ts
  pages/api/google/connect-email-account.ts
  pages/api/permissions/index.ts
  pages/api/profile/add-wallets.ts
  pages/api/profile/index.ts
  pages/api/spaces/[id]/members/[userId].ts
  pages/api/spaces/[id]/members/[userId]/ban.ts
  pages/api/spaces/[id]/members/[userId]/index.ts
  pages/api/spaces/[id]/members/ban-status.ts
  pages/api/summon/join-space.ts
  pages/authenticate/index.tsx
  pages/invite/[inviteCode].tsx
Labels: :rocket: deploy

#3012 More friction when signing up if you haven't provided an email
  components/_app/components/OnboardingEmailForm.tsx
  components/_app/components/UserOnboardingDialog.tsx
  components/common/BoardEditor/focalboard/src/components/dialog.tsx
  components/members/components/MemberProfile/components/ProfileWidgets/components/MemberPropertiesWidget/MemberPropertiesFormDialog.tsx
Labels: :rocket: deploy

#3017 fix closing sidebar when navigating favorites
  components/common/PageLayout/components/Sidebar/Sidebar.tsx
  components/common/PageLayout/components/Sidebar/components/NotificationsPopover.tsx
Labels: :rocket: deploy

#3015 fix category links for custom domains
  components/forum/ForumFeedPage.tsx
  components/forum/components/CategoryContextMenu.tsx
  components/forum/components/CategoryMenu.tsx
  components/forum/components/CategorySelect.tsx
  components/forum/components/ForumFilterListLink.tsx
  components/forum/components/PostCategoryPermissions/PostCategoryPermissionsContainer.tsx
  hooks/useForumCategories.tsx
Labels: :rocket: deploy
