Repository charmverse/app.charmverse.io, pull requests merged in 2024-06, with the labels that each got.

#4125 Fix: Database filters are not responsive on mobile
  components/common/DatabaseEditor/components/ViewFilterControl.tsx
Labels: :rocket: deploy

#4130 Send notification & email for proposal publish event
  components/settings/space/components/NotificationToggles.tsx
  lib/notifications/constants.ts
  lib/notifications/getNotificationMetadata.tsx
  lib/notifications/proposals/createProposalNotifications.ts
  lib/webhookPublisher/interfaces.ts
  lib/webhookPublisher/publishEvent.ts
  pages/api/proposals/[id]/publish.ts
  pages/api/proposals/evaluations/[id]/appeal/index.ts
  scripts/migrations/2024_06_06_uncheckProposalPublishedNotification.ts
  serverless/sqs/worker.ts
Labels: :rocket: deploy

#4131 Custom email branding for space
  .ebstalk.apps.env/cron.env
  components/settings/SettingsContent.tsx
  components/settings/config.tsx
  components/settings/notifications/NotificationSettings.tsx
  components/settings/notifications/components/SpaceEmailBrandingSettings.tsx
  components/settings/notifications/components/SpaceNotificationSettings.tsx
  components/settings/space/SpaceSettings.tsx
  components/settings/space/components/LargeAvatar.tsx
  components/settings/space/components/NotificationToggles.tsx
  lib/mailer/emails/emails.ts
  lib/mailer/emails/templates/NotificationTemplate.tsx
  lib/mailer/emails/templates/PageInviteEmail.tsx
  lib/mailer/emails/templates/components/Button.tsx
  lib/mailer/emails/templates/components/EmailWrapper.tsx
  lib/mailer/emails/templates/components/Feedback.tsx
  lib/mailer/emails/templates/components/Header.tsx
  lib/mailer/emails/templates/components/Link.tsx
  lib/mailer/emails/templates/components/Text.tsx
  lib/mailer/mailer.ts
  lib/metrics/mixpanel/interfaces/PageEvent.ts
  lib/notifications/mailer/sendNotificationEmail.ts
  lib/spaces/updateSpace.ts
  package.json
  pages/api/email-templates/page-invite.ts
  public/images/icons/speech-bubbles.png
Labels: :rocket: deploy

#4141 UI to send test notification email
  charmClient/apis/blockchainApi.ts
  charmClient/hooks/email.ts
  components/settings/SettingsContent.tsx
  components/settings/notifications/NotificationSettings.tsx
  components/settings/notifications/components/SpaceEmailBrandingSettings.tsx
  components/settings/notifications/components/SpaceNotificationSettings.tsx
  pages/api/email/send-test.ts
Labels: :rocket: deploy

#4144 UI to send test notification email
  charmClient/apis/blockchainApi.ts
  charmClient/hooks/email.ts
  components/settings/SettingsContent.tsx
  components/settings/notifications/NotificationSettings.tsx
  components/settings/notifications/components/SpaceEmailBrandingSettings.tsx
  components/settings/notifications/components/SpaceNotificationSettings.tsx
  pages/api/email/send-test.ts
Labels: :rocket: deploy

#4121 Select properties for proposal source boards
  __e2e__/database/databaseProposalsAsSource.spec.ts
  __e2e__/proposals/duplicateProposalTemplate.spec.ts
  __integration-tests__/server/pages/api/blocks/[id]/subtree.spec.ts
  charmClient/charmClient.ts
  charmClient/hooks/blocks.ts
  charmClient/hooks/proposals.ts
  components/common/DatabaseEditor/components/cardProperties/CardDetailProperty.tsx
  components/common/DatabaseEditor/components/table/tableHeader.tsx
  components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx
  components/common/DatabaseEditor/components/viewHeader/viewHeaderSortMenu.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewPropertyOption.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewPropertyOptions.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSidebarSelect.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/CustomPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/FormFieldPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProjectProfilePropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/PropertiesListSelector.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalDefaultPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourceDialogButton.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/SelectedPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/viewSourceType.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/viewSourceOptions.tsx
  components/proposals/components/NewProposalButton.tsx
  components/proposals/components/ProposalStepSelect.tsx
  components/proposals/hooks/useProposalTemplates.tsx
  lib/databases/board.ts
  lib/databases/getPropertyName.ts
  lib/databases/getRelatedBlocks.ts
  lib/databases/proposalDbProperties.ts
  lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts
  lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
  lib/databases/proposalsSource/filterBoardProperties.ts
  lib/databases/proposalsSource/getBlocks.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
  lib/databases/proposalsSource/updateBoardProperties.ts
  lib/proposals/getProposalTemplates.ts
  pages/api/blocks/[id]/index.ts
  pages/api/blocks/[id]/subtree.ts
  pages/api/blocks/index.ts
  pages/api/blocks/relation/sync-values.ts
  pages/api/pages/[id]/proposal-source.ts
  pages/api/spaces/[id]/proposal-templates.ts
  scripts/migrations/2024_05_30_deleteRubricCriteriaTotalProperties.ts
  testing/setupDatabase.ts
  testing/utils/proposals.ts
Labels: :rocket: deploy

#4148 Fixed test notification email sent to user's email
  pages/api/email/send-test.ts
Labels: :rocket: deploy

#4149 Select properties for proposal source boards (#4121)
  __e2e__/database/databaseProposalsAsSource.spec.ts
  __e2e__/proposals/duplicateProposalTemplate.spec.ts
  __integration-tests__/server/pages/api/blocks/[id]/subtree.spec.ts
  charmClient/charmClient.ts
  charmClient/hooks/blocks.ts
  charmClient/hooks/proposals.ts
  components/common/DatabaseEditor/components/cardProperties/CardDetailProperty.tsx
  components/common/DatabaseEditor/components/table/tableHeader.tsx
  components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx
  components/common/DatabaseEditor/components/viewHeader/viewHeaderSortMenu.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewPropertyOption.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewPropertyOptions.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSidebarSelect.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/CustomPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/FormFieldPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProjectProfilePropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/PropertiesListSelector.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalDefaultPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourceDialogButton.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/SelectedPropertiesList.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/viewSourceType.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/viewSourceOptions.tsx
  components/proposals/components/NewProposalButton.tsx
  components/proposals/components/ProposalStepSelect.tsx
  components/proposals/hooks/useProposalTemplates.tsx
  lib/databases/board.ts
  lib/databases/getPropertyName.ts
  lib/databases/getRelatedBlocks.ts
  lib/databases/proposalDbProperties.ts
  lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts
  lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
  lib/databases/proposalsSource/filterBoardProperties.ts
  lib/databases/proposalsSource/getBlocks.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
  lib/databases/proposalsSource/updateBoardProperties.ts
  lib/proposals/getProposalTemplates.ts
  pages/api/blocks/[id]/index.ts
  pages/api/blocks/[id]/subtree.ts
  pages/api/blocks/index.ts
  pages/api/blocks/relation/sync-values.ts
  pages/api/pages/[id]/proposal-source.ts
  pages/api/spaces/[id]/proposal-templates.ts
  scripts/migrations/2024_05_30_deleteRubricCriteriaTotalProperties.ts
  scripts/migrations/2024_05_30_updateProposalSourceBoardCardProperties.ts
  testing/setupDatabase.ts
  testing/utils/proposals.ts
Labels: :rocket: deploy

#4161 Fixed custom proposal source board properties not showing
  lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
  lib/databases/proposalsSource/filterBoardProperties.ts
  lib/projects/formField.ts
  scripts/migrations/2024_06_11_exportCustomProposalSourceBoardProperties.ts
Labels: :rocket: deploy

#4158 Rubric criteria average score in proposal source board properties
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
  components/common/DatabaseEditor/store/cards.ts
  components/common/DatabaseEditor/widgets/iconForPropertyType.tsx
  components/common/DatabaseEditor/widgets/typeDisplayName.ts
  lib/databases/board.ts
  lib/databases/filterClause.ts
  lib/databases/generateCsv.ts
  lib/databases/proposalDbProperties.ts
  lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts
  lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
  lib/databases/proposalsSource/filterBoardProperties.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/getCardProperties.ts
  lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
Labels: :rocket: deploy

#4154 Optimism proposal scripts
  lib/farcaster/getFarcasterProfile.ts
  lib/proposals/createDraftProposal.ts
  lib/websockets/authentication.ts
  scripts/importOPGrantsProjects.ts
  scripts/optimism/exportRetroCSVs.ts
  scripts/optimism/getProjects.ts
  scripts/optimism/getRound3Projects.ts
  scripts/optimism/importRetroProjects.ts
  scripts/optimism/importRetroReviewers.ts
  scripts/optimism/replaceReviewers.ts
  scripts/optimism/retroData.ts
  scripts/optimism/updateRetroValues.ts
  scripts/query.ts
Labels: work-in-progress

#4171 Add proposal link as rewards table custom property
  components/rewards/components/RewardProperties/CustomPropertiesAdapter.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
Labels: :rocket: deploy

#4169 Show and filter custom properties in reward applicants board view
  components/common/DatabaseEditor/components/kanban/KanbanGroupColumn.tsx
  components/common/DatabaseEditor/components/kanban/kanban.tsx
  components/common/DatabaseEditor/components/kanban/kanbanCard.tsx
  components/common/PageActions/KanbanPageActionButton.tsx
  components/common/PageActions/components/CopyPageLinkAction.tsx
  components/common/PageActions/components/DatabaseRowActionsMenu.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/hooks/useRewardsBoardAdapter.ts
Labels: :rocket: deploy

#4173 Collapse evaluation section for creating proposal with template
  __e2e__/proposals/freeFormProposalTemplate.spec.ts
  components/proposals/ProposalPage/components/ProposalEvaluations/ProposalEvaluations.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettingsRow.tsx
Labels: :rocket: deploy

#4175 collapse navigation bar if workflow sidebar is open
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/[pageId]/DocumentPage/DocumentPageWithSidebars.tsx
  components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx
  components/common/PageLayout/PageLayout.tsx
  components/rewards/NewRewardPage.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
Labels: :rocket: deploy

#4122 Poc monorepo
  .cdk/base-staging-stack.ts
  .cdk/bin/app.ts
  .cdk/charmverse-staging-stack.ts
  .cdk/connect-staging-stack.ts
  .cdk/staging-stack.ts
  .ebextensions_connect/00_env_vars.config
  .ebextensions_connect/01_env_health_ignore_400.config
  .ebextensions_connect/04_autoscaling.config
  .ebextensions_connect/06_cloudwatch_alarm.config
  .ebstalk.apps.env/connect.env
  .eslintrc.json
  .github/actions/build_connect/action.yml
  .github/actions/build_docker_image/action.yml
  .github/workflows/deploy_connect_staging.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/destroy_staging.yml
  .github/workflows/test_and_deploy.yml
  .gitignore
  apps/connect-api/__integration-tests__/api/random-number.spec.ts
  apps/connect-api/jest.config.ts
  apps/connect-api/lib/__tests__/exampleMethod.spec.ts
  apps/connect-api/lib/exampleMethod.ts
  apps/connect-api/package.json
  apps/connect-api/src/main.ts
  apps/connect-api/src/server.ts
  apps/connect-api/tsconfig.json
  apps/connect/.eslintrc.json
  apps/connect/README.md
  apps/connect/apiClient/apiClient.ts
  apps/connect/apiClient/baseConnectApiClient.ts
  apps/connect/apiClient/testApiClient.ts
  apps/connect/app/cssVariables.scss
  apps/connect/app/favicon.ico
  apps/connect/app/layout.tsx
  apps/connect/app/page.module.css
  apps/connect/app/page.tsx
  apps/connect/next-env.d.ts
  apps/connect/next.config.js
  apps/connect/package.json
  apps/connect/public/next.svg
  apps/connect/public/vercel.svg
  apps/connect/tsconfig.json
  components/common/Button.tsx
  config/constants.ts
  docker-compose.yml
  package.json
  shared/components/elements/Button.tsx
  theme/AppThemeProvider.tsx
  tsconfig.json
  tsconfig.next.json
Labels: :rocket: deploy-connect

#4179 Revert "Fix user select property"
  components/common/DatabaseEditor/components/properties/UserSelect.tsx
  components/common/form/InputSearchMember.tsx
Labels: :rocket: deploy

#4192 use tabs to delimit columns in CSV an dcommas for values
  lib/databases/__tests__/generateCsv.spec.ts
  lib/databases/generateCsv.ts
Labels: :rocket: deploy

#4198 Disable cw alarm on connect-api and add Datadog
  .cdk/StagingStack.ts
  .ebextensions_connect_api/06_cloudwatch_alarm.config
  docker-compose.yml
Labels: :rocket: deploy-connect

#4201 add swap file for connect deployments
  .ebextensions_connect/01_setup_swap.config
  .ebextensions_connect/02_autoscaling.config
  .ebextensions_connect/03_env_health_ignore_400.config
  .ebextensions_connect/04_cloudwatch_alarm.config
  .ebextensions_connect/setup_swap.sh
  .ebextensions_connect_api/01_setup_swap.config
  .ebextensions_connect_api/02_autoscaling.config
  .ebextensions_connect_api/03_env_health_ignore_400.config
  .ebextensions_connect_api/setup_swap.sh
Labels: :rocket: deploy-connect

#4204 hide share buttons for proposals that are not public
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
  lib/proposals/__tests__/getProposal.spec.ts
  lib/proposals/getProposal.ts
  lib/proposals/interfaces.ts
  lib/proposals/mapDbProposalToProposal.ts
  testing/mocks/proposal.ts
Labels: :rocket: deploy

#4212 Fixed proposal step value
  lib/databases/proposalDbProperties.ts
  lib/databases/proposalsSource/filterBoardProperties.ts
Labels: :rocket: deploy

#4187 Fixed editor pdf upload issue
  components/common/CharmEditor/components/pdf/PDFViewer.tsx
  components/common/CharmEditor/components/pdf/ResizablePDF.tsx
  components/common/PdfSelector/PdfSelector.tsx
Labels: :rocket: deploy

#4216 Fix connect api
  .github/workflows/test_and_deploy.yml
  apps/connect-api/src/server.ts
  apps/connect/apiClient/HttpClient.ts
  apps/connect/apiClient/apiClient.ts
Labels: :rocket: deploy-connect

#4133 add scripts to deploy test credentials
  lib/credentials/indexOnChainProposalCredential.ts
  lib/utils/ethers.ts
  scripts/credentials/deploySchema.ts
Labels: work-in-progress

#4218 Fix connect api, add logging and speed up CI a little
  .ebstalk.apps.env/connect-api.env
  .ebstalk.apps.env/connect.env
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  apps/connect-api/package.json
  apps/connect-api/src/lib/pathBasedRouter.ts
  apps/connect-api/src/logRoutes.ts
  apps/connect-api/src/main.ts
  apps/connect-api/src/server.ts
  apps/connect/apiClient/HttpClient.ts
Labels: :rocket: deploy-connect

#4215 Display op project details in tabs
  components/common/form/fields/OptimismProjectSelector.tsx
Labels: :rocket: deploy

#4224 Session domain setting
  apps/connect-api/src/server.ts
  lib/session/getIronOptions.ts
Labels: :rocket: deploy-connect

#4228 fix cookie config for staging
  apps/connect-api/src/server.ts
  docker-compose.yml
Labels: :rocket: deploy-connect

#4221 Connect Project page
  .ebstalk.apps.env/connect-api.env
  .ebstalk.apps.env/connect.env
  .ebstalk.apps.env/webapp.env
  apps/connect-api/src/api/farcaster/get-by-username.ts
  apps/connect-api/src/routes.ts
  apps/connect/apiClient/apiClient.ts
  apps/connect/app/projects/[id]/loading.tsx
  apps/connect/app/projects/[id]/page.tsx
  apps/connect/components/common/FarcasterCard.tsx
  apps/connect/components/profile/ProfilePage.tsx
  apps/connect/components/projects/ProjectShareButton.tsx
  apps/connect/components/projects/[id]/ProjectDetailsPage.tsx
  apps/connect/components/projects/components/AddProjectMembersForm.tsx
  apps/connect/components/projects/components/ProjectDescription.tsx
  apps/connect/components/projects/components/ProjectDetailsSkeleton.tsx
  apps/connect/components/projects/components/ProjectItem.tsx
  apps/connect/components/projects/components/SearchFarcasterUser.tsx
  apps/connect/components/projects/new/components/CreateProjectForm.tsx
  apps/connect/components/welcome/WelcomePage.tsx
  apps/connect/lib/actions/createProject.ts
  apps/connect/lib/actions/fetchProject.ts
  apps/connect/lib/projects/getRecentProjectsWithMembers.ts
  apps/connect/public/images/farcaster.png
  apps/connect/public/images/mirror-xyz.png
  apps/connect/theme/theme.tsx
  lib/farcaster/getFarcasterUsersByUsername.ts
Labels: :rocket: deploy-connect

#4227 Add support for Kyoto and Polygon testnet
  connectors/chains.ts
  lib/tokenGates/humanizeConditions.ts
  public/images/cryptoLogos/kyoto-logo.png
  public/images/cryptoLogos/kyoto-logo.svg
Labels: :rocket: deploy

#4233 Fix bug in project form when adding/removing team members
  charmClient/hooks/projects.ts
  charmClient/hooks/proposals.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/form/FormField.tsx
  components/common/form/FormFieldAnswers.tsx
  components/common/form/fields/ProjectField/ProjectFieldAnswer.tsx
  components/common/form/fields/ProjectField/ProjectFieldEditor.tsx
  components/common/form/fields/ProjectField/ProjectForm.tsx
  components/common/form/fields/ProjectField/useProjectUpdates.ts
  components/proposals/hooks/useProjectForm.ts
  components/proposals/hooks/useProposalFormAnswers.ts
  components/settings/projects/ProjectsSettings.tsx
  components/settings/projects/components/CreateProjectForm.tsx
  components/settings/projects/components/FieldAnswers.tsx
  components/settings/projects/components/FieldsEditor.tsx
  components/settings/projects/components/ProjectFields.tsx
  components/settings/projects/components/ProjectForm.tsx
  components/settings/projects/components/ProjectMemberFields.tsx
  components/settings/projects/hooks/useProjectUpdates.ts
  lib/projects/constants.ts
  lib/projects/convertToProjectValues.ts
  lib/projects/getDefaultProjectValues.ts
  lib/projects/getProjectsByUserId.ts
  lib/projects/interfaces.ts
  stories/FormFields/FormFields.stories.tsx
  stories/Projects/ProjectFormEditor.stories.tsx
Labels: :rocket: deploy

#4234 update the cache of projects when using project form
  components/common/form/fields/ProjectField/ProjectFieldAnswer.tsx
  components/common/form/fields/ProjectField/ProjectForm.tsx
  components/common/form/fields/ProjectField/useProjectUpdates.ts
  lib/projects/constants.ts
  lib/proposals/__tests__/validateProposalProject.spec.ts
  lib/proposals/getProposalErrors.ts
  lib/proposals/validateProposalProject.ts
Labels: :rocket: deploy

#4232 Public connect project pages
  apps/connect-api/src/api/farcaster/get-by-username.ts
  apps/connect/apiClient/apiClient.ts
  apps/connect/app/p/[id]/loading.tsx
  apps/connect/app/p/[id]/page.tsx
  apps/connect/components/profile/ProfilePage.tsx
  apps/connect/components/projects/components/AddProjectMembersForm.tsx
  apps/connect/components/projects/components/ProjectDescription.tsx
  apps/connect/components/projects/components/ProjectItem.tsx
  apps/connect/components/projects/components/SearchFarcasterUser.tsx
  apps/connect/components/welcome/WelcomePage.tsx
  apps/connect/lib/actions/fetchProject.ts
  apps/connect/middleware.ts
  lib/farcaster/getFarcasterUsers.ts
  lib/farcaster/getFarcasterUsersByUsername.ts
  package.json
Labels: :rocket: deploy-connect
