Repository charmverse/app.charmverse.io, pull requests merged in 2024-05, with the labels that each got.

#3979 Add support for preventing new props if board is locked
  __e2e__/database/relationProperty.spec.ts
  __e2e__/po/databasePage.po.ts
  __integration-tests__/server/pages/api/blocks/index.spec.ts
  __integration-tests__/server/pages/api/pages/[id]/toggle-lock.spec.ts
  charmClient/charmClient.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/DatabaseEditor/components/cardDetail/cardDetailProperties.tsx
  components/common/DatabaseEditor/components/cardProperties/CardDetailProperty.tsx
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/store/boards.ts
  lib/databases/block.ts
  lib/databases/board.ts
  lib/databases/card.ts
  lib/databases/getRelatedBlocks.ts
  lib/databases/relationProperty/syncRelatedCardsValues.ts
  lib/pages/duplicatePage.ts
  lib/pages/togglePageLock.ts
  lib/websockets/interfaces.ts
  pages/api/blocks/[id]/index.ts
  pages/api/blocks/[id]/subtree.ts
  pages/api/blocks/index.ts
  pages/api/blocks/relation/sync-values.ts
  pages/api/pages/[id]/toggle-lock.ts
Labels: :rocket: deploy

#4011 Ux/proposal creds
  components/common/WorkflowSidebar/components/CredentialReviewStep/CredentialRow.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
  lib/credentials/__tests__/findSpaceIssuableProposalCredentials.spec.ts
  lib/credentials/findIssuableProposalCredentials.ts
  lib/databases/proposalsSource/__tests__/applyPropertiesToCards.spec.ts
  lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
  lib/databases/proposalsSource/getCardProperties.ts
  lib/proposals/getCurrentStep.ts
  lib/proposals/getProposals.ts
  lib/proposals/publishProposal.ts
  pages/api/blocks/[id]/index.ts
Labels: :rocket: deploy

#4019 Find coinbase wallet connector correctly
  components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
Labels: :rocket: deploy

#4020 Updated getting started page
  seedData/gettingStartedPage.ts
Labels: :rocket: deploy

#4025 Remove milestone form field answers
  lib/forms/upsertProposalFormAnswers.ts
Labels: :rocket: deploy

#3990 Rewards KYC
  __e2e__/bounties/rewardWorkflow.spec.ts
  __e2e__/po/rewardPage.po.ts
  __e2e__/settings/updateIntegrations.spec.ts
  charmClient/hooks/kyc.ts
  charmClient/hooks/spaces.ts
  components/[pageId]/DocumentPage/hooks/useReward.ts
  components/common/Link.tsx
  components/rewards/NewRewardPage.tsx
  components/rewards/components/RewardEvaluations/components/Review/EvaluationsReview.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/KycStepSettings.tsx
  components/rewards/components/RewardProperties/components/RewardApplicationTypeSelect.tsx
  components/settings/integrations/components/KYC/KYCSettings.tsx
  components/settings/integrations/components/KYC/KYCSettingsForm.tsx
  components/settings/integrations/components/KYC/PersonaModal.tsx
  components/settings/integrations/components/KYC/SynapsModal.tsx
  lib/kyc/synaps/createSynapsSession.ts
  lib/kyc/synaps/getSynapsSessionDetails.ts
  lib/kyc/synaps/interfaces.ts
  lib/rewards/getRewardWorkflowWithApplication.ts
  lib/rewards/getRewardWorkflows.ts
  lib/rewards/inferRewardWorkflow.ts
  lib/rewards/updateRewardSettings.ts
  pages/api/spaces/[id]/kyc-credentials/persona/[userId].ts
  pages/api/spaces/[id]/kyc-credentials/persona/index.ts
  pages/api/spaces/[id]/kyc-credentials/synaps/[userId].ts
  pages/api/spaces/[id]/kyc-credentials/synaps/index.ts
  testing/utils/kyc.ts
Labels: :rocket: deploy

#4027 allow grouping rewards by milestone
  components/common/DatabaseEditor/components/ViewFilterControl.tsx
  components/common/DatabaseEditor/components/ViewSortControl.tsx
  components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
  components/common/DatabaseEditor/components/centerPanel.tsx
  components/common/DatabaseEditor/components/kanban/KanbanGroupColumn.tsx
  components/common/DatabaseEditor/components/kanban/__snapshots__/kanban.spec.tsx.snap
  components/common/DatabaseEditor/components/kanban/__snapshots__/kanbanColumnHeader.spec.tsx.snap
  components/common/DatabaseEditor/components/kanban/kanban.spec.tsx
  components/common/DatabaseEditor/components/kanban/kanban.tsx
  components/common/DatabaseEditor/components/kanban/kanbanColumnHeader.spec.tsx
  components/common/DatabaseEditor/components/kanban/kanbanColumnHeader.tsx
  components/common/DatabaseEditor/components/kanban/kanbanHiddenColumnItem.spec.tsx
  components/common/DatabaseEditor/components/kanban/kanbanHiddenColumnItem.tsx
  components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
  components/common/DatabaseEditor/components/table/__snapshots__/tableGroupHeaderRow.spec.tsx.snap
  components/common/DatabaseEditor/components/table/table.scss
  components/common/DatabaseEditor/components/table/table.spec.tsx
  components/common/DatabaseEditor/components/table/table.tsx
  components/common/DatabaseEditor/components/table/tableGroup.tsx
  components/common/DatabaseEditor/components/table/tableGroupHeaderRow.spec.tsx
  components/common/DatabaseEditor/components/table/tableGroupHeaderRow.tsx
  components/common/DatabaseEditor/components/table/tableRow.tsx
  components/common/DatabaseEditor/components/table/tableRows.tsx
  components/common/DatabaseEditor/components/viewHeader/ToggleViewSidebarButton.tsx
  components/common/DatabaseEditor/components/viewHeader/__snapshots__/viewHeader.spec.tsx.snap
  components/common/DatabaseEditor/components/viewHeader/__snapshots__/viewHeaderSearch.spec.tsx.snap
  components/common/DatabaseEditor/components/viewHeader/viewHeader.tsx
  components/common/DatabaseEditor/components/viewHeader/viewHeaderSearch.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewGroupOptions.tsx
  components/common/DatabaseEditor/widgets/buttons/iconButton.tsx
  components/rewards/RewardsPage.tsx
  hooks/useAreaSelection.ts
  hooks/useDisablePropagation.ts
  lib/databases/board.ts
  lib/utils/react.ts
  scripts/query.ts
  stories/Databases/Kanban.stories.tsx
Labels: :rocket: deploy

#4032 Fix user select property
  components/common/form/InputSearchMember.tsx
Labels: :rocket: deploy

#4034 Disable token chain and token inputs when using a reward template
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/RewardTokenProperty.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalRewards.ts
  components/rewards/NewRewardPage.tsx
  components/rewards/components/RewardEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx
  components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/PaymentStepSettings.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/components/RewardTokenForm.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  components/rewards/components/RewardProperties/components/RewardTokenDialog.tsx
Labels: :rocket: deploy

#4031 Fix forms values
  components/common/form/hooks/useFormFields.ts
  components/members/hooks/useRequiredMemberProperties.ts
  components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
  components/settings/profile/components/SocialInputs.tsx
  components/settings/profile/components/UserDescription.tsx
  components/settings/profile/components/UserDetailsForm.tsx
  components/settings/projects/components/ProjectForm.tsx
Labels: :rocket: deploy

#4053 Fixed issue with project field not found
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
  lib/proposals/validateProposalProject.ts
Labels: :rocket: deploy

#4043 Allow creating Assigned workflow reward templates without applicants
  __e2e__/bounties/rewardApplication.spec.ts
  __e2e__/bounties/rewardWorkflow.spec.ts
  components/[pageId]/DocumentPage/hooks/useReward.ts
  components/common/DatabaseEditor/components/properties/UserSelect.tsx
  components/common/form/InputSearchMember.tsx
  components/rewards/NewRewardPage.tsx
  components/rewards/components/RewardEvaluations/RewardEvaluations.tsx
  components/rewards/components/RewardEvaluations/components/Review/EvaluationsReview.tsx
  components/rewards/components/RewardEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx
  components/rewards/components/RewardEvaluations/components/Review/components/SubmitStepReview.tsx
  components/rewards/components/RewardEvaluations/components/Settings/EvaluationsSettings.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/SubmitStepSettings.tsx
  lib/proposals/createRewardsForProposal.ts
  lib/rewards/__tests__/inferRewardWorkflow.spec.ts
  lib/rewards/blocks/interfaces.ts
  lib/rewards/createDefaultReward.ts
  lib/rewards/getRewardErrors.ts
  lib/rewards/getRewardWorkflows.ts
  lib/rewards/inferRewardWorkflow.ts
  pages/api/spaces/[id]/rewards/workflows/index.ts
  scripts/migrations/2024_05_09_addRewardFieldsWorkflowId.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#4054 Fixed issue when deleting nested page inside column
  lib/websockets/spaceEvents.ts
Labels: :rocket: deploy

#4047 Private proposal evaluation content
  __e2e__/database/relationProperty.spec.ts
  __e2e__/proposals/structuredProposalTemplate.spec.ts
  __e2e__/proposals/structuredProposalWithProject.spec.ts
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/viewSourceOptions.tsx
  components/common/Icons/VisibilityIcon.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PrivateEvaluation.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx
  components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
  components/settings/proposals/SpaceProposalSettings.tsx
  components/settings/proposals/components/EvaluationPermissions.tsx
  components/settings/proposals/components/EvaluationRow.tsx
  components/settings/proposals/components/ProposalWorkflow.tsx
  components/settings/proposals/constants.tsx
  lib/credentials/indexOnChainProposalCredential.ts
  lib/credentials/indexOnChainRewardCredential.ts
  lib/notifications/proposals/createProposalNotifications.ts
  lib/proposals/__tests__/concealProposalSteps.spec.ts
  lib/proposals/concealProposalSteps.ts
  lib/proposals/getProposalErrors.ts
  lib/proposals/getProposals.ts
  lib/proposals/interfaces.ts
  lib/proposals/workflows/__tests__/obfuscateWorkflow.spec.ts
  lib/proposals/workflows/__tests__/upsertWorkflowTemplate.spec.ts
  lib/proposals/workflows/defaultWorkflows.ts
  lib/proposals/workflows/obfuscateWorkflow.ts
  lib/roles/__tests__/getAssignedRoleIds.spec.ts
  lib/roles/getAssignedRoleIds.ts
  lib/templates/__tests__/importSpaceSettings.spec.ts
  pages/api/proposals/[id]/index.ts
  pages/api/spaces/[id]/proposals/index.ts
  pages/api/spaces/[id]/proposals/workflows/index.ts
Labels: :rocket: deploy

#4056 Lift feature flag for hidden evaluations
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
  components/settings/proposals/components/ProposalWorkflow.tsx
  lib/proposals/concealProposalSteps.ts
Labels: :rocket: deploy

#4059 Fix sort databases
  components/common/DatabaseEditor/components/table/tableHeader.tsx
  components/common/DatabaseEditor/store/cards.ts
Labels: :rocket: deploy

#4057 Proposal evaluation final step settings
  __e2e__/database/createAndEditDatabase.spec.ts
  __e2e__/database/createLinkedDatabase.spec.ts
  __e2e__/database/databaseProposalsAsSource.spec.ts
  __e2e__/database/navigateThroughDatabases.spec.ts
  __e2e__/database/relationProperty.spec.ts
  __e2e__/po/pagesSidebar.po.ts
  __e2e__/po/pagesSiderbar.po.ts
  __e2e__/proposals/proposalFinalStep.spec.ts
  __e2e__/testWithFixtures.ts
  background/tasks/updateVotesStatus/updateVoteStatus.ts
  components/common/WorkflowSidebar/components/EvaluationStepRow.tsx
  components/common/WorkflowSidebar/components/StepperResultIcon.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx
  components/proposals/components/ProposalStepSelect.tsx
  components/settings/proposals/SpaceProposalSettings.tsx
  components/settings/proposals/components/EvaluationDialog.tsx
  components/settings/proposals/components/ProposalWorkflow.tsx
  lib/credentials/__tests__/findSpaceIssuableProposalCredentials.spec.ts
  lib/credentials/findIssuableProposalCredentials.ts
  lib/credentials/issueOffchainProposalCredentialsIfNecessary.ts
  lib/databases/proposalsSource/getCardProperties.ts
  lib/notifications/proposals/createProposalNotifications.ts
  lib/proposals/applyProposalWorkflow.ts
  lib/proposals/createProposal.ts
  lib/proposals/createRewardsForProposal.ts
  lib/proposals/getCurrentStep.ts
  lib/proposals/getProposalAction.ts
  lib/templates/__tests__/importWorkspacePages.spec.ts
  lib/webhookPublisher/publishEvent.ts
  package.json
  scripts/fixProposalSteps.ts
Labels: :rocket: deploy

#4060 Fix for filter database relation property
  components/common/DatabaseEditor/components/viewHeader/RelatedPagesSelect.tsx
Labels: :rocket: deploy

#4037 Fix proposal labels in list and db source
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/proposals/components/ProposalStatusSelect.tsx
  lib/databases/proposalDbProperties.ts
Labels: :rocket: deploy

#4058 Credential notifications
  components/settings/space/components/NotificationToggles.tsx
  lib/credentials/saveIssuedCredential.ts
  lib/notifications/constants.ts
  lib/notifications/getNotificationMetadata.tsx
  lib/notifications/proposals/createProposalNotifications.ts
  lib/notifications/rewards/createRewardNotifications.ts
  lib/webhookPublisher/interfaces.ts
  lib/webhookPublisher/publishEvent.ts
Labels: :rocket: deploy

#4067 Workflow appeal & priority steps UI improvements
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/proposals/components/ProposalStepSelect.tsx
  components/settings/proposals/components/EvaluationDialog.tsx
  lib/credentials/issueOffchainProposalCredentialsIfNecessary.ts
  lib/notifications/proposals/createProposalNotifications.ts
  lib/proposals/getCurrentStep.ts
  lib/proposals/getProposalAction.ts
  lib/proposals/updateProposalEvaluation.ts
  lib/webhookPublisher/publishEvent.ts
  pages/api/proposals/[id]/evaluation.ts
Labels: :rocket: deploy

#4068 Sync proposal template and workflow appeal & final step settings
  lib/proposals/workflows/controller.ts
Labels: :rocket: deploy

#4078 optimize React rendering on Rewards page
  components/common/DatabaseEditor/components/centerPanel.tsx
  components/common/DatabaseEditor/components/table/table.tsx
  components/common/DatabaseEditor/components/table/tableRow.tsx
  components/common/DatabaseEditor/components/table/tableRows.tsx
  components/common/DatabaseEditor/mutator.ts
  components/rewards/components/RewardsBoard/hooks/useRewardsBoardMutator.ts
  components/rewards/hooks/useRewardsBoardAdapter.ts
  hooks/useAreaSelection.ts
  scripts/optimisms/getProjects.ts
Labels: deploy-ceramic

#4083 Fixed rewards application open button showing error page
  __e2e__/bounties/rewardApplication.spec.ts
  __e2e__/po/rewardPage.po.ts
  components/common/DatabaseEditor/components/table/tableRow.tsx
Labels: :rocket: deploy

#4084 Show credentials step for rewards templates
  components/rewards/components/RewardEvaluations/components/Settings/EvaluationsSettings.tsx
Labels: :rocket: deploy

#4086 Add shadows to crypto icons
  components/common/DatabaseEditor/components/properties/tokenAmount/tokenAmount.tsx
  components/common/Icons/BlockchainLogo.tsx
  components/common/Icons/TokenLogo.tsx
  components/common/TokenBadge.tsx
  components/common/TokenGateModal/components/TokenGateBlockchainSelect.tsx
  components/common/TokenLogo.tsx
  components/common/form/InputSearchBlockchain.tsx
  components/common/form/InputSearchCrypto.tsx
  components/credentials/CredentialsSelect.tsx
  components/rewards/components/RewardAmount.tsx
  components/rewards/components/RewardApplicationPage/components/GnosisSafesList.tsx
  components/rewards/components/RewardProperties/components/RewardTokenInfo.tsx
  theme/colors.ts
  theme/cssVariables.ts
Labels: :rocket: deploy

#4088 Fixed showing review button after publishing proposal
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
  components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
Labels: :rocket: deploy

#4082 Reward Applicants Board
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/DatabaseEditor/components/createLinkedView.tsx
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/components/table/tableRow.tsx
  components/common/DatabaseEditor/components/viewHeader/ViewHeaderRowsMenu/components/PropertyMenu.tsx
  components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSidebar.tsx
  components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/viewSourceOptions.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/components/RewardsBoard/utils/getDefaultRewardProperties.ts
  components/rewards/hooks/useRewardsBoardAdapter.ts
  lib/databases/board.ts
  lib/databases/boardView.ts
  lib/rewards/blocks/__tests__/upsertDefaultRewardsBoard.spec.ts
  lib/rewards/blocks/constants.ts
  lib/rewards/blocks/upsertDefaultRewardsBoard.ts
  lib/rewards/blocks/views.ts
  lib/rewards/createDefaultReward.ts
  scripts/migrations/2024_05_27_rewardSubmissionsBoard.ts
Labels: :rocket: deploy

#4100 Fixed pasting text inside code block
  components/common/CharmEditor/components/markdown/__tests__/markdown.plugin.spec.ts
  components/common/CharmEditor/components/markdown/markdown.plugins.ts
Labels: :rocket: deploy

#4105 Provide appeal reason when appealing review decision
  __e2e__/proposals/appealProposal.spec.ts
  charmClient/hooks/proposals.ts
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx
  lib/proposals/goBackToStep.ts
  lib/proposals/mapDbProposalToProposal.ts
  lib/templates/__tests__/importWorkspacePages.spec.ts
  pages/api/proposals/evaluations/[id]/appeal/index.ts
Labels: :rocket: deploy

#4104 Add rubric criteria question as column with total score as value
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/store/cards.ts
  components/common/DatabaseEditor/widgets/iconForPropertyType.tsx
  components/common/DatabaseEditor/widgets/typeDisplayName.ts
  lib/databases/board.ts
  lib/databases/filterClause.ts
  lib/databases/generateCsv.ts
  lib/databases/proposalDbProperties.ts
  lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
  lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
  lib/databases/proposalsSource/updateBoardProperties.ts
Labels: :rocket: deploy

#4116 Added custom tooltip based on description for rubric criteria columns
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/components/table/tableHeader.tsx
  lib/databases/board.ts
  lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/updateBoardProperties.ts
Labels: :rocket: deploy

#4115 Proposal reviewers column for proposal source boards [skip-tests]
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/octoUtils.tsx
  components/common/DatabaseEditor/store/cards.ts
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  lib/databases/cardFilter.ts
  lib/databases/proposalsSource/getBoardProperties.ts
  lib/databases/proposalsSource/getCardProperties.ts
  lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
  lib/databases/proposalsSource/updateBoardProperties.ts
  lib/proposals/blocks/interfaces.ts
  lib/proposals/concealProposalSteps.ts
  lib/proposals/createDefaultProposal.ts
  pages/api/pages/[id]/proposal-source.ts
Labels: work-in-progress, :rocket: deploy

#4119 Clean up bounty reviewers and add filter by role for all reviewers
  __integration-tests__/server/pages/api/rewards/index.spec.ts
  components/common/DatabaseEditor/components/properties/UserAndRoleSelect.tsx
  components/common/DatabaseEditor/components/propertyValueElement.tsx
  components/common/DatabaseEditor/components/viewHeader/ViewHeaderRowsMenu/components/PropertyTemplateMenu.tsx
  components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalRewards.ts
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/rewards/components/RewardEvaluations/components/Review/components/ReviewStepReview.tsx
  components/rewards/components/RewardEvaluations/components/Settings/components/ReviewStepSettings.tsx
  components/rewards/components/RewardProperties/components/MissingPagePermissions.tsx
  components/rewards/components/RewardsHeaderRowsMenu.tsx
  components/rewards/hooks/useRewardsBoardAdapter.ts
  lib/databases/cardFilter.ts
  lib/databases/filterClause.ts
  lib/github/__tests__/createRewardFromIssue.spec.ts
  lib/github/createRewardFromIssue.ts
  lib/permissions/bounties/__tests__/addBountyPermissionGroup.spec.ts
  lib/permissions/bounties/__tests__/computeBountyPermissions.spec.ts
  lib/permissions/bounties/__tests__/mapBountyPermissions.spec.ts
  lib/permissions/bounties/addBountyPermissionGroup.ts
  lib/permissions/bounties/client.ts
  lib/permissions/bounties/index.ts
  lib/permissions/bounties/interfaces.ts
  lib/permissions/bounties/mapBountyPermissions.ts
  lib/permissions/validateAssigneeGroup.ts
  lib/proposals/createRewardsForProposal.ts
  lib/rewards/__tests__/createReward.spec.ts
  lib/rewards/__tests__/getReward.spec.ts
  lib/rewards/__tests__/getRewardTemplates.spec.ts
  lib/rewards/__tests__/setRewardUsers.spec.ts
  lib/rewards/__tests__/updateRewardSettings.spec.ts
  lib/rewards/blocks/interfaces.ts
  lib/rewards/createDefaultReward.ts
  lib/rewards/createReward.ts
  lib/rewards/interfaces.ts
  lib/rewards/mapDbRewardToReward.ts
  lib/rewards/setRewardUsers.ts
  lib/rewards/updateRewardSettings.ts
  scripts/applicationImport/importApplications.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy
