Repository charmverse/app.charmverse.io, pull requests merged in 2024-03, with the labels that each got.

#3734 Add description to proposal board
  components/proposals/ProposalsPage.tsx
Labels: :rocket: deploy

#3740 Hats Protocol Token Gate
  components/common/TokenGateModal/components/TokenGateCommunities.tsx
  components/common/TokenGateModal/hooks/useCommunitiesForm.tsx
  components/common/TokenGateModal/utils/getCommunitiesAccessControlConditions.ts
  components/common/TokenGateModal/utils/utils.ts
  connectors/chains.ts
  lib/blockchain/updateTokenGateDetails.ts
  lib/tokenGates/abis/abis.ts
  lib/tokenGates/humanizeConditions.ts
  lib/tokenGates/interfaces.ts
  lib/tokenGates/validateTokenGateCondition.ts
Labels: :rocket: deploy

#3535 Fix wallet connect / gnosis
  hooks/useWeb3Account.tsx
  lib/blockchain/provider/alchemy/client.ts
  lib/blockchain/provider/ankr/client.ts
  lib/blockchain/publicClient.ts
  lib/blockchain/signAndVerify.ts
  lib/middleware/requireWalletSignature.ts
Labels: work-in-progress, :rocket: deploy

#3742 Whitespace for proposal board with description
  components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
  components/proposals/ProposalsPage.tsx
Labels: :rocket: deploy

#3741 Fixed deleting page node in a column deletes whole column node
  components/common/CharmEditor/components/@bangle.dev/core/node-view.ts
  components/common/CharmEditor/components/@bangle.dev/react/node-view-helpers.tsx
  components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
  components/common/CharmEditor/components/rowActions/__tests__/deleteRowNode.spec.ts
  components/common/CharmEditor/components/rowActions/rowActions.ts
  testing/prosemirror/renderTestEditor.ts
Labels: :rocket: deploy

#3753 Bug fix: filter out favorite page ids that dont exist in a space
  hooks/useFavoritePages.ts
Labels: :rocket: deploy

#3745 Revert "Revert "Fix wallet connect / gnosis (#3535)" (#3744)"
  charmClient/hooks/profile.ts
  components/_app/components/ConnectedAccounts.tsx
  components/settings/account/components/NewIdentityModal.tsx
  hooks/useWeb3Account.tsx
  lib/blockchain/provider/alchemy/client.ts
  lib/blockchain/provider/ankr/client.ts
  lib/blockchain/publicClient.ts
  lib/blockchain/signAndVerify.ts
  lib/middleware/requireWalletSignature.ts
Labels: :rocket: deploy

#3759 Fixed pinning nfts on empty state
  components/members/components/MemberProfile/components/ProfileWidgets/components/CollectionWidget/NftAvatarGallery/NftAvatarGalleryPopup.tsx
  hooks/useMyNfts.ts
Labels: :rocket: deploy

#3757 filter out markdown files based on view filter
  lib/focalboard/generateCsv.ts
  pages/api/pages/[id]/export-database.ts
Labels: :rocket: deploy

#3760 Improved layout for user identities section
  components/settings/Legend.tsx
  components/settings/account/AccountSettings.tsx
  components/settings/account/components/AccountPreferences.tsx
  components/settings/account/hooks/useIdentityTypes.tsx
  components/settings/profile/components/IdentityIcon.tsx
  components/settings/profile/components/IdentityModal.tsx
  components/settings/profile/components/Integration.tsx
Labels: :rocket: deploy

#3758 Show clicked related pages in modal
  components/[pageId]/DatabasePage/DatabasePage.tsx
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/common/BoardEditor/components/properties/PagesAutocomplete.tsx
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
  components/common/PageDialog/PageDialog.tsx
  components/common/PageDialog/hooks/usePageDialog.tsx
Labels: :rocket: deploy

#3765 Allow copying rubric criteria from templates
  __integration-tests__/server/pages/api/proposals/[id]/evaluation.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/rubric-answers.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/rubric-criteria.spec.ts
  charmClient/hooks/proposals.ts
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/RubricTemplatesButton.tsx
  lib/focalboard/createCardsFromProposals.ts
  lib/focalboard/updateCardsFromProposals.ts
  lib/proposals/interfaces.ts
  lib/proposals/rubric/__tests__/upsertRubricAnswers.spec.ts
  lib/proposals/rubric/__tests__/upsertRubricCriteria.spec.ts
  lib/proposals/rubric/getRubricTemplates.ts
  lib/proposals/rubric/interfaces.ts
  lib/proposals/rubric/upsertRubricAnswers.ts
  lib/proposals/rubric/upsertRubricCriteria.ts
  pages/api/proposals/[id]/rubric-criteria.ts
  pages/api/proposals/rubric-templates.ts
Labels: :rocket: deploy

#3763 Refresh ENS
  __integration-tests__/serverless/index.spec.ts
  charmClient/apis/blockchainApi.ts
  charmClient/hooks/blockchain.ts
  components/settings/account/components/TwoFactorAuthUser.tsx
  components/settings/profile/components/IdentityModal.tsx
  hooks/useENSName.tsx
  hooks/useGetEnsName.tsx
  jest.setup.ts
  lib/blockchain/__tests__/refreshENSName.spec.ts
  lib/blockchain/getENSName.ts
  lib/blockchain/refreshENSName.ts
  lib/members/__tests__/createMemberPropertyPermission.spec.ts
  lib/members/__tests__/getSpaceMemberRoles.spec.ts
  lib/profile/getEnsProfile.ts
  lib/users/createUser.ts
  lib/votes/__tests__/getVotesByPage.spec.ts
  pages/api/profile/add-wallets.ts
  pages/api/session/login.ts
  pages/api/v1/bounties/index.ts
  testing/__tests__/setupDatabase.spec.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#3764 Support for draft proposal templates
  __e2e__/po/proposalsList.po.ts
  __e2e__/proposals/archiveProposal.spec.ts
  __e2e__/proposals/freeFormProposalTemplate.spec.ts
  __e2e__/proposals/proposalDrafts.spec.ts
  __e2e__/proposals/structuredProposalTemplate.spec.ts
  __e2e__/proposals/voteOnProposal.spec.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/common/PageActions/components/ArchiveProposalAction.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/PageActionsMenu.tsx
  components/common/PageActions/components/PublishProposalAction.tsx
  components/common/TemplatesMenu/TemplatesMenu.tsx
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/GoBackButton.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
  components/proposals/ProposalPage/components/ProposalStickyFooter/components/CompleteDraftButton.tsx
  components/proposals/components/NewProposalButton.tsx
  components/proposals/hooks/useProposalTemplates.tsx
  components/proposals/hooks/useProposals.tsx
  lib/proposals/__tests__/getProposalTemplates.spec.ts
  lib/proposals/archiveProposals.ts
  lib/proposals/getCurrentStep.ts
  lib/proposals/getProposalTemplates.ts
  lib/proposals/getProposals.ts
  lib/proposals/goBackToStep.ts
  lib/proposals/publishProposal.ts
  lib/spaces/createSpace.ts
  lib/templates/__tests__/importWorkspacePages.spec.ts
  lib/templates/exports/templateCreator.json
  lib/templates/exports/templateGrantRecipient.json
  lib/templates/exports/templateGrantor.json
  lib/templates/exports/templateHackathon.json
  lib/templates/exports/templateImpactCommunity.json
  lib/templates/exports/templateNftCommunity.json
  lib/templates/exports/templateNounishDAO.json
  lib/templates/exports/templateOPGrant.json
  lib/templates/importWorkspacePages.ts
  lib/websockets/interfaces.ts
  pages/api/pages/[id]/index.ts
  pages/api/proposals/index.ts
  scripts/migrations/2024_03_06_proposalTemplateDrafts.ts
Labels: :rocket: deploy

#3768 Onchain credentials
  .ebstalk.apps.env/serverless.env
  .env.test.local.example
  charmClient/apis/credentialsApi.ts
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialRow.tsx
  components/settings/credentials/components/CredentialTemplateDialog.tsx
  lib/credentials/__tests__/issueProposalCredentialIfNecessary.spec.ts
  lib/credentials/__tests__/issueRewardCredentialIfNecessary.spec.ts
  lib/credentials/attest.ts
  lib/credentials/attestOffchain.ts
  lib/credentials/attestOnchain.ts
  lib/credentials/connectors.ts
  lib/credentials/external/exportSchemas.ts
  lib/credentials/external/getOnchainCredentials.ts
  lib/credentials/external/schemas.ts
  lib/credentials/issueProposalCredentialsIfNecessary.ts
  lib/credentials/issueRewardCredentialsIfNecessary.ts
  lib/credentials/schemas/index.ts
  lib/credentials/schemas/proposal.ts
  lib/credentials/schemas/reward.ts
  lib/webhookPublisher/interfaces.ts
  lib/webhookPublisher/publishEvent.ts
  package.json
  pages/api/credentials/index.ts
  serverless.yml
  serverless/sqs/worker.ts
Labels: :rocket: deploy, :rocket: serverless

#3780 Rewards board description
  components/proposals/ProposalsPage.tsx
  components/rewards/RewardsPage.tsx
Labels: :rocket: deploy

#3774 Instantly show reward board updates
  components/common/BoardEditor/focalboard/src/components/__snapshots__/centerPanel.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/viewHeader/__snapshots__/viewHeader.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx
  components/rewards/hooks/useRewardBlocks.tsx
  components/rewards/hooks/useRewardsBoard.ts
  lib/websockets/interfaces.ts
  pages/api/spaces/[id]/rewards/blocks/index.ts
Labels: :rocket: deploy

#3786 Boto
  components/settings/space/SpaceSettings.tsx
  components/settings/space/components/ConnectBoto.tsx
Labels: :rocket: deploy

#3565 Discord popup login
  __e2e__/fixtures/discordServer.ts
  __e2e__/po/login.po.ts
  __e2e__/sessions/loginDiscord.spec.ts
  __e2e__/sessions/signupDiscord.spec.ts
  charmClient/apis/discordApi.ts
  charmClient/hooks/discord.ts
  charmClient/hooks/farcaster.ts
  components/_app/GlobalComponents.tsx
  components/common/SpaceAccessGate/components/DiscordGate/DiscordGate.tsx
  components/login/components/DiscordLoginHandler.tsx
  components/settings/account/components/NewIdentityModal.tsx
  components/settings/account/components/otp/hooks/useTwoFactorAuth.tsx
  components/settings/profile/components/IdentityModal.tsx
  components/settings/roles/RoleSettings.tsx
  components/settings/roles/components/ImportDiscordRolesMenuItem.tsx
  components/settings/roles/components/ImportGuildRolesMenuItem.tsx
  components/settings/roles/hooks/useImportDiscordRoles.ts
  hooks/useDiscordConnection.tsx
  hooks/useRoles.ts
  lib/discord/getDiscordCallbackUrl.ts
  lib/discord/loginByDiscord.ts
  lib/oauth/interfaces.ts
  package.json
  pages/api/discord/callback.ts
  pages/api/discord/connect.ts
  pages/api/discord/import-roles.ts
  pages/api/discord/importRoles.ts
  pages/api/discord/login.ts
  pages/api/discord/oauth.ts
  pages/authenticate/discord.tsx
  pages/authenticate/otp.tsx
Labels: :rocket: deploy

#3792 Add additional checks to prevent early render
  components/common/PageLayout/PageLayout.tsx
Labels: :rocket: deploy

#3801 Improvements for proposal token voting
  components/common/CharmEditor/components/inlineVote/components/SingleChoiceForm.tsx
  components/common/form/CustomERCTokenForm.tsx
  components/common/form/InputSearchCrypto.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx
  components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/VoteSettings.tsx
  components/settings/proposals/components/EvaluationPermissions.tsx
  lib/blockchain/getTokenDecimals.ts
  lib/blockchain/getTokenSupplyAmount.ts
  lib/proposals/createProposal.ts
  lib/proposals/getProposalErrors.ts
  lib/snapshot/getTokenAmountOnBlockNumber.ts
  lib/votes/getVotingPowerForVotes.ts
Labels: :rocket: deploy

#3813 use TLS1.3 on load balancer in staging
  .cdk/staging-stack.ts
Labels: :rocket: deploy

#3814 Tls 3 prod
  .ebextensions/07_alb_sslpolicy.config
  .ebextensions_websockets/07_alb_sslpolicy.config
Labels: :rocket: deploy

#3817 Fixed user accounts layout
  components/settings/profile/components/Integration.tsx
Labels: :rocket: deploy

#3834 add Gaming Template
  components/common/CreateSpaceForm/TemplateIcon.tsx
  lib/spaces/config.ts
  lib/templates/exports/templateGaming.json
  lib/templates/importSpaceSettings.ts
  scripts/exportData/exportEntireSpace.ts
  scripts/exportData/exportNewTemplate.ts
Labels: :rocket: deploy

#3837 allow removing the creator of a space
  components/settings/roles/components/MemberActions.tsx
Labels: :rocket: deploy

#3842 fix db templates not appearing
  components/common/DatabaseEditor/store/cards.ts
  lib/databases/card.ts
Labels: :rocket: deploy

#3840 Add Zora / ZKSync token gate chains
  components/common/TokenGateModal/components/TokenGateBlockchainSelect.tsx
  components/common/TokenGateModal/components/TokenGateCollectables.tsx
  components/common/TokenGateModal/components/TokenGateContent.tsx
  components/common/TokenGateModal/components/TokenGateNft.tsx
  components/common/TokenGateModal/components/TokenGateTokens.tsx
  connectors/chains.ts
  lib/blockchain/provider/zksync/client.ts
  lib/blockchain/provider/zksync/config.ts
  lib/blockchain/provider/zksync/verifyNFTOwner.ts
  lib/blockchain/provider/zora/config.ts
  lib/tokenGates/validateTokenGateCondition.ts
Labels: :rocket: deploy

#3846 fix duplicating proposal templates
  components/proposals/ProposalPage/NewProposalPage.tsx
Labels: :rocket: deploy

#3859 cleanup page search and add it to link components
  charmClient/apis/pagesApi.ts
  charmClient/hooks/pages.ts
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
  components/common/CharmEditor/components/mention/components/Mention.tsx
  components/common/CharmEditor/components/mention/components/MentionsPopup.tsx
  components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
  components/common/CharmEditor/hooks/useGetPageMetaFromCache.ts
  components/common/PageIcon.tsx
  components/common/PageLayout/components/Sidebar/NavigationSidebar.tsx
  components/common/PageLayout/components/Sidebar/components/PageNavigation/components/AddNewCard.tsx
  components/common/PageLayout/components/Sidebar/components/PageNavigation/components/PageTreeItem.tsx
  components/common/PageLayout/components/Sidebar/components/SearchInWorkspaceModal.tsx
  components/common/PagesList.tsx
  hooks/useRootPages.ts
  hooks/useSearchPages.ts
Labels: :rocket: deploy

#3864 Show recent pages when using search and update the UI
  charmClient/hooks/helpers.ts
  charmClient/hooks/pages.ts
  components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
  components/common/DatabaseEditor/components/centerPanel.tsx
  components/common/PageLayout/components/Sidebar/components/SearchInWorkspaceModal.tsx
  hooks/useSearchPages.ts
  lib/pages/__tests__/getRecentHistory.spec.ts
  lib/pages/getPageMetaLite.ts
  lib/pages/getRecentHistory.ts
  lib/pages/interfaces.ts
  lib/utils/dates.ts
  pages/api/pages/recent-history.ts
  scripts/exportProposalScores.ts
Labels: :rocket: deploy
