Repository charmverse/app.charmverse.io, pull requests merged in 2024-01, with the labels that each got.

#3351 Use proposal permissions in structured proposal
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/proposals/ProposalPage/components/ProposalFormFieldInputs.tsx
  components/proposals/components/ProposalRewards/AttachRewardButton.tsx
Labels: :rocket: deploy

#3333 Edit proposal reviewers from proposals table
  charmClient/apis/proposalsApi.ts
  charmClient/hooks/proposals.ts
  components/common/BoardEditor/components/properties/UserSelect.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/ProposalsPage.tsx
  components/proposals/hooks/useProposals.tsx
  components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
  lib/focalboard/card.ts
  lib/pages/interfaces.ts
  lib/proposal/interface.ts
  lib/proposal/mapDbProposalToProposal.ts
  pages/api/spaces/[id]/proposals/index.ts
Labels: :rocket: deploy

#3246 commit core right away before running tests
  .github/actions/install/action.yml
  .github/workflows/test_and_deploy.yml
Labels: work-in-progress

#3368 allow admin to edit all settings even when using a template
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx
Labels: :rocket: deploy

#3373 Fix state for proposals
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/proposals/ProposalPage/components/ProposalProperties/CustomPropertiesAdapter.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/ProposalsPage.tsx
  components/proposals/ProposalsPageProviders.tsx
  components/proposals/components/ProposalDialog/ProposalDialog.tsx
  components/proposals/components/ProposalDialog/hooks/useProposalDialog.tsx
  lib/proposal/__tests__/archiveProposal.spec.ts
Labels: :rocket: deploy

#3374 make sure we delete vote when going backward in proposals
  charmClient/hooks/proposals.ts
  components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx
  lib/proposal/__tests__/goBackToEvaluationStep.spec.ts
  lib/proposal/goBackToEvaluationStep.ts
  pages/api/proposals/[id]/back-to-step.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#3362 Hypersub token gate
  components/common/Avatar.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateConditions.tsx
  components/common/SpaceAccessGate/components/TokenGate/TokenGateContent.tsx
  components/common/TokenGateModal/components/TokenGateCollectableFields.tsx
  components/common/TokenGateModal/components/TokenGateCollectables.tsx
  components/common/TokenGateModal/components/TokenGateContent.tsx
  components/common/TokenGateModal/components/TokenGateHypersub.tsx
  components/common/TokenGateModal/hooks/useCollectablesForm.tsx
  components/common/TokenGateModal/hooks/useTokenGateModalContext.tsx
  components/common/TokenGateModal/utils/helpers.ts
  components/common/TokenGateModal/utils/utils.ts
  components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
  connectors/chains.ts
  lib/blockchain/updateHypersubDetails.ts
  lib/blockchain/updateTokenGateDetails.ts
  lib/tokenGates/__tests__/daylight.spec.ts
  lib/tokenGates/__tests__/humanizeConditions.spec.ts
  lib/tokenGates/daylight.ts
  lib/tokenGates/evaluateEligibility.ts
  lib/tokenGates/humanizeConditions.ts
  lib/tokenGates/hypersub/abi.ts
  lib/tokenGates/hypersub/getHypersubDetails.ts
  lib/tokenGates/interfaces.ts
  lib/tokenGates/processTokenGateConditions.ts
  lib/tokenGates/validateTokenGateConditions.ts
  lib/tokenGates/verifyTokenGateMembership.ts
  lib/tokenGates/verifyTokenGates.ts
  pages/api/token-gates/review.ts
  public/images/logos/fabric-xyz.svg
Labels: :rocket: deploy

#3377 Feat/edit form field UI
  components/common/form/FormField.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx
  theme/index.ts
Labels: :rocket: deploy

#3376 Allow updating workflow of templates and draft proposals
  charmClient/hooks/proposals.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/WorkflowSelect.tsx
  lib/proposal/updateProposalWorkflow.ts
  pages/api/proposals/[id]/workflow.ts
Labels: :rocket: deploy

#3383 Fix draft saving
  __e2e__/po/document.po.ts
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/components/ProposalRewards/ProposalRewards.tsx
Labels: :rocket: deploy

#3384 clear evaluation results when going back to draft
  __integration-tests__/server/pages/api/proposals/[id]/publish.spec.ts
  charmClient/hooks/proposals.ts
  components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx
  components/proposals/ProposalPage/components/ProposalStickyFooter/components/CompleteDraftButton.tsx
  components/proposals/components/ProposalStatusSelect.tsx
  components/proposals/components/ProposalStepSelect.tsx
  lib/proposal/__tests__/goBackToStep.spec.ts
  lib/proposal/goBackToStep.ts
  pages/api/proposals/[id]/back-to-step.ts
  pages/api/proposals/[id]/publish.ts
Labels: :rocket: deploy

#3385 add default rubric criteria when setting up a new proposal
  __e2e__/proposals/proposalEvaluationCreation.spec.ts
  __e2e__/proposals/proposalEvaluationTemplatesCreation.spec.ts
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/RubricCriteriaSettings.tsx
Labels: :rocket: deploy

#3393 require rubric criteria title
  components/proposals/ProposalPage/hooks/useNewProposal.tsx
Labels: :rocket: deploy

#3390 Proposal status and step column extras
  charmClient/apis/proposalsApi.ts
  components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumnHeader.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableGroupHeaderRow.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyTemplateMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/viewHeaderRowsMenu.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/components/ProposalStatusSelect.tsx
  components/proposals/components/ProposalStepSelect.tsx
  components/proposals/components/ProposalsBoard/utils/boardData.ts
  components/proposals/hooks/useBatchUpdateProposalStatusOrStep.ts
  components/proposals/hooks/useProposals.tsx
  lib/focalboard/__tests__/setDatabaseProposalProperties.spec.ts
  lib/focalboard/card.ts
  lib/focalboard/cardFilter.ts
  lib/focalboard/filterClause.ts
  lib/focalboard/proposalDbProperties.ts
  lib/focalboard/setDatabaseProposalProperties.ts
  lib/notifications/proposals/__tests__/createProposalNotifications.spec.ts
  lib/proposal/__tests__/publishProposal.spec.ts
  lib/proposal/createVoteIfNecessary.ts
  lib/proposal/getCurrentStep.ts
  lib/proposal/mapDbProposalToProposal.ts
  lib/proposal/updateProposalStatusOnly.ts
  testing/mocks/proposal.ts
Labels: :rocket: deploy

#3397 Remove "create vote" button except for Snapshot - also bring back vote details for Snapshot votes
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/VoteEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/PublishToSnapshot.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/components/ConnectSnapshot.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/components/InputVotingStrategies.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/components/PublishingForm.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVoteDetails.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/SnapshotVotingForm.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/DisplayChoiceScore.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/DraggableRankedItem.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/MultiChoiceVoting.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/RankedVoting.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/SingleChoiceVoting.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/components/WeightedVoting.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/hooks/useSnapshotVoting.ts
  components/settings/space/components/SpaceIntegrations.tsx
  components/votes/components/CreateVoteModal.tsx
Labels: :rocket: deploy

#3391 Builder Protocol DAO Token Gate
  components/common/TokenGateModal/components/TokenGateDao.tsx
  components/common/TokenGateModal/components/TokenGateHome.tsx
  components/common/TokenGateModal/hooks/useDaoForm.tsx
  components/common/TokenGateModal/utils/getDaoUnifiedAccessControlConditions.ts
  components/common/TokenGateModal/utils/utils.ts
  connectors/chains.ts
Labels: :rocket: deploy

#3405 remove null values from page meta
  pages/api/spaces/[id]/pages.ts
Labels: :rocket: deploy

#3402 Import custom proposal properties in proposal as a source boards
  components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
  components/proposals/components/ProposalsBoard/utils/boardData.ts
  lib/focalboard/__tests__/createCardsFromProposals.spec.ts
  lib/focalboard/__tests__/setDatabaseProposalProperties.spec.ts
  lib/focalboard/__tests__/updateCardsFromProposals.spec.ts
  lib/focalboard/board.ts
  lib/focalboard/createCardsFromProposals.ts
  lib/focalboard/setDatabaseProposalProperties.ts
  lib/focalboard/updateCardsFromProposals.ts
  testing/generateBoardStub.ts
  testing/setupDatabase.ts
Labels: :rocket: deploy

#3409 Fix/proposal evaluation
  components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx
  lib/focalboard/createCardsFromProposals.ts
  lib/focalboard/generateResyncedProposalEvaluationForCard.ts
  lib/focalboard/setDatabaseProposalProperties.ts
  lib/focalboard/updateCardsFromProposals.ts
  lib/proposal/rubric/aggregateResults.ts
  scripts/query.ts
Labels: :rocket: deploy

#3408 simplify context for proposals and rewards
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/common/PageLayout/PageLayout.tsx
  components/common/PageLayout/SharedPageLayout.tsx
  components/proposals/ProposalsPage.tsx
  components/proposals/ProposalsPageProviders.tsx
  components/rewards/RewardsPage.tsx
  components/rewards/RewardsPageWithProviders.tsx
  components/rewards/hooks/useRewardsBoard.tsx
  hooks/useDragDrop.ts
  pages/[domain]/proposals/index.tsx
  pages/[domain]/rewards/index.tsx
  pages/_app.tsx
  stories/ProposalsPage/ProposalsPageStory.tsx
Labels: :rocket: deploy

#3361 Join workspace via proposal template
  charmClient/hooks/spaces.ts
  components/common/PageActions/components/CopyPageLinkAction.tsx
  components/common/RouteGuard.tsx
  components/proposals/components/NewProposalButton.tsx
  hooks/useCustomJoinSpace.ts
  lib/invites/acceptInvite.ts
  lib/spaces/customConditionJoinSpace.ts
  lib/spaces/joinSpace.ts
  pages/api/spaces/[id]/custom-join.ts
Labels: :rocket: deploy

#3426 add script to update criteria steps order according to templates
  scripts/fixProposalSteps.ts
Labels: work-in-progress

#3427 Fix UI for select property in view headers menu
  components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PersonPropertyTemplateMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyTemplateMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/SelectPropertyTemplateMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/viewHeaderRowsMenu.tsx
  components/common/CharmEditor/components/BlockAligner.tsx
  components/common/TemplatesMenu/TemplatePageActionMenu.tsx
  components/common/TemplatesMenu/TemplatesMenu.tsx
  components/proposals/components/NewProposalButton.tsx
Labels: :rocket: deploy

#3428 Fix archive proposal action
  __e2e__/po/proposalPage.po.ts
  __e2e__/po/proposalsList.po.ts
  __e2e__/proposals/archiveProposal.spec.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyTemplateMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/viewHeaderRowsMenu.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepActions.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/FeedbackEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricAnswersForm.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/VoteEvaluation.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/components/ProposalRewards/AttachRewardButton.tsx
  components/proposals/components/ProposalRewards/ProposalRewards.tsx
  components/proposals/components/ProposalStatusSelect.tsx
  components/proposals/components/ProposalStepSelect.tsx
  lib/focalboard/card.ts
  lib/focalboard/proposalDbProperties.ts
  lib/proposal/getProposalEvaluationStatus.ts
  lib/proposal/goBackToStep.ts
  lib/proposal/interface.ts
  pages/api/proposals/[id]/publish.ts
  pages/api/proposals/[id]/submit-result.ts
Labels: :rocket: deploy

#3432 Enable updated column on proposals page and make sure we update the page
  .storybook/preview.tsx
  __integration-tests__/server/pages/api/proposals/[id]/rubric-answers.spec.ts
  components/common/BoardEditor/focalboard/src/components/properties/createdAt/createdAt.scss
  components/common/BoardEditor/focalboard/src/components/properties/createdAt/createdAt.tsx
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.scss
  components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/widgets/propertyMenu.tsx
  components/common/BoardEditor/focalboard/src/widgets/propertyTypes.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/components/ProposalsBoard/utils/boardData.ts
  lib/focalboard/board.ts
  lib/proposal/__tests__/archiveProposal.spec.ts
  lib/proposal/__tests__/updateProposal.spec.ts
  lib/proposal/archiveProposal.ts
  lib/proposal/blocks/upsertBlocks.ts
  lib/proposal/createDefaultProposal.ts
  lib/proposal/createProposal.ts
  lib/proposal/goBackToStep.ts
  lib/proposal/publishProposal.ts
  lib/proposal/rubric/__tests__/upsertRubricAnswers.spec.ts
  lib/proposal/rubric/__tests__/upsertRubricCriteria.spec.ts
  lib/proposal/rubric/upsertRubricAnswers.ts
  lib/proposal/rubric/upsertRubricCriteria.ts
  lib/proposal/setPageUpdatedAt.ts
  lib/proposal/submitEvaluationResult.ts
  lib/proposal/updateProposal.ts
  lib/proposal/updateProposalEvaluation.ts
  lib/proposal/updateProposalWorkflow.ts
  pages/_app.tsx
  pages/api/proposals/[id]/archive.ts
  pages/api/proposals/[id]/evaluation.ts
  pages/api/proposals/[id]/index.ts
  pages/api/proposals/[id]/rubric-criteria.ts
  pages/api/proposals/[id]/workflow.ts
Labels: :rocket: deploy

#3449 Space template proposals adjustments
  lib/templates/__tests__/exportSpaceSettings.spec.ts
  lib/templates/__tests__/importSpaceSettings.spec.ts
  lib/templates/__tests__/importWorkspacePages.spec.ts
  lib/templates/exportWorkspacePages.ts
  lib/templates/importSpaceData.ts
  lib/templates/importSpaceSettings.ts
  lib/templates/importWorkspacePages.ts
Labels: :rocket: deploy

#3450 Add global confirmation modal
  charmClient/apis/proposalsApi.ts
  components/_app/GlobalComponents.tsx
  components/_app/components/ConfirmationModal.tsx
  components/_app/components/Snackbar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/PublishRewardsButton.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricAnswersForm.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx
  components/proposals/ProposalPage/components/WorkflowSelect.tsx
  components/proposals/hooks/useBatchUpdateProposalStatusOrStep.ts
  hooks/useConfirmationModal.tsx
  pages/_app.tsx
Labels: :rocket: deploy

#3447 Update proposal as a source board evaluation properties
  __e2e__/database/databaseProposalsAsSource.spec.ts
  components/common/BoardEditor/components/cardProperties/CardDetailProperty.tsx
  components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts
  components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableHeader.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.spec.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
  components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx
  components/common/BoardEditor/focalboard/src/components/viewSidebar/viewPropertyOptions.tsx
  lib/focalboard/__tests__/createCardsFromProposals.spec.ts
  lib/focalboard/__tests__/extractCardProposalProperties.spec.ts
  lib/focalboard/__tests__/extractDatabaseProposalProperties.spec.ts
  lib/focalboard/__tests__/updateCardsFromProposals.spec.ts
  lib/focalboard/createCardsFromProposals.ts
  lib/focalboard/extractCardProposalProperties.ts
  lib/focalboard/extractDatabaseProposalProperties.ts
  lib/focalboard/generateResyncedProposalEvaluationForCard.ts
  lib/focalboard/getPropertyName.ts
  lib/focalboard/setDatabaseProposalProperties.ts
  lib/focalboard/updateCardsFromProposals.ts
  lib/proposal/createRewardsForProposal.ts
  scripts/migrations/2024_01_16_deleteProposalEvaluationProperties.ts
Labels: :rocket: deploy

#3452 Check permissions for each evaluation step
  __integration-tests__/server/pages/api/proposals/[id]/index.public.spec.ts
  __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
  components/common/PageActions/components/DuplicatePageAction.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx
  components/proposals/components/ProposalRewards/CreateProposalRewardsButton.tsx
  components/proposals/hooks/useProposals.tsx
  lib/focalboard/updateCardFormFieldPropertiesValue.ts
  lib/focalboard/updateCardsFromProposals.ts
  lib/proposal/interface.ts
  lib/proposal/mapDbProposalToProposal.ts
  pages/api/proposals/[id]/index.ts
  stories/ProposalsPage/Proposals.stories.tsx
  testing/mocks/proposal.ts
Labels: :rocket: deploy

#3446 fix proposals in space templates
  lib/spaces/createSpace.ts
  lib/templates/__tests__/exportSpaceData.spec.ts
  lib/templates/__tests__/exportSpaceSettings.spec.ts
  lib/templates/__tests__/getImportData.spec.ts
  lib/templates/__tests__/importSpaceData.spec.ts
  lib/templates/__tests__/importSpaceSettings.spec.ts
  lib/templates/__tests__/importWorkspacePages.spec.ts
  lib/templates/exportSpaceSettings.ts
  lib/templates/exportWorkspacePages.ts
  lib/templates/exports/charmverse-demo.json
  lib/templates/exports/templateCreator.json
  lib/templates/exports/templateGrantRecipient.json
  lib/templates/exports/templateGrantor.json
  lib/templates/exports/templateHackathon.json
  lib/templates/exports/templateImpactCommunity.json
  lib/templates/exports/templateNftCommunity.json
  lib/templates/exports/templateNounishDAO.json
  lib/templates/importSpaceData.ts
  lib/templates/importSpaceSettings.ts
  lib/templates/importWorkspacePages.ts
  page-backup-05-22.json
  scripts/refreshSpaceTemplates.ts
Labels: :rocket: deploy

#3453 Updated proposal lens publish workflow
  charmClient/hooks/lens.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/CommentsFooter/PageComments.tsx
  components/[pageId]/DocumentPage/components/CreateLensPublication.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/common/CharmEditor/components/inlineComment/components/InlineCommentSubMenu.tsx
  components/common/CharmEditor/index.ts
  components/members/components/MemberProfile/components/ProfileWidgets/components/LensProfileWidget.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/ProposalSocialShare.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/settings/account/AccountSettings.tsx
  components/settings/account/components/LensPublication.tsx
  components/settings/account/hooks/useLensProfile.ts
  components/settings/profile/components/IdentityIcon.tsx
  components/settings/space/SpaceSettings.tsx
  hooks/useCreateLensPublication.ts
  lib/lens/uploadToArweave.ts
  package.json
  pages/api/lens/upload-arweave.ts
  patches/@lens-protocol+react+2.0.0-alpha.27.patch
  public/images/logos/lens_logo.png
  public/images/logos/lens_logo.svg
Labels: :rocket: deploy

#3463 Proposals context fixes and cleanup
  __integration-tests__/server/pages/api/proposals/[id]/archive.spec.ts
  charmClient/apis/permissions/index.ts
  charmClient/apis/permissions/proposalsApi.ts
  charmClient/apis/proposalsApi.ts
  charmClient/hooks/proposals.ts
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/[pageId]/DocumentPage/components/ProposalArchivedBanner.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/common/PageActions/KanbanPageActionButton.tsx
  components/common/PageActions/components/ArchiveProposalAction.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/PageActionsMenu.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx
  components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
  components/proposals/ProposalsPage.tsx
  components/proposals/components/ProposalRewards/AttachRewardButton.tsx
  components/proposals/components/ProposalRewards/CreateProposalRewardsButton.tsx
  components/proposals/hooks/useProposals.tsx
  components/proposals/hooks/useProposalsBoard.tsx
  hooks/usePage.ts
  lib/pages/trashPages.ts
  lib/proposal/archiveProposal.ts
  lib/websockets/interfaces.ts
  pages/[domain]/proposals/index.tsx
  pages/_app.tsx
  pages/api/permissions/proposals/compute-proposal-permissions.ts
  pages/api/proposals/[id]/archive.ts
Labels: :rocket: deploy

#3459 2fa required config
  components/_app/components/UserOnboardingDialog.tsx
  components/settings/account/components/otp/components/SetupTwoFactorAuthGlobal.tsx
Labels: :rocket: deploy

#3470 Remove otp + analytics
  charmClient/hooks/profile.ts
  components/common/form/fields/NumberInputField.tsx
  components/settings/account/components/TwoFactorAuthUser.tsx
  components/settings/account/components/otp/components/BackupCodes.tsx
  components/settings/account/components/otp/components/ConfirmAuthCode.tsx
  components/settings/account/components/otp/components/DeleteOtpModal.tsx
  components/settings/account/components/otp/components/GetQrCodeModal.tsx
  components/settings/account/components/otp/components/ResetRecoveryCodeModal.tsx
  components/settings/account/components/otp/components/TwoFactorAuthSetupModal.tsx
  components/settings/space/components/LabelWithCopy.tsx
  lib/metrics/mixpanel/interfaces/UserEvent.ts
  lib/profile/otp/deleteUserOtp.ts
  pages/api/profile/otp/activate.ts
  pages/api/profile/otp/index.ts
  stories/Common/Form.stories.tsx
Labels: :rocket: deploy

#3478 update event settings for proposals
  components/settings/space/SpaceSettings.tsx
  components/settings/space/components/NotificationToggles.tsx
Labels: :rocket: deploy, :rocket: serverless

#3489 Support linking to proposal templates
  components/[pageId]/DocumentPage/components/ProposalArchivedBanner.tsx
  components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx
  components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
  lib/utilities/__tests__/strings.spec.ts
  lib/utilities/strings.ts
Labels: :rocket: deploy

#3485 Feat/external credentials
  __integration-tests__/server/pages/api/spaces/[id]/set-default-public-pages.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/set-public-bounty-board.spec.ts
  background/ceramicServer/README.md
  background/ceramicServer/authenticate.ts
  background/ceramicServer/credentials.gql
  background/ceramicServer/deploy-composites.ts
  background/ceramicServer/generated/composite-definition.js
  background/ceramicServer/generated/composite-definition.json
  background/ceramicServer/package.json
  background/ceramicServer/run-deploy.ts
  charmClient/apis/credentialsApi.ts
  charmClient/hooks/credentialHooks.ts
  components/credentials/CredentialsSelect.tsx
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialRow.tsx
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialsList.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/settings/credentials/SpaceCredentialSettings.tsx
  components/settings/credentials/components/CredentialEventToggle.tsx
  components/settings/credentials/components/CredentialEventsForm.tsx
  components/settings/credentials/components/CredentialTemplateDialog.tsx
  components/settings/credentials/components/CredentialTemplateRow.tsx
  components/settings/credentials/components/CredentialTemplates.tsx
  components/settings/credentials/components/ProposalCredentialPreview.tsx
  config/constants.ts
  connectors/chains.ts
  docker-compose.yml
  hooks/useGetEnsName.tsx
  hooks/useWeb3Signer.ts
  lib/credentials/__tests__/issueProposalCredentialIfNecessary.spec.ts
  lib/credentials/attest.ts
  lib/credentials/connectors.ts
  lib/credentials/constants.ts
  lib/credentials/external/exportSchemas.ts
  lib/credentials/external/getExternalCredentials.ts
  lib/credentials/external/schemas-1706033462641.json
  lib/credentials/external/schemas.ts
  lib/credentials/getAllUserCredentials.ts
  lib/credentials/issueProposalCredentialsIfNecessary.ts
  lib/credentials/queriesAndMutations.ts
  lib/credentials/templates.ts
  package.json
  pages/api/credentials/events.ts
  pages/api/credentials/index.ts
  public/images/logos/devfolio.png
  public/images/logos/eas.png
Labels: :rocket: deploy

#3488 Feat/db table polish
  __e2e__/po/databasePage.po.ts
  components/common/BoardEditor/components/properties/PopupFieldWrapper.tsx
  components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx
  components/common/BoardEditor/components/properties/TextInput.tsx
  components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
  components/common/BoardEditor/components/properties/UserSelect.tsx
  components/common/BoardEditor/focalboard/src/components/properties/link/__snapshots__/link.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/properties/link/link.scss
  components/common/BoardEditor/focalboard/src/components/properties/link/link.tsx
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap
  components/common/BoardEditor/focalboard/src/components/table/table.scss
  components/common/PopperPopup.tsx
  components/common/form/InputSearchMember.tsx
  components/common/form/fields/SelectField.tsx
  components/proposals/components/ProposalStatusSelect.tsx
  components/proposals/components/ProposalStepSelect.tsx
Labels: :rocket: deploy

#3492 Add the option to set the template for proposal milestones (rewards)
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/RewardProperties.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/RewardTemplateSelect.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/AttachRewardButton.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
  components/proposals/ProposalPage/components/TemplateSelect.tsx
  components/proposals/ProposalPage/hooks/useNewProposal.tsx
  components/proposals/components/ProposalRewards/AttachRewardButton.tsx
  components/rewards/components/NewInlineReward.tsx
  components/rewards/components/NewRewardButton.tsx
  components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
  docker-compose.yml
  lib/proposal/__tests__/isProposalAuthor.spec.ts
  lib/proposal/__tests__/isProposalReviewer.spec.ts
  lib/proposal/interface.ts
  lib/proposal/isProposalReviewer.ts
  pages/api/proposals/[id]/index.ts
  scripts/query.ts
  stories/Rewards/Pages/NewRewardPage.stories.tsx
  testing/setupDatabase.ts
  testing/utils/proposals.ts
Labels: :rocket: deploy

#3506 Fixed clicking on links opening two tabs on readonly editor
  components/common/CharmEditor/InlineCharmEditor.tsx
  components/common/CharmEditor/components/link/link.plugins.ts
  components/common/CharmEditor/plugins.ts
Labels: :rocket: deploy

#3502 Add reviewers to feedback step
  .github/workflows/test_and_deploy.yml
  __e2e__/proposals/proposalCustomProperties.spec.ts
  __e2e__/proposals/proposalEvaluationCreation.spec.ts
  __e2e__/proposals/proposalEvaluationTemplatesCreation.spec.ts
  charmClient/apis/rewardsApi.ts
  components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
  components/common/BoardEditor/focalboard/src/components/viewHeader/ViewHeaderRowsMenu/components/PropertyTemplateMenu.tsx
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepActions.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/FeedbackEvaluation.tsx
  components/proposals/components/ProposalsHeaderRowsMenu.tsx
  components/rewards/components/RewardApplicationPage/components/ApplicationComments.tsx
  components/settings/proposals/components/EvaluationPermissions.tsx
  components/settings/proposals/constants.tsx
  lib/proposal/createDefaultProposal.ts
  lib/proposal/createProposal.ts
  lib/proposal/mapDbProposalToProposal.ts
  pages/api/proposals/[id]/submit-result.ts
  pages/api/reward-applications/comments/[commentId].ts
  pages/api/spaces/[id]/proposals/index.ts
  scripts/migrations/2024_01_25_feedback_reviewers.ts
Labels: :rocket: deploy

#3511 dont override default reward type for new rewards
  components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
Labels: :rocket: deploy

#3503 Setup ceramic staging instance
  .ebextensions_ceramic/00_env_vars.config
  .ebextensions_ceramic/01_env_health_ignore_400.config
  .ebstalk.apps.env/ceramic.env
  .github/actions/build_docker_image/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  __integration-tests__/server/pages/api/credentials/templates.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/set-default-public-pages.spec.ts
  __integration-tests__/server/pages/api/spaces/[id]/set-public-bounty-board.spec.ts
  adapters/redis/redisClient.ts
  background/ceramicServer/ceramic-client.ts
  background/ceramicServer/run-deploy.ts
  charmClient/apis/credentialsApi.ts
  docker-compose.yml
  esbuild.ceramic.ts
  lib/credentials/apolloClientWithRedisCache.ts
  lib/credentials/attest.ts
  lib/credentials/external/getExternalCredentials.ts
  lib/credentials/getAllUserCredentials.ts
  lib/credentials/queriesAndMutations.ts
  lib/credentials/templates.ts
  package.json
  pages/api/credentials/templates.ts
Labels: :rocket: deploy

#3497 OTP wallet login
  charmClient/charmClient.ts
  charmClient/hooks/profile.ts
  components/_app/GlobalComponents.tsx
  components/login/components/LoginButton.tsx
  components/login/components/VerifyLoginOtpModal.tsx
  components/rewards/components/RewardProperties/components/RewardSignupButton.tsx
  hooks/useUser.tsx
  hooks/useVerifyLoginOtp.tsx
  hooks/useWeb3Account.tsx
  lib/metrics/mixpanel/interfaces/UserEvent.ts
  lib/session/config.ts
  pages/_app.tsx
  pages/api/profile/index.ts
  pages/api/profile/otp/verify.ts
  pages/api/session/login.ts
  pages/authenticate/otp.tsx
  testing/customRender.tsx
Labels: :rocket: deploy

#3526 fix snapshot voting
  components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/VoteEvaluation.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/PublishToSnapshot.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/components/PublishingForm.tsx
  components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/SnapshotVotingForm.tsx
Labels: :rocket: deploy

#3522 Update Ceramic model and drop feature flags
  background/ceramicServer/credentials.gql
  background/ceramicServer/deploy-composites.ts
  background/ceramicServer/generated/composite-definition.js
  background/ceramicServer/generated/composite-definition.json
  components/members/components/MemberProfile/components/ProfileTabs.tsx
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialsList.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/settings/SettingsContent.tsx
  lib/credentials/issueProposalCredentialsIfNecessary.ts
  lib/credentials/queriesAndMutations.ts
Labels: :rocket: deploy

#3528 Update composites
  background/ceramicServer/credentials.gql
  background/ceramicServer/deploy-composites.ts
  background/ceramicServer/generated/composite-definition.js
  background/ceramicServer/generated/composite-definition.json
  components/members/components/MemberProfile/components/ProfileTabs.tsx
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialsList.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/settings/SettingsContent.tsx
  lib/credentials/issueProposalCredentialsIfNecessary.ts
  lib/credentials/queriesAndMutations.ts
Labels: :rocket: deploy

#3534 Fix build cache
  .ebstalk.apps.env/ceramic.env
  .github/actions/build/action.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/test_and_deploy.yml
  .github/workflows/update_core_pkg.yml
  background/ceramicServer/ceramic-client.ts
  background/ceramicServer/credentials.gql
  background/ceramicServer/deploy-composites.ts
  background/ceramicServer/generated/composite-definition.js
  background/ceramicServer/generated/composite-definition.json
  components/members/components/MemberProfile/components/ProfileTabs.tsx
  components/members/components/MemberProfile/components/UserCredentials/UserCredentialsList.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/settings/SettingsContent.tsx
  lib/credentials/issueProposalCredentialsIfNecessary.ts
  lib/credentials/queriesAndMutations.ts
Labels: :rocket: deploy

#3540 add more obvious button at bottom of forms when using form proposals
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/components/ProposalProperties.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/hooks/useProposal.ts
  components/common/form/FormField.tsx
  components/common/form/FormFieldInputs.tsx
  components/common/form/FormFieldsEditor.tsx
  components/proposals/ProposalPage/NewProposalPage.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx
  components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/RewardSettings.tsx
  components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/AttachRewardButton.tsx
  components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
  components/proposals/ProposalPage/hooks/useNewProposal.tsx
  lib/proposal/interface.ts
  middleware.ts
Labels: :rocket: deploy

#3546 Proposal author column in proposal as a source boards
  components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts
  components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
  lib/focalboard/cardFilter.ts
  lib/focalboard/createCardsFromProposals.ts
  lib/focalboard/extractCardProposalProperties.ts
  lib/focalboard/extractDatabaseProposalProperties.ts
  lib/focalboard/setDatabaseProposalProperties.ts
  lib/focalboard/updateCardsFromProposals.ts
  scripts/migrations/2024_01_30_addProposalAuthorColumn.ts
Labels: :rocket: deploy

#3530 Editor context
  components/[pageId]/DocumentPage/DocumentPage.tsx
  components/[pageId]/DocumentPage/DocumentPageProviders.tsx
  components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx
  components/[pageId]/DocumentPage/components/Sidebar/components/CommentsSidebar.tsx
  components/[pageId]/DocumentPage/components/Sidebar/components/SuggestionsSidebar.tsx
  components/common/CharmEditor/CharmEditor.tsx
  components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
  components/common/PageDialog/components/NewDocumentPage.tsx
  components/proposals/ProposalPage/NewProposalPage.tsx
  hooks/useCharmEditorView.tsx
  stories/CharmEditor/renderEditor.tsx
Labels: :rocket: deploy

#3554 Add option to set Home page
  charmClient/hooks/spaces.ts
  components/common/PageActions/components/DatabasePageActionList.tsx
  components/common/PageActions/components/DocumentPageActionList.tsx
  components/common/PageActions/components/SetAsHomePageAction.tsx
  components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
  lib/session/__tests__/getDefaultPageForSpace.spec.ts
  lib/session/getDefaultPageForSpace.ts
  lib/spaces/updateSpace.ts
Labels: :rocket: deploy

#3548 Loop Crypto - Minimum amount for the user to have in his wallet
  lib/subscription/createCryptoSubscription.ts
Labels: :rocket: deploy

#3521 Discord otp
  charmClient/apis/discordApi.ts
  components/login/components/LoginButton.tsx
  components/login/components/VerifyLoginOtpModal.tsx
  components/settings/account/components/otp/components/ConfirmAuthCode.tsx
  hooks/useDiscordConnection.tsx
  pages/api/discord/callback.ts
  pages/api/discord/login.ts
  pages/api/profile/otp/verify.ts
  pages/authenticate/otp.tsx
Labels: :rocket: deploy

#3533 Otp magic link login
  charmClient/apis/googleApi.ts
  components/_app/BaseAuthenticateProviders.tsx
  components/invite/page/PageInviteLink.tsx
  components/invite/page/hooks/useMagicLink.spec.ts
  components/invite/page/hooks/useMagicLink.ts
  hooks/useFirebaseAuth.tsx
  pages/api/google/verify-magic-link.ts
  pages/authenticate/index.tsx
Labels: :rocket: deploy

#3543 OTP google login
  charmClient/apis/googleApi.ts
  hooks/useGoogleLogin.ts
  pages/api/google/code.ts
Labels: :rocket: deploy
